unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track Health Insurance Information for a Patient</description>
    <label>Application</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>The Status from the Application Submitted/New to till Approved or Rejected.</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Need More Information</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Payment Error</fullName>
                <isActive>false</isActive>
                <label>Payment Error</label>
            </value>
            <value>
                <fullName>Payment Processing</fullName>
                <isActive>false</isActive>
                <label>Payment Processing</label>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Care_Program__c.field-meta.xml
<CustomField>
    <fullName>Care_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Care Program, Populate Name of the Care Program for the Application.</description>
    <label>Care Program</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CareProgram.Care_Program_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.Application_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>CareProgram.Status</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Applications (Care Program)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/No_of_People_in_the_Household__c.field-meta.xml
<CustomField>
    <fullName>No_of_People_in_the_Household__c</fullName>
    <description>Number of People in the Patient/Applicant House.</description>
    <label>No. Of People In The Household</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Poverty_Level__c.field-meta.xml
<CustomField>
    <fullName>Poverty_Level__c</fullName>
    <description>This field get Auto Calculated based on Financial Information.</description>
    <label>Poverty Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Total_annual_Household_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_annual_Household_Income__c</fullName>
    <description>Combined gross income of all members of a household.</description>
    <label>Total Annual Household Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/TAP_ApplicationTrigger_Handler.cls
/****************************************************************************************************************************************************************
* @author IVL Dev
* @date 12-May-2020
* @description Handler is for Application Trigger
****************************************************************************************************************************************************************/
public class TAP_ApplicationTrigger_Handler extends TriggerHandler {
    
    private List<Application__c> newApplications;
    private List<Application__c> oldApplications;
    private Map<Id,Application__c> newApplicationsMap;
    private Map<Id,Application__c> oldApplicationsMap;
    
    public TAP_ApplicationTrigger_Handler() {
        newApplications = Trigger.new;
        if(Trigger.old == null) {
            oldApplications = new List<Application__c>();
        } else {
            oldApplications = Trigger.old;
        }
        newApplicationsMap = (Map<Id, Application__c>) Trigger.newMap;
        if(Trigger.oldMap == null) {
            oldApplicationsMap = new Map<Id, Application__c>();
        } else {
            oldApplicationsMap = (Map<Id, Application__c>) Trigger.oldMap;
        }
    }
    
   /*********************************************************************************
	*Context Overrides.Overrides the beforeInsert method of TriggerHandler class.
	*Methods from Application Helper will be called beforeInsert.
	*********************************************************************************/ 
    public override void beforeInsert() {
        updateApplicationStatusDuration();
        calculateIncomeBasedAttributes();
        TAP_Application_Helper.copyEmailIdFromAccount(newApplications,oldApplicationsMap);
    }
    
    /*********************************************************************************
    *Context Overrides.Overrides the before update method of TriggerHandler class.
	*Methods from Application Helper will be called  before Update.
    *********************************************************************************/	 
    
    public override void beforeUpdate() {
        updateApplicationStatusDuration();
        calculateIncomeBasedAttributes();
        TAP_Application_Helper.copyEmailIdFromAccount(newApplications,oldApplicationsMap);
    }
   /*********************************************************************************
    *Context Overrides.Overrides the afterInsert method of TriggerHandler class.
	*Methods from Application Helper will be called after Insert.
    *********************************************************************************/
    
    public override void afterInsert() {
        TAP_SuggestedProgramHelper.calculateSuggestedPrograms(new List<Id>(newApplicationsMap.keySet()));
      
    }
    
   /*********************************************************************************
    *Context Overrides.Overrides the afterUpdate method of TriggerHandler class.
	*Methods from Application Helper will be called after Update.
    *********************************************************************************/    
    
    public override void afterUpdate() {
        TAP_SuggestedProgramHelper.calculateSuggestedPrograms(new List<Id>(newApplicationsMap.keySet()));
        TAP_Payment_Helper.updatePaymentStatus(newApplications,oldApplicationsMap);
        deleteSuggestedCarePrograms();
    }
    
 
    
    
    private void deleteSuggestedCarePrograms() {
        List<Application__c> approvedApplications = new List<Application__c>();
        for(Application__c application : newApplications) {
            if(application.Application_Status__c != oldApplicationsMap.get(application.Id).Application_Status__c) {
                if(application.Application_Status__c == TAP_Constants.APPLICATION_STATUS_APPROVED 
                   && oldApplicationsMap.get(application.Id).Application_Status__c != TAP_Constants.APPLICATION_STATUS_APPROVED) {
                    approvedApplications.add(application);
                }
            }
        }
        
        if (approvedApplications.size() > 0) {
            TAP_SuggestedProgramHelper.deleteSuggestedCarePrograms(approvedApplications);  
        }
    }
    
    private void calculateIncomeBasedAttributes(){
        for(Application__c application : newApplications){
            if(oldApplicationsMap.size() > 0) {
                Application__c oldApplication = oldApplicationsMap.get(application.Id);
                if (application.Total_annual_Household_Income__c != oldApplication.Total_annual_Household_Income__c
                    || application.No_of_People_in_the_Household__c != oldApplication.No_of_People_in_the_Household__c 
                    || application.Care_Program__c != oldApplication.Care_Program__c) {
                        application.Poverty_Level__c = TAP_CareProgram_Helper.calculatePovertyLevelForApplication(application);
                        TAP_Application_Helper.updateIncomeGuidelinesCheck(newApplications);
                    }
            } else {
                application.Poverty_Level__c = TAP_CareProgram_Helper.calculatePovertyLevelForApplication(application);
                TAP_Application_Helper.updateIncomeGuidelinesCheck(newApplications);
            }
        }
    }
    
    private void updateApplicationStatusDuration() {
        for(Application__c application : newApplications){
            if(oldApplicationsMap != null && oldApplicationsMap.get(application.Id) != null) {
                TAP_Application_Helper.calculateStatusDuration(application,oldApplicationsMap.get(application.Id).Application_Status__c);
            } else {
                TAP_Application_Helper.setStatusChangeDate(application);
            }
        }
    }
    
}