unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track Health Insurance Information for a Patient</description>
    <label>Application</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Email__c</fullName>
    <description>Application Email ID</description>
    <label>Applicant Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Application_Source__c.field-meta.xml
<CustomField>
    <fullName>Application_Source__c</fullName>
    <description>The Source which the Applicant/Patient  was Submitted their Application.</description>
    <label>Application Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>The Status from the Application Submitted/New to till Approved or Rejected.</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Need More Information</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Payment Error</fullName>
                <isActive>false</isActive>
                <label>Payment Error</label>
            </value>
            <value>
                <fullName>Payment Processing</fullName>
                <isActive>false</isActive>
                <label>Payment Processing</label>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup with Account, to Populate Patient or Applicant Name.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Patient_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Patient_Email_Address__c</fullName>
    <formula>Patient__r.PersonContact.Email</formula>
    <label>Patient Email Address</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Patient_State__c.field-meta.xml
<CustomField>
    <fullName>Patient_State__c</fullName>
    <formula>Patient__r.PersonContact.MailingState</formula>
    <label>Patient State</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Status_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Change_Date__c</fullName>
    <label>Status Change Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/globalValueSets/Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Fax</fullName>
        <label>Fax</label>
    </customValue>
    <customValue>
        <fullName>Direct Email</fullName>
        <label>Email</label>
    </customValue>
    <customValue>
        <fullName>Postal Mail</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Portal</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Phone</fullName>
        <label>Phone</label>
    </customValue>
    <description>How they heard about the program</description>
    <masterLabel>Source</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ApplicationEnrollmentReqSelector.cls
/**
 * Created by vupneja on 2/17/2021.
 */

public with sharing class ApplicationEnrollmentReqSelector {

    public List<Application__c> selectApplicationEnrollmentReq( Id accId ){
        if( String.isNotBlank( accId ) ){
             return [select Patient__c,
                        Patient__r.Name,
                        Patient_Email_Address__c,
                        Application_Status__c,
                        Applicant_Email__c,
                        Patient_State__c ,
                        Name, Id,
                        Abnormal_Screening_Result__c,
                        In_Active_Treatment__c,
                        Application_Source__c,
                        Status_Change_Date__c
                        from Application__c
                        WHERE Patient__c =  :accId
                        ];
        }
        return null;
    }
}