unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track Health Insurance Information for a Patient</description>
    <label>Application</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The date on which Application was submitted by the Patient / Relative.</description>
    <inlineHelpText>The date on which Application was submitted by the Patient / Relative.</inlineHelpText>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>The Status from the Application Submitted/New to till Approved or Rejected.</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Need More Information</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Payment Error</fullName>
                <isActive>false</isActive>
                <label>Payment Error</label>
            </value>
            <value>
                <fullName>Payment Processing</fullName>
                <isActive>false</isActive>
                <label>Payment Processing</label>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Care_Program__c.field-meta.xml
<CustomField>
    <fullName>Care_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Care Program, Populate Name of the Care Program for the Application.</description>
    <label>Care Program</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CareProgram.Care_Program_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.Application_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>CareProgram.Status</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Applications (Care Program)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup with Account, to Populate Patient or Applicant Name.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Using Trigger, Update Payment Date from Payment obj.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <description>Using Trigger, Update Payment Status from Payment obj.</description>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payment Processing</fullName>
            </value>
            <value>
                <fullName>Payment Error</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CareProgram/fields/Care_Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Program_Type__c</fullName>
    <label>Care Program Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Treatment_Application_Program</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CareProgram/fields/Remaining_Amount__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Amount__c</fullName>
    <description>Remaining Amount from Total Received amount(Donation) , Total Awarded Amount(Payments) for this Care Program.</description>
    <formula>Total_Donation_Amount_del__c -  Total_Payment_Amount_del__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/CareProgram/fields/Remaining_monthly_Balance__c.field-meta.xml
<CustomField>
    <fullName>Remaining_monthly_Balance__c</fullName>
    <description>Remaining Monthly Balance from Monthly Payout Cap, Current Monthly Payout Amount.</description>
    <formula>Monthly_Payout_Cap__c - Current_Monthly_Payout__c</formula>
    <label>Remaining Monthly Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <description>The primary record type for individuals in the Komen Health database.</description>
    <label>Person Account</label>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
</RecordType>

unpackaged/main/default/objects/Suggested_Care_Program__c/Suggested_Care_Program__c.object-meta.xml
<CustomObject>
    <label>Suggested Care Program</label>
    <nameField>
        <label>Suggested Programs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suggested Care Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Suggested_Care_Program__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>Suggested_Program</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Suggested_Care_Program__c/fields/Care_Program__c.field-meta.xml
<CustomField>
    <fullName>Care_Program__c</fullName>
    <label>Care Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Suggested Care Programs</relationshipLabel>
    <relationshipName>Suggested_Program</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/globalValueSets/Treatment_Application_Program.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Treatment Assistance Program</fullName>
        <default>true</default>
        <label>Treatment Assistance Program</label>
    </customValue>
    <masterLabel>Treatment Application Program</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TAP_Application_Ctlr.cls
/****************************************************************************************************************************************************************
* @author IVL Dev
* @date 21-May-2020
* @description Controller for Lightning components on Application Object
****************************************************************************************************************************************************************/

public with sharing class TAP_Application_Ctlr {
    
    /*******************************************************************************************************
    * @description checks if user have edit access for Applications
    * @return Map with key String and value as Boolean it return true if user have Edit access
    ********************************************************************************************************/
    @auraEnabled
    public static Map<String,Boolean> checkAccessOnApplication() {
        return new Map<String,Boolean>{'hasEditAccess' => Schema.sObjectType.Application__c.IsUpdateable()};
    }
    
    /*******************************************************************************************************
    * @description checks if user have edit access for Applications		
    * @param applicationIds Id of Application Id
    * @return Map with key String and value as Boolean it return true if user have Edit access
	********************************************************************************************************/
    
    @auraEnabled
    public static Map<String,Boolean> checkAccessesOnApplication(Id recordId) {
        Boolean isEditable = false;
        Boolean isAdmin = false;
        for(PermissionSetAssignment psa: [SELECT PermissionSet.PermissionsModifyAllData FROM PermissionSetAssignment WHERE AssigneeId = :UserInfo.getUserId()]) {
            isAdmin |= psa.PermissionSet.PermissionsModifyAllData;
        }
        if(isAdmin) {
            isEditable = true;
        } else if(Schema.sObjectType.Application__c.IsUpdateable()) {
            isEditable = true;
            Application__c application = [Select Id,Application_Status__c from Application__c where Id =:recordId LIMIT 1];
            if(application.Application_Status__c == TAP_Constants.APPLICATION_STATUS_APPROVED) {
                isEditable = false;
            }
        }
        return new Map<String,Boolean>{'hasEditAccess' => isEditable,'isAdmin' => isAdmin};
    }
    
    /***************************************************************************************************************************
    * @description checks list of Suggested Care Programs Care Programs and Existing Programs for Application 		
    * @param applicationIds Id of Application Id
    * @return Map with key String and value as List of list of Suggested Care Programs Care Programs and Existing Programs 
	*****************************************************************************************************************************/
    
    @auraEnabled
    public static Map<String,List<CareProgram>> loadPrograms(Id recordId) {

        Application__c application = [SELECT Id, Care_Program__c, (SELECT Care_Program__c FROM Suggested_Program__r)  
                                    FROM Application__c WHERE Id = :recordId LIMIT 1];
        String activeStatus = TAP_Constants.CARE_PROGRAM_STATUS_ACTIVE;
        Id careProgramId = application.Care_Program__c;
        String queryString = 'SELECT Id,name,Care_Program_Type__c,Status,Remaining_Amount__c,Remaining_monthly_Balance__c '+
                                'FROM CareProgram Where Status = :activeStatus';
        if(careProgramId != null) {
            queryString += ' OR Id = :careProgramId';
        }
        Map<Id,CareProgram> allCareProgramsMap = new Map<Id,CareProgram>((List<CareProgram>)Database.query(queryString));
        List<CareProgram> existingProgramsOnApplication = null;
        if(careProgramId != null) {
            existingProgramsOnApplication = new List<CareProgram> {allCareProgramsMap.get(application.Care_Program__c)};
        }
        List<CareProgram> suggestedCarePrograms = new List<CareProgram>();
        if(application.Suggested_Program__r != null) {
            for(Suggested_Care_Program__c suggestedCareProgram : application.Suggested_Program__r) {
                if(allCareProgramsMap.get(suggestedCareProgram.Care_Program__c) != null) {
                    suggestedCarePrograms.add(allCareProgramsMap.get(suggestedCareProgram.Care_Program__c));
                }
            }
        }
               
        return new Map<String,List<CareProgram>>{'suggested' => suggestedCarePrograms,'all' => allCareProgramsMap.values(),
                                                 'existing' => existingProgramsOnApplication};
        
    }
    
    /*******************************************************************************************************
    * @description checks  Care Programs is in Suggested Care Programs for Application 		
    * @param  recordId of Application Id and careProgramId of CareProgram Id
    * @return Boolean, YES- if Care Program in Suggested Care Program for Application
	********************************************************************************************************/
    
    @auraEnabled
    public static Boolean isCareProgramSuggested(Id recordId, Id careProgramId) {
        return TAP_SuggestedProgramHelper.isSelectedCareProgramSuggested(recordId,careProgramId);
    }
    
    /*******************************************************************************************************
     * @description checks other Applications related to Patient(PersonAccount) 		
     * @param  recordId of Application Id 
     * @return List of other Applications for that Patient(PersonAccount)
	********************************************************************************************************/
    
    @auraEnabled
    public Static List<Application__c> relatedApplicationlist(String recordId){
        Application__c application = [Select Patient__c from Application__c where Id =:recordId LIMIT 1];
        return [Select Id,Name,Application_Status__c,Application_Date__c,Payment_Status__c,LastModifiedDate,Payment_Date__c 
                from Application__c Where Id != :recordId 
                AND Patient__c = :application.Patient__c ORDER BY LastModifiedDate DESC limit 5];
    }

    /*******************************************************************************************************
    * @description checks status of application	
    * @param  recordId of Application Id 
    * @return String which is status of Application
    ********************************************************************************************************/
    
    @auraEnabled    
    public static String initialValue( String recordId){
        String result;
        Application__c app = [Select Id,Application_Status__c from Application__c where Id =:recordId];
        if(app.Application_Status__c!= null){
            result= app.Application_Status__c;
        }
        return result;
    }
    
    /*******************************************************************************************************
    * @description checks if status of Application is rejected 	then populate the reason in Rich text Area
    * @param recordId of Application Id 
    * @return String which is rejection reason of Application
    ********************************************************************************************************/
    
    @AuraEnabled
    public static String calculateRejectionComment(Id recordId) {
        String rejectionComment = '<html><body><ul>';
        for(String comment : TAP_Application_Helper.getIncompleteReviewChecks(recordId)) {
            rejectionComment += '<li>'+comment+'</li>';
        }
        rejectionComment += '</ul></body></html>';
        return rejectionComment;
    }
}