unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track Health Insurance Information for a Patient</description>
    <label>Application</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/TAP_Inbox__c.field-meta.xml
<CustomField>
    <fullName>TAP_Inbox__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Tap Inbox, Populate Tap Inbox Id.</description>
    <label>TAP Inbox</label>
    <referenceTo>TAP_Inbox__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TAP_Inbox__c/TAP_Inbox__c.object-meta.xml
<CustomObject>
    <label>TAP Inbox</label>
    <nameField>
        <displayFormat>TAP Inbox-{0000000}</displayFormat>
        <label>TAP Inbox Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TAP Inbox</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TAP_Inbox__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>Komen_Fax_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TAP_Inbox__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Discard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TAP_TAPInboxTrigger_Handler.cls
/***************************************************************************************************************************************************************
* @author IVL Dev
* @date 21-July-2020
* @description 
***************************************************************************************************************************************************************/
public class TAP_TAPInboxTrigger_Handler extends TriggerHandler {

    private List<TAP_Inbox__c> newInboxes;
    private Map<Id,TAP_Inbox__c> oldInboxesMap;
    
    public TAP_TAPInboxTrigger_Handler() {
        newInboxes = Trigger.new;
        system.debug('newInboxes :: ' + newInboxes);
        system.debug('Trigger.oldMap :: ' + Trigger.oldMap);
        if(Trigger.oldMap == null) {
            oldInboxesMap = new Map<Id, TAP_Inbox__c>();
            system.debug('oldInboxesMapOLDNULL :: ' + oldInboxesMap);
        } else {
            oldInboxesMap = (Map<Id, TAP_Inbox__c>) Trigger.oldMap;
            system.debug('oldInboxesMapOLDNOTNULL :: ' + oldInboxesMap);
        }
      
    }
    
    /***********************************************************************************************
    *Context Overrides.Overrides the beforeUpdate method of TriggerHandler class
	*Method will be called beforeUpdate
    ************************************************************************************************/
    
    public override void beforeUpdate() {
        updateStatus();
    }
    
    /***********************************************************************************************
    *Context Overrides.Overrides the afterUpdate method of TriggerHandler class
	*Method will be called afterUpdate
    ************************************************************************************************/
    
    public override void afterUpdate() {
        copyContentToApplication();
    }
    
    private void updateStatus() {
        for(TAP_Inbox__c inbox : newInboxes) {
            if(inbox.Application__c != null && inbox.Application__c != oldInboxesMap.get(inbox.Id).Application__c 
               && inbox.Status__c == TAP_Constants.TAP_INBOX_STATUS_PENDING) {
                inbox.Status__c = TAP_Constants.TAP_INBOX_STATUS_PROCESSED;
            }
        }
    }
    
    private void copyContentToApplication() {
        for(TAP_Inbox__c inbox : newInboxes) {
            if(inbox.Application__c != null && inbox.Application__c != oldInboxesMap.get(inbox.Id).Application__c) {
                TAP_CreateEmailActivity.copyEmailsfromInbox(inbox);
            }
        }
    }
}