unpackaged/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Referral_Record__c/Referral_Record__c.object-meta.xml
<CustomObject>
    <label>Referral Record</label>
    <nameField>
        <displayFormat>RR-{00000}</displayFormat>
        <label>Referral Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Referral_Record__c/fields/Knowledge_Article_Referred__c.field-meta.xml
<CustomField>
    <fullName>Knowledge_Article_Referred__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Knowledge Article Referred</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Referral Records</relationshipLabel>
    <relationshipName>Referral_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/KHC_SyncReferralRecordsBatch.cls
/**
@name       KHC_SyncReferralRecordsBatch
@date       6 May 2021
@description Batch class to update referral record when linked article is an old version
@author     NChandwani, Traction on Demand 
 */
public class KHC_SyncReferralRecordsBatch implements Database.Batchable<sObject> {

    public Set<Id> knowledgeIds = new Set<Id>();

    public Database.QueryLocator start( Database.BatchableContext bc ){
        String query = ' SELECT Id, Knowledge_Article_Referred__c, Knowledge_Article_Referred__r.KnowledgeArticleId ';
        query += 'FROM Referral_Record__c ';
        query += 'WHERE Knowledge_Article_Referred__r.IsLatestVersion = FALSE ';

        if( knowledgeIds != null && !knowledgeIds.isEmpty() ){
            query+= 'AND Knowledge_Article_Referred__c IN: knowledgeIds ';
        }
        return Database.getQueryLocator( query );
    }

    public void execute( Database.BatchableContext bc, List<Referral_Record__c> refRecords ){
        Map<Id, List<Referral_Record__c>> knowledgeWithReferrals = new Map<Id, List<Referral_Record__c>>();
        for( Referral_Record__c referralRecord : refRecords){
            if( !knowledgeWithReferrals.containsKey( referralRecord.Knowledge_Article_Referred__r.KnowledgeArticleId ) ){
                knowledgeWithReferrals.put( referralRecord.Knowledge_Article_Referred__r.KnowledgeArticleId, new List<Referral_Record__c>() );
            }
            knowledgeWithReferrals.get( referralRecord.Knowledge_Article_Referred__r.KnowledgeArticleId ).add( referralRecord );
        }
        if( !knowledgeWithReferrals.isEmpty() ){
            List<Referral_Record__c> syncReferrals = new List<Referral_Record__c>();
            for( Knowledge__kav latestKnowledge : [SELECT Id, KnowledgeArticleId FROM Knowledge__kav WHERE IsLatestVersion = TRUE AND KnowledgeArticleId IN: knowledgeWithReferrals.keySet() AND PublishStatus = 'Online'] ){
                if( knowledgeWithReferrals.containsKey( latestKnowledge.KnowledgeArticleId ) ){
                    for( Referral_Record__c referralRecord : knowledgeWithReferrals.get( latestKnowledge.KnowledgeArticleId )){
                        referralRecord.Knowledge_Article_Referred__c = latestKnowledge.Id;
                        syncReferrals.add( referralRecord );
                    }
                    if( !syncReferrals.isEmpty() ){
                        UPDATE syncReferrals;
                    }
                }
            }
        }
    }

    public void finish( Database.BatchableContext bc ){
        
    }
}