unpackaged/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Knowledge__kav/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Knowledge</relationshipLabel>
    <relationshipName>Knowledge</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/fields/Account_Billing_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Account_Billing_Address_City__c</fullName>
    <formula>Account__r.BillingCity</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Billing Address City</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/fields/Account_Billing_Address_Country__c.field-meta.xml
<CustomField>
    <fullName>Account_Billing_Address_Country__c</fullName>
    <formula>Account__r.BillingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Billing Address Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/fields/Account_Billing_Address_State__c.field-meta.xml
<CustomField>
    <fullName>Account_Billing_Address_State__c</fullName>
    <formula>Account__r.BillingState</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Billing Address State</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/fields/Account_Billing_Address_Street__c.field-meta.xml
<CustomField>
    <fullName>Account_Billing_Address_Street__c</fullName>
    <formula>Account__r.BillingStreet</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Billing Address Street</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/fields/Account_Billing_Address_Zip__c.field-meta.xml
<CustomField>
    <fullName>Account_Billing_Address_Zip__c</fullName>
    <formula>Account__r.BillingPostalCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Billing Address Zip</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/fields/Komen_Site_URL__c.field-meta.xml
<CustomField>
    <fullName>Komen_Site_URL__c</fullName>
    <inlineHelpText>Enter the URL of the page on the Komen Public web site.</inlineHelpText>
    <label>Site URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <formula>Account__r.Phone</formula>
    <label>Phone</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <label>Resource Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Article</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/recordTypes/Knowledge.recordType-meta.xml
<RecordType>
    <fullName>Knowledge</fullName>
    <active>true</active>
    <label>Knowledge</label>
</RecordType>

unpackaged/main/default/objects/Referral_Record__c/Referral_Record__c.object-meta.xml
<CustomObject>
    <label>Referral Record</label>
    <nameField>
        <displayFormat>RR-{00000}</displayFormat>
        <label>Referral Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Referral_Record__c/fields/Favourite__c.field-meta.xml
<CustomField>
    <fullName>Favourite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Favorite</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Referral_Record__c/fields/Featured__c.field-meta.xml
<CustomField>
    <fullName>Featured__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Featured</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Referral_Record__c/fields/Knowledge_Article_Referred__c.field-meta.xml
<CustomField>
    <fullName>Knowledge_Article_Referred__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Knowledge Article Referred</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Referral Records</relationshipLabel>
    <relationshipName>Referral_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Referral_Record__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referral Records</relationshipLabel>
    <relationshipName>Referral_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Referral_Record__c/fields/Referred__c.field-meta.xml
<CustomField>
    <fullName>Referred__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Referred</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Referral_Record__c/fields/Referred_By__c.field-meta.xml
<CustomField>
    <fullName>Referred_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Referral_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Contact.AccountId</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/KHC_ResourceSearchController.cls
/**
 * Created by vupneja on 3/16/2021.
 */

public with sharing class KHC_ResourceSearchController {

    private static Id knowledgeRecordTypeId = Schema.SObjectType.Knowledge__kav.getRecordTypeInfosByName().get('Knowledge').getRecordTypeId();

    //Nchandwani, 19 March 2021: Filter Knowledge records
    @AuraEnabled
    public static List<Knowledge__kav> getResources( ResourceFilterWrapper filter ){

        User currUser;
        Id currentLoggedAccount;
        Boolean isGuestUser = MyKomenHealthUtility.isGuestUser();

        if ( !isGuestUser ) {
            currUser = MyKomenHealthUtility.getLoggedInUserDetails();
            currentLoggedAccount = currUser.AccountId;
        }

        Set<String> topics = new Set<String>();
        Set<String> types = new Set<String>();
        Set<String> locations = new Set<String>();
        Set<Id> knowledgeIds = new Set<Id>();
        Set<Id> favKnowledgeIds = new Set<Id>();
        Set<Id> referredKnowledgeIds = new Set<Id>();

        String query = 'SELECT Id, Title, Summary, Resource_Type__c, Community_Topics__c, Phone__c, Email__c, Featured__c';
        query += ', Account__c';
        query += ', Account_Name__c';
        query += ', Account_Billing_Address_Street__c';
        query += ', Account_Billing_Address_City__c';
        query += ', Account_Billing_Address_State__c';
        query += ', Account_Billing_Address_Country__c';
        query += ', Account_Billing_Address_Zip__c';
        query += ', Komen_Site_URL__c';
        query += ', Body__c';
        if ( !isGuestUser ) {
            // Query favorites
            query += ', (SELECT Id, Favourite__c, Referred__c FROM ' +
                        'Referral_Records__r WHERE ' +
                        'Patient__c = :currentLoggedAccount AND ' +
                        '(Favourite__c = TRUE OR ' +
                        'Referred__c = TRUE)) ';
        }
        query += ' FROM Knowledge__kav ';

        String filterClause = '';
        //Create Filter String
        if( filter != null ){
            //Filter by resource Type
            if( filter.type != null && !filter.type.isEmpty() ){
                types = new Set<String>( filter.type );
                filterClause += 'Resource_Type__c IN: types ';
            }

            if(filter.featured == true) {
                filterClause += String.isNotBlank( filterClause ) ? 'AND ' : '';
                filterClause += 'Featured__c = TRUE ';
            }

            //Check if favorite/referred is selected
            if(filter.favourites == true || filter.referred == true ){

                //Query Referral_Record__c and create a set of knowledge which matches the criterias
                for( Referral_Record__c referralRecord : getReferralRecords( currentLoggedAccount ) ){
                    if( filter.favourites == true && referralRecord.Favourite__c ){
                        favKnowledgeIds.add( referralRecord.Knowledge_Article_Referred__c );
                    }

                    if( filter.referred == true && referralRecord.Referred__c ){
                        referredKnowledgeIds.add( referralRecord.Knowledge_Article_Referred__c );
                    }
                }
                //Add and criteria for featured, favorite, referred
                if( filter.favourites == true ){
                    filterClause += String.isNotBlank( filterClause ) ? 'AND ' : '';
                    filterClause += 'Id IN: favKnowledgeIds ';
                }

                if( filter.referred == true ){
                    filterClause += String.isNotBlank( filterClause ) ? 'AND ' : '';
                    filterClause += 'Id IN: referredKnowledgeIds ';
                }

                if( !knowledgeIds.isEmpty() ){
                    filterClause += String.isNotBlank( filterClause ) ? 'AND ' : '';
                    filterClause += 'Id IN: knowledgeIds ';
                }
            }

            //Filter by Topics
            if( filter.topics != null && !filter.topics.isEmpty() ){
                String topicsClause = '';
                for(string t : filter.topics) {
                    topicsClause += ',\'' + t + '\'';
                }
                topicsClause = topicsClause.substring(1, topicsClause.length() - 1);
                topicsClause = topicsClause + '\'';

                filterClause += String.isNotBlank( filterClause ) ? 'AND ' : '';
                filterClause += 'Community_Topics__c INCLUDES (' + topicsClause + ') ';
            }

            //Filter by Location
            if( filter.location != null && !filter.location.isEmpty() ){
                locations = new Set<String>( filter.location );
                filterClause += String.isNotBlank( filterClause ) ? 'AND ' : '';
                filterClause += 'Account_Billing_Address_State__c IN: locations ';
            }

            //by specific Id
            if( filter.articleId != null ){
                knowledgeIds.add( filter.articleId );
                filterClause += String.isNotBlank( filterClause ) ? 'AND ' : '';
                filterClause += 'Id IN: knowledgeIds ';
            }
        }

        if( String.isNotBlank( filterClause ) ){
            query += ' WHERE ' + filterClause;
            query += ' AND ArchivedById = NULL';
        } else {
            query += ' WHERE ArchivedById = NULL';
        }
        query += ' AND RecordTypeId != NULL';
        query += ' AND RecordTypeId = :knowledgeRecordTypeId';
        query += ' AND IsLatestVersion = TRUE';
        query += ' AND PublishStatus = \'Online\'';

        query += applySort( filter );
        return Database.query( query );
    }

    //Sort by specified field
    private static String applySort( ResourceFilterWrapper filter ){
        if ( filter == null ) {
            return '';
        }
        if( String.isNotBlank( filter.sortByField ) &&  String.isNotBlank( filter.sortOrder ) ){
            return ' ORDER BY ' + filter.sortByField + ' ' + filter.sortOrder;
        }
        return '';
    } 

    //Get Referral records by logged in user
    private static List<Referral_Record__c> getReferralRecords( Id currentLoggedAccount ){
        return [SELECT Favourite__c, Featured__c,
                Referred__c, Knowledge_Article_Referred__c
                FROM Referral_Record__c
                WHERE Patient__c =: currentLoggedAccount];
    }

    //Wrapper class for Knowledge Filter
    public class ResourceFilterWrapper{
        @AuraEnabled
        public Id articleId {get;set;}

        @AuraEnabled
        public List<String> type {get;set;}

        @AuraEnabled
        public boolean featured {get;set;}

        @AuraEnabled
        public List<String> location {get;set;}

        @AuraEnabled
        public List<String> topics {get;set;}

        @AuraEnabled
        public boolean favourites{get;set;}

        @AuraEnabled
        public boolean referred{get;set;}

        @AuraEnabled
        public String sortByField{get;set;}

        @AuraEnabled
        public String sortOrder{get;set;}
    }
}