unpackaged/main/default/objects/Family_Medical_History_Condition__c/Family_Medical_History_Condition__c.object-meta.xml
<CustomObject>
    <label>Family Medical History Condition</label>
    <nameField>
        <displayFormat>FMHC-{0000}</displayFormat>
        <label>Family Medical History Condition Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Medical History Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Family_Medical_History_Condition__c/fields/Age_at_diagnosis__c.field-meta.xml
<CustomField>
    <fullName>Age_at_diagnosis__c</fullName>
    <label>Age at diagnosis</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Age_Range</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Family_Medical_History_Condition__c/fields/Condition_Category__c.field-meta.xml
<CustomField>
    <fullName>Condition_Category__c</fullName>
    <label>Condition Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Condition_Category</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Family_Medical_History_Condition__c/fields/Condition_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Condition_Sub_Category__c</fullName>
    <label>Condition Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Condition_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Condition_Sub_Category</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Family_Medical_History_Condition__c/fields/Family_Medical_History__c.field-meta.xml
<CustomField>
    <fullName>Family_Medical_History__c</fullName>
    <label>Family Medical History</label>
    <referenceTo>Patient_Contact__c</referenceTo>
    <relationshipLabel>Family Medical History Conditions</relationshipLabel>
    <relationshipName>Family_Medical_History_Conditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/Patient_Contact__c.object-meta.xml
<CustomObject>
    <label>Patient Contact</label>
    <nameField>
        <displayFormat>FMH-{0000}</displayFormat>
        <label>Patient Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Patient_Contact__c/fields/Description_Notes__c.field-meta.xml
<CustomField>
    <fullName>Description_Notes__c</fullName>
    <label>Description/Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Emergency_Contact__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency Contact</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Family_Member_Name__c.field-meta.xml
<CustomField>
    <fullName>Family_Member_Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Is_this_person_living__c.field-meta.xml
<CustomField>
    <fullName>Is_this_person_living__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is this person living?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <description>Field to hold Mailing details for patient contact</description>
    <label>Mailing City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country__c</fullName>
    <description>Field to hold Mailing details for patient contact</description>
    <label>Mailing Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Mailing_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State_Province__c</fullName>
    <description>Field to hold Mailing details for patient contact</description>
    <label>Mailing State/Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Mailing_Street__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Street__c</fullName>
    <description>Field to hold Mailing details for patient contact</description>
    <label>Mailing Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Mailing_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Zip_Postal_Code__c</fullName>
    <description>Field to hold Mailing details for patient contact</description>
    <label>Mailing Zip/Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Name_with_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Name_with_Relationship__c</fullName>
    <description>Display the family member&apos;s name followed the the relationship in brackets, if a relationship value has been selected</description>
    <formula>Family_Member_Name__c +
IF(ISBLANK(TEXT(Relationship__c)),
  &quot;&quot;,
  &quot; (&quot; + TEXT(Relationship__c) + &quot;)&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name with Relationship</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patient Contacts</relationshipLabel>
    <relationshipName>Patient_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <label>Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Relationship</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Age_Range.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prebirth</fullName>
    </customValue>
    <customValue>
        <fullName>Newborn</fullName>
    </customValue>
    <customValue>
        <fullName>In Infancy</fullName>
    </customValue>
    <customValue>
        <fullName>In Childhood</fullName>
    </customValue>
    <customValue>
        <fullName>In Adolescence</fullName>
    </customValue>
    <customValue>
        <fullName>20-29 Years</fullName>
    </customValue>
    <customValue>
        <fullName>30-39 Years</fullName>
    </customValue>
    <customValue>
        <fullName>40-49 Years</fullName>
    </customValue>
    <customValue>
        <fullName>50-59 Years</fullName>
    </customValue>
    <customValue>
        <fullName>60 Years or older</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <masterLabel>Age Range</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Condition_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Clotting Disorder</fullName>
    </customValue>
    <customValue>
        <fullName>Dementia/Alzheimers</fullName>
    </customValue>
    <customValue>
        <fullName>Diabetes</fullName>
    </customValue>
    <customValue>
        <fullName>Gastrointestinal Disorder</fullName>
    </customValue>
    <customValue>
        <fullName>Heart Disease</fullName>
    </customValue>
    <customValue>
        <fullName>High Cholesterol</fullName>
    </customValue>
    <customValue>
        <fullName>Hypertension</fullName>
    </customValue>
    <customValue>
        <fullName>Kidney Disease</fullName>
    </customValue>
    <customValue>
        <fullName>Lung Disease</fullName>
    </customValue>
    <customValue>
        <fullName>Osteoporosis</fullName>
    </customValue>
    <customValue>
        <fullName>Psychological Disorder</fullName>
    </customValue>
    <customValue>
        <fullName>Septicemia</fullName>
    </customValue>
    <customValue>
        <fullName>Stroke/Brain Attack</fullName>
    </customValue>
    <customValue>
        <fullName>Sudden Infant Death Syndrome</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown Disease</fullName>
    </customValue>
    <masterLabel>Condition Category</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Condition_Sub_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bone Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Brain Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Breast Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Colon Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Colorectal Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Esophageal Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Familial adnenomatous polyposis (FAP)</fullName>
    </customValue>
    <customValue>
        <fullName>Gastric Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Lynch Syndrome/Hereditary non-polyposis colorectal cancer (HNPCC)</fullName>
    </customValue>
    <customValue>
        <fullName>Kidney Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Leukemia</fullName>
    </customValue>
    <customValue>
        <fullName>Liver Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Lung Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Muscle Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Other Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Ovarian Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Pancreatic Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Prostate Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Rectal Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Skin Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Thyroid Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Uterine Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Clotting Disorder</fullName>
    </customValue>
    <customValue>
        <fullName>Deep Vein Thrombosis (DVT)</fullName>
    </customValue>
    <customValue>
        <fullName>Pulmonary Embolism</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown Clotting Disorder</fullName>
    </customValue>
    <customValue>
        <fullName>Dementia/Alzheimer&apos;s</fullName>
    </customValue>
    <customValue>
        <fullName>Diabetes</fullName>
    </customValue>
    <customValue>
        <fullName>Gestational Diabetes</fullName>
    </customValue>
    <masterLabel>Condition Sub Category</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Relationship.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Mother</fullName>
    </customValue>
    <customValue>
        <fullName>Father</fullName>
    </customValue>
    <customValue>
        <fullName>Full Sibling</fullName>
    </customValue>
    <customValue>
        <fullName>Half Sibling</fullName>
    </customValue>
    <customValue>
        <fullName>Grandparent</fullName>
    </customValue>
    <customValue>
        <fullName>Uncle/Aunt</fullName>
    </customValue>
    <customValue>
        <fullName>First Cousin</fullName>
    </customValue>
    <customValue>
        <fullName>Grandchild</fullName>
    </customValue>
    <customValue>
        <fullName>Niece/Nephew</fullName>
    </customValue>
    <customValue>
        <fullName>Spouse/Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Co-Worker</fullName>
    </customValue>
    <customValue>
        <fullName>Employer</fullName>
    </customValue>
    <customValue>
        <fullName>Therapist</fullName>
    </customValue>
    <customValue>
        <fullName>Child</fullName>
        <isActive>false</isActive>
        <label>Child</label>
    </customValue>
    <customValue>
        <fullName>Maternal Uncle/Aunt</fullName>
        <isActive>false</isActive>
        <label>Maternal Uncle/Aunt</label>
    </customValue>
    <customValue>
        <fullName>Maternal Grandparent</fullName>
        <isActive>false</isActive>
        <label>Maternal Grandparent</label>
    </customValue>
    <customValue>
        <fullName>Paternal Uncle/Aunt</fullName>
        <isActive>false</isActive>
        <label>Paternal Uncle/Aunt</label>
    </customValue>
    <customValue>
        <fullName>Paternal Grandparent</fullName>
        <isActive>false</isActive>
        <label>Paternal Grandparent</label>
    </customValue>
    <customValue>
        <fullName>Paternal Half Sibling</fullName>
        <isActive>false</isActive>
        <label>Paternal Half Sibling</label>
    </customValue>
    <customValue>
        <fullName>Maternal Half Sibling</fullName>
        <isActive>false</isActive>
        <label>Maternal Half Sibling</label>
    </customValue>
    <masterLabel>Relationship</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/KHC_FamilyMedicalHealthSelector.cls
/**
 * Selector for the Family Medical History object
 * Object renamed to Patient Contact
 * @author Grant Adamson, Traction on Demand
 * @date 2020-09-17
 */
public inherited sharing class KHC_FamilyMedicalHealthSelector {

    public static final Id supporterCaregiverRecTypeId = Schema.SObjectType.Patient_Contact__c.getRecordTypeInfosByName().get('Supporter/Caregiver').getRecordTypeId();
    public static final Id familyMedicalHistoryRecTypeId = Schema.SObjectType.Patient_Contact__c.getRecordTypeInfosByName().get('Family Medical History').getRecordTypeId();

    public List<Patient_Contact__c> selectByPersonAccountIdWithConditions(Id personAccountId) {
        return [
                SELECT Name_with_Relationship__c, Relationship__c, Is_this_person_living__c,
                (
                        SELECT Condition_Category__c, Condition_Sub_Category__c, Age_at_diagnosis__c
                        FROM Family_Medical_History_Conditions__r
                )
                FROM Patient_Contact__c
                WHERE Patient__c = :personAccountId 
                AND RecordTypeId =: familyMedicalHistoryRecTypeId 
                ORDER BY CreatedDate
        ];
    }

    public List<Patient_Contact__c> selectByRelatedPatientAndRelationships( Id personAccountId, Id recordTypeId ) {
        return [
                SELECT Id, Name, Patient__c, Patient__r.Name, Relationship__c,
                Family_Member_Name__c, Email__c, Phone__c, 
                Mobile_Phone__c, Emergency_Contact__c, Mailing_Street__c,
                Mailing_City__c, Mailing_State_Province__c, Mailing_Country__c, 
                Mailing_Zip_Postal_Code__c, Description_Notes__c
                FROM Patient_Contact__c
                WHERE Patient__c =:personAccountId 
                AND RecordTypeId =: recordTypeId
                ORDER BY CreatedDate
        ];
    }
}