unpackaged/main/default/objects/Medication__c/Medication__c.object-meta.xml
<CustomObject>
    <description>Holds information about medications in use by Patients.  Intended to be populated either manually, or via integration with an API.</description>
    <label>Medication</label>
    <nameField>
        <label>Medication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Medication__c/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <defaultValue>false</defaultValue>
    <description>identifies if this medication is a brand name or not</description>
    <label>Brand Name?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Medication__c/fields/Med_Name__c.field-meta.xml
<CustomField>
    <fullName>Med_Name__c</fullName>
    <label>Med Name</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Medication__c/fields/Product_NDC__c.field-meta.xml
<CustomField>
    <fullName>Product_NDC__c</fullName>
    <label>Product NDC</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Medication__c/fields/RXCUI__c.field-meta.xml
<CustomField>
    <fullName>RXCUI__c</fullName>
    <description>The RXCUI identifier for this medication.</description>
    <label>RXCUI</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Medication__c/fields/RXCUI_Possible_Matches__c.field-meta.xml
<CustomField>
    <fullName>RXCUI_Possible_Matches__c</fullName>
    <label>RXCUI Possible Matches</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Medication__c/fields/Side_Effects_Statement__c.field-meta.xml
<CustomField>
    <fullName>Side_Effects_Statement__c</fullName>
    <label>Side Effects Statement</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Medication__c/fields/Update_Medication_Information__c.field-meta.xml
<CustomField>
    <fullName>Update_Medication_Information__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, triggers a process to refresh the Medication information from defined sources.  Triggers an outbound message to external providers.</description>
    <label>Update Medication Information</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/MedicationSelector.cls
/**
 * Selector for Medication records
 * 
 * @author Nitin Chandwani, Traction on Demand
 * @date 2020-09-03
 */
public with sharing class MedicationSelector {
    public List<Medication__c> selectAll(){
        return [
                SELECT Id, Name, RXCUI__c, Product_NDC__c, Brand_Name__c, 
                Side_Effects_Statement__c, RXCUI_Possible_Matches__c, 
                Update_Medication_Information__c , Med_Name__c
                FROM Medication__c
                ORDER BY Name
            ];
    }

    public List<Medication__c> selectByName( String name ){
        return [
                SELECT Id, Name, RXCUI__c, Product_NDC__c, Brand_Name__c, 
                Side_Effects_Statement__c, RXCUI_Possible_Matches__c, 
                Update_Medication_Information__c , Med_Name__c
                FROM Medication__c
                WHERE Med_Name__c =: name
                LIMIT 1 
            ];
    }
}