unpackaged/main/default/objects/Medication__c/Medication__c.object-meta.xml
<CustomObject>
    <description>Holds information about medications in use by Patients.  Intended to be populated either manually, or via integration with an API.</description>
    <label>Medication</label>
    <nameField>
        <label>Medication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Medication__c/fields/Med_Name__c.field-meta.xml
<CustomField>
    <fullName>Med_Name__c</fullName>
    <label>Med Name</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/classes/KHC_MedicationLookupControllerTest.cls
/**
 * Test class for Medication Lookup Controller
 * 
 * @author Nitin Chandwani, Traction on Demand
 * @date 2020-09-10
 */
@isTest
public class KHC_MedicationLookupControllerTest {
    private static final string MEDICATION_ADVIL = 'Advil';
    @isTest
    public static void testSearchMedications(){
        Test.setMock(HttpCalloutMock.class, new KHC_HttpCalloutMock());
        List<KHC_MedicationLookupController.DrugWrap> resp = KHC_MedicationLookupController.getAllMedications( MEDICATION_ADVIL );
        System.assertNotEquals( null, resp, 'Return value should have response.');
    }
    @isTest
    public static void testUpsertMedications(){
        Test.setMock(HttpCalloutMock.class, new KHC_HttpCalloutMock());
        List<KHC_MedicationLookupController.DrugWrap> resp = KHC_MedicationLookupController.getAllMedications(MEDICATION_ADVIL);
        System.assertNotEquals( null, resp, 'Return value should have response.');
        Medication__c medication = new Medication__c( Med_Name__c = MEDICATION_ADVIL );
        Id medicationId = KHC_MedicationLookupController.upsertMedication( medication );
        System.assertEquals( medicationId, [SELECT Id FROM Medication__c WHERE Med_Name__c =: MEDICATION_ADVIL LIMIT 1].Id, 'Medication created should be same.');
    }
    @isTest
    public static void testUpsertExistingMedications(){
        Test.setMock(HttpCalloutMock.class, new KHC_HttpCalloutMock());
        List<KHC_MedicationLookupController.DrugWrap> resp = KHC_MedicationLookupController.getAllMedications(MEDICATION_ADVIL);
        System.assertNotEquals( null, resp, 'Return value should have response.');
        Medication__c medication = new Medication__c( Med_Name__c = MEDICATION_ADVIL );
        Id medicationId = KHC_MedicationLookupController.upsertMedication( medication );
        System.assertEquals( medicationId, [SELECT Id FROM Medication__c WHERE Med_Name__c =: MEDICATION_ADVIL  LIMIT 1].Id, 'Medication created should be same.');
        //Calling method with same medication
        Id medicationId2 = KHC_MedicationLookupController.upsertMedication( medication );
        System.assertEquals( medicationId, medicationId2, 'Medication should not be created again.');
    }
}