unpackaged/main/default/objects/Account/fields/Applicant_Birth_Date__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Birth_Date__c</fullName>
    <description>Using Trigger, Populating Patient Date of Birth to create Matching/Duplicate Rule.</description>
    <label>Applicant Birth Date</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Using Trigger, Update Payment Date from Payment obj.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track Health Insurance Information for a Patient</description>
    <label>Application</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Care_Program__c.field-meta.xml
<CustomField>
    <fullName>Care_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Care Program, Populate Name of the Care Program for the Application.</description>
    <label>Care Program</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CareProgram.Care_Program_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.Application_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>CareProgram.Status</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Applications (Care Program)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup with Account, to Populate Patient or Applicant Name.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Using Trigger, Update Payment Date from Payment obj.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Poverty_Level__c.field-meta.xml
<CustomField>
    <fullName>Poverty_Level__c</fullName>
    <description>This field get Auto Calculated based on Financial Information.</description>
    <label>Poverty Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/CareProgram/fields/Payout_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payout_Amount__c</fullName>
    <description>Payout Amount for this Care Program.</description>
    <label>Payout Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/Eligibility_Detail__c.object-meta.xml
<CustomObject>
    <description>This objects holds data details of Care Program eligibility criteria.</description>
    <label>Eligibility Detail</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Eligibility Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligibility Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/Care_Program__c.field-meta.xml
<CustomField>
    <fullName>Care_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Eligibility Details</relationshipLabel>
    <relationshipName>Eligibility_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/Eligibility_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Criteria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Eligibility Criteria</label>
    <referenceTo>EnrollmentEligibilityCriteria</referenceTo>
    <relationshipLabel>Eligibility Details</relationshipLabel>
    <relationshipName>Eligibility_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/Per_Person_Incremental_Amount__c.field-meta.xml
<CustomField>
    <fullName>Per_Person_Incremental_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Per Person Incremental Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/Single_Person_Income_Limit__c.field-meta.xml
<CustomField>
    <fullName>Single_Person_Income_Limit__c</fullName>
    <label>Single Person Income Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EnrollmentEligibilityCriteria/fields/Criteria_Type__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Type__c</fullName>
    <label>Criteria Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZIP</fullName>
            </value>
            <value>
                <fullName>Income</fullName>
            </value>
            <value>
                <fullName>USA Resident</fullName>
            </value>
            <value>
                <fullName>No Awards</fullName>
            </value>
            <value>
                <fullName>Patient Needs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Suggested_Care_Program__c/Suggested_Care_Program__c.object-meta.xml
<CustomObject>
    <label>Suggested Care Program</label>
    <nameField>
        <label>Suggested Programs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suggested Care Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Suggested_Care_Program__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>Suggested_Program</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Suggested_Care_Program__c/fields/Care_Program__c.field-meta.xml
<CustomField>
    <fullName>Care_Program__c</fullName>
    <label>Care Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Suggested Care Programs</relationshipLabel>
    <relationshipName>Suggested_Program</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/TAP_AccountTrigger_Handler_Test.cls
@isTest
public class TAP_AccountTrigger_Handler_Test {
    @testSetup static void setup() {
        //Create common test accounts
        List<Account> testaccounts = TAP_TestDataFactory.createAccount(2,'Account'); 
        
        // Create common test care Program
        List<CareProgram> testCarePrograms = TAP_TestDataFactory.createCareProgram(2,'careProgram');
        
        // Create common test application
        List<Application__c> testapplications = TAP_TestDataFactory.createApplication(1,testaccounts[0].Id,testCarePrograms[0].Id);
        
        // Create common test EnrollmentEligibilityCriteria
        List<EnrollmentEligibilityCriteria> enrollmentEligibilityCriterias = TAP_TestDataFactory.createEnrollmentEligibilityCriteria(1,'Income','TestIncomeCriteria');
        
        // Create common test CareProgramEligibilityRule
        List<CareProgramEligibilityRule> careProgramRules = TAP_TestDataFactory.careProgramEligibilityRule(1,enrollmentEligibilityCriterias[0].Id,testCarePrograms[0].Id);
        
        // Create common test CareProgramEligibilityRule
        List<Eligibility_Detail__c> eligibilityDetails =TAP_TestDataFactory.createEligibilityDetail('Income',enrollmentEligibilityCriterias[0].Id,'NY','10001'); 
    }

    @isTest static void accountTest(){
        Decimal level = 0.0 ;
        //query to get EnrollmentEligibilityCriteria
        EnrollmentEligibilityCriteria criteria = [SELECT Id,Criteria_Type__c,Status FROM EnrollmentEligibilityCriteria WHERE Criteria_Type__c = 'Income'];
        
        //query to get Eligibility Detalis
        List<Eligibility_Detail__c> eligibilityDetails = [SELECT Id,Per_Person_Incremental_Amount__c,Single_Person_Income_Limit__c,State__c,Is_Active__c FROM Eligibility_Detail__c 
                                                          WHERE Eligibility_Criteria__c=:criteria.Id];
        //query to get Account
        List<Account> accounts = [SELECT Id,Name,Payment_Date__c FROM Account WHERE LastName = 'Account0'];
       
        //query to get Application
        Application__c application = [SELECT ID,Care_Program__c FROM Application__c WHERE Patient__c =:accounts[0].Id];
        
        //query to get CareProgram
        CareProgram careProgram = [SELECT ID,Payout_Amount__c FROM CareProgram WHERE Name = 'careProgram0'];
        
        test.startTest();
        
        //query to get Account
        List<Account> account = [SELECT Id,Applicant_Birth_Date__c,PersonBirthdate,Payment_Date__c FROM Account WHERE Id =:accounts[0].Id];
        
        //check PersonBirthdate is same as Applicant Birth Date
        system.assertEquals(account[0].Applicant_Birth_Date__c,String.valueOf(account[0].PersonBirthdate));
        
        //update Account address
        account[0].PersonMailingStateCode = 'NY';
        accounts[0].PersonMailingPostalCode = '10001';
        update account;

        //query to get Suggested Care Program
        List<Suggested_Care_Program__c> suggestedCareProgram = [SELECT Id,Name,Application__c FROM Suggested_Care_Program__c 
                                                                WHERE Application__c = :application.id];
        
        //check Suggested Care Program size is greater than 0
        system.assert(suggestedCareProgram.size()>0);
        system.assertEquals(suggestedCareProgram[0].Application__c, application.Id);
        
        //query to get application
        List<application__c> applications = [SELECT ID,Care_Program__c,Poverty_Level__c FROM Application__c WHERE Patient__c =:accounts[0].Id];
        //Asserts to check  poverty level odf application
        system.assertEquals(184,Integer.valueOf(applications[0].Poverty_Level__c)); 
        test.stopTest();
    }
}