unpackaged/main/default/objects/Account/fields/Breast_Cancer_Status__c.field-meta.xml
<CustomField>
    <fullName>Breast_Cancer_Status__c</fullName>
    <label>Breast Cancer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Early Indications</fullName>
            </value>
            <value>
                <fullName>Diagnosed</fullName>
            </value>
            <value>
                <fullName>Metastatic</fullName>
            </value>
            <value>
                <fullName>Remission</fullName>
            </value>
            <value>
                <fullName>Survivor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/Family_Medical_History_Condition__c/Family_Medical_History_Condition__c.object-meta.xml
<CustomObject>
    <label>Family Medical History Condition</label>
    <nameField>
        <displayFormat>FMHC-{0000}</displayFormat>
        <label>Family Medical History Condition Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Medical History Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Family_Medical_History_Condition__c/fields/Age_at_diagnosis__c.field-meta.xml
<CustomField>
    <fullName>Age_at_diagnosis__c</fullName>
    <label>Age at diagnosis</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Age_Range</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Family_Medical_History_Condition__c/fields/Condition_Category__c.field-meta.xml
<CustomField>
    <fullName>Condition_Category__c</fullName>
    <label>Condition Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Condition_Category</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Family_Medical_History_Condition__c/fields/Condition_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Condition_Sub_Category__c</fullName>
    <label>Condition Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Condition_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Condition_Sub_Category</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Family_Medical_History_Condition__c/fields/Family_Medical_History__c.field-meta.xml
<CustomField>
    <fullName>Family_Medical_History__c</fullName>
    <label>Family Medical History</label>
    <referenceTo>Patient_Contact__c</referenceTo>
    <relationshipLabel>Family Medical History Conditions</relationshipLabel>
    <relationshipName>Family_Medical_History_Conditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/Patient_Contact__c.object-meta.xml
<CustomObject>
    <label>Patient Contact</label>
    <nameField>
        <displayFormat>FMH-{0000}</displayFormat>
        <label>Patient Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Patient_Contact__c/fields/Adopted__c.field-meta.xml
<CustomField>
    <fullName>Adopted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Adopted?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Are_They_Ashkenazi_Jewish__c.field-meta.xml
<CustomField>
    <fullName>Are_They_Ashkenazi_Jewish__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>For certain conditions, such as ovarian and breast cancer, it is important to know if a person has Ashkenazi Jewish heritage for risk assessment purposes.</inlineHelpText>
    <label>Are They Ashkenazi Jewish?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Birth_Year__c.field-meta.xml
<CustomField>
    <fullName>Birth_Year__c</fullName>
    <description>Used to calculate an estimated age</description>
    <label>Birth Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Cause_of_Death__c.field-meta.xml
<CustomField>
    <fullName>Cause_of_Death__c</fullName>
    <label>Cause of Death</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Estimated_Age_at_Death__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Age_at_Death__c</fullName>
    <label>Estimated Age at Death</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Age_Range</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Ethnicity__c.field-meta.xml
<CustomField>
    <fullName>Ethnicity__c</fullName>
    <label>Ethnicity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Ethnicity</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Family_Member_Name__c.field-meta.xml
<CustomField>
    <fullName>Family_Member_Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Gender Diverse</fullName>
            </value>
            <value>
                <fullName>Prefer Not To Say</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Is_this_person_living__c.field-meta.xml
<CustomField>
    <fullName>Is_this_person_living__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is this person living?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patient Contacts</relationshipLabel>
    <relationshipName>Patient_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Race_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Race_Picklist__c</fullName>
    <description>Race multi-picklist set for patient contacts</description>
    <label>Race</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Race</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Related_through_family_member__c.field-meta.xml
<CustomField>
    <fullName>Related_through_family_member__c</fullName>
    <label>Related through family member</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Relationship</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <label>Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Relationship</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Patient_Contact__c/fields/Was_this_person_born_a_twin_multiple__c.field-meta.xml
<CustomField>
    <fullName>Was_this_person_born_a_twin_multiple__c</fullName>
    <label>Was this person born a twin / multiple?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not a Twin</fullName>
            </value>
            <value>
                <fullName>Yes, Identical Twin</fullName>
            </value>
            <value>
                <fullName>Yes, Not Identical Twin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Age_Range.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prebirth</fullName>
    </customValue>
    <customValue>
        <fullName>Newborn</fullName>
    </customValue>
    <customValue>
        <fullName>In Infancy</fullName>
    </customValue>
    <customValue>
        <fullName>In Childhood</fullName>
    </customValue>
    <customValue>
        <fullName>In Adolescence</fullName>
    </customValue>
    <customValue>
        <fullName>20-29 Years</fullName>
    </customValue>
    <customValue>
        <fullName>30-39 Years</fullName>
    </customValue>
    <customValue>
        <fullName>40-49 Years</fullName>
    </customValue>
    <customValue>
        <fullName>50-59 Years</fullName>
    </customValue>
    <customValue>
        <fullName>60 Years or older</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <masterLabel>Age Range</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Condition_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Clotting Disorder</fullName>
    </customValue>
    <customValue>
        <fullName>Dementia/Alzheimers</fullName>
    </customValue>
    <customValue>
        <fullName>Diabetes</fullName>
    </customValue>
    <customValue>
        <fullName>Gastrointestinal Disorder</fullName>
    </customValue>
    <customValue>
        <fullName>Heart Disease</fullName>
    </customValue>
    <customValue>
        <fullName>High Cholesterol</fullName>
    </customValue>
    <customValue>
        <fullName>Hypertension</fullName>
    </customValue>
    <customValue>
        <fullName>Kidney Disease</fullName>
    </customValue>
    <customValue>
        <fullName>Lung Disease</fullName>
    </customValue>
    <customValue>
        <fullName>Osteoporosis</fullName>
    </customValue>
    <customValue>
        <fullName>Psychological Disorder</fullName>
    </customValue>
    <customValue>
        <fullName>Septicemia</fullName>
    </customValue>
    <customValue>
        <fullName>Stroke/Brain Attack</fullName>
    </customValue>
    <customValue>
        <fullName>Sudden Infant Death Syndrome</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown Disease</fullName>
    </customValue>
    <masterLabel>Condition Category</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Condition_Sub_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bone Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Brain Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Breast Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Colon Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Colorectal Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Esophageal Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Familial adnenomatous polyposis (FAP)</fullName>
    </customValue>
    <customValue>
        <fullName>Gastric Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Lynch Syndrome/Hereditary non-polyposis colorectal cancer (HNPCC)</fullName>
    </customValue>
    <customValue>
        <fullName>Kidney Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Leukemia</fullName>
    </customValue>
    <customValue>
        <fullName>Liver Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Lung Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Muscle Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Other Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Ovarian Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Pancreatic Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Prostate Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Rectal Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Skin Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Thyroid Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Uterine Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Clotting Disorder</fullName>
    </customValue>
    <customValue>
        <fullName>Deep Vein Thrombosis (DVT)</fullName>
    </customValue>
    <customValue>
        <fullName>Pulmonary Embolism</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown Clotting Disorder</fullName>
    </customValue>
    <customValue>
        <fullName>Dementia/Alzheimer&apos;s</fullName>
    </customValue>
    <customValue>
        <fullName>Diabetes</fullName>
    </customValue>
    <customValue>
        <fullName>Gestational Diabetes</fullName>
    </customValue>
    <masterLabel>Condition Sub Category</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Ethnicity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hispanic or Latino</fullName>
    </customValue>
    <customValue>
        <fullName>Not Hispanic or Latino</fullName>
    </customValue>
    <customValue>
        <fullName>Prefer Not to Answer</fullName>
    </customValue>
    <masterLabel>Ethnicity</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Race.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>American Indian or Alaska Native</fullName>
    </customValue>
    <customValue>
        <fullName>Asian</fullName>
    </customValue>
    <customValue>
        <fullName>Black or African American</fullName>
    </customValue>
    <customValue>
        <fullName>Hawaiian or Other Pacific Islander</fullName>
    </customValue>
    <customValue>
        <fullName>Middle Eastern and North African (MENA)</fullName>
    </customValue>
    <customValue>
        <fullName>Prefer Not to Answer</fullName>
    </customValue>
    <customValue>
        <fullName>White or Caucasian</fullName>
    </customValue>
    <masterLabel>Race</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Relationship.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Mother</fullName>
    </customValue>
    <customValue>
        <fullName>Father</fullName>
    </customValue>
    <customValue>
        <fullName>Full Sibling</fullName>
    </customValue>
    <customValue>
        <fullName>Half Sibling</fullName>
    </customValue>
    <customValue>
        <fullName>Grandparent</fullName>
    </customValue>
    <customValue>
        <fullName>Uncle/Aunt</fullName>
    </customValue>
    <customValue>
        <fullName>First Cousin</fullName>
    </customValue>
    <customValue>
        <fullName>Grandchild</fullName>
    </customValue>
    <customValue>
        <fullName>Niece/Nephew</fullName>
    </customValue>
    <customValue>
        <fullName>Spouse/Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Co-Worker</fullName>
    </customValue>
    <customValue>
        <fullName>Employer</fullName>
    </customValue>
    <customValue>
        <fullName>Therapist</fullName>
    </customValue>
    <customValue>
        <fullName>Child</fullName>
        <isActive>false</isActive>
        <label>Child</label>
    </customValue>
    <customValue>
        <fullName>Maternal Uncle/Aunt</fullName>
        <isActive>false</isActive>
        <label>Maternal Uncle/Aunt</label>
    </customValue>
    <customValue>
        <fullName>Maternal Grandparent</fullName>
        <isActive>false</isActive>
        <label>Maternal Grandparent</label>
    </customValue>
    <customValue>
        <fullName>Paternal Uncle/Aunt</fullName>
        <isActive>false</isActive>
        <label>Paternal Uncle/Aunt</label>
    </customValue>
    <customValue>
        <fullName>Paternal Grandparent</fullName>
        <isActive>false</isActive>
        <label>Paternal Grandparent</label>
    </customValue>
    <customValue>
        <fullName>Paternal Half Sibling</fullName>
        <isActive>false</isActive>
        <label>Paternal Half Sibling</label>
    </customValue>
    <customValue>
        <fullName>Maternal Half Sibling</fullName>
        <isActive>false</isActive>
        <label>Maternal Half Sibling</label>
    </customValue>
    <masterLabel>Relationship</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/KHC_ExportMedicalHistoryController.cls
/**
 * Controller for the Export Medical History VF page
 * Loads patient record (Person Account) and all related medical history records for rendering in VF as a PDF document
 * 
 * @author Grant Adamson, Traction on Demand
 * @date 2020-08-13
 */
public with sharing class KHC_ExportMedicalHistoryController {
    @TestVisible
    private static final String UNABLE_TO_LOAD_ACCOUNT_ERROR_MSG = 'Unable to load account for Id provided';

    public Account patient { get; private set; }
    public List<Patient_Contact__c> familyMedicalHistories { get; private set; }
    public List<Family_Medical_History_Condition__c> familyMedicalHistoryConditions { get; private set; }


    public KHC_ExportMedicalHistoryController(ApexPages.StandardController ctlr) {
        Id accountId = ctlr.getId();

        patient = loadPatient(accountId);
        familyMedicalHistories = loadFamilyMedicalHistory(accountId);
        familyMedicalHistoryConditions = extractConditionsFromFamilyHistories(familyMedicalHistories);

        String filename = generateFilename(patient);
        setFilenameHeader(filename);
    }

    private Account loadPatient(Id accountId) {
        List<Account> result = selectAccountById(accountId);

        if (result.isEmpty()) {
            throw new MedicalHistoryControllerException(UNABLE_TO_LOAD_ACCOUNT_ERROR_MSG);
        }

        return result[0];
    }

    private List<Patient_Contact__c> loadFamilyMedicalHistory(Id accountId) {
        return selectFamilyMedicalHistoryByAccountIdWithConditions(accountId);
    }

    private List<Account> selectAccountById(Id accountId) {
        return [
                SELECT Name, 
                FirstName, 
                LastName, 
                Breast_Cancer_Status__c, 
                PersonEmail, 
                Phone, 
                Gender__pc,
                HealthCloudGA__BirthDate__pc,
                Blood_Type__pc,
                Height_ft__pc,
                Height_in__pc,
                Weight__c,
                Ethnicity__pc
                FROM Account
                WHERE Id = :accountId
        ];
    }

    private static List<Patient_Contact__c> selectFamilyMedicalHistoryByAccountIdWithConditions(Id accountId) {
        return [
                SELECT Relationship__c, Related_through_family_member__c, Family_Member_Name__c, Gender__c,
                        Was_this_person_born_a_twin_multiple__c, Birth_Year__c, Adopted__c, Race_Picklist__c, Ethnicity__c,
                        Are_They_Ashkenazi_Jewish__c, Is_this_person_living__c, Estimated_Age_at_Death__c,
                        Cause_of_Death__c,
                (
                        SELECT Condition_Category__c, Condition_Sub_Category__c, Family_Medical_History__c,
                                Family_Medical_History__r.Family_Member_Name__c, Age_at_diagnosis__c
                        FROM Family_Medical_History_Conditions__r
                )
                FROM Patient_Contact__c
                WHERE Patient__c = :accountId
        ];
    }

    private List<Family_Medical_History_Condition__c> extractConditionsFromFamilyHistories(
            List<Patient_Contact__c> histories) {

        List<Family_Medical_History_Condition__c> result = new List<Family_Medical_History_Condition__c>();

        for ( Patient_Contact__c history : histories) {
            if (history.Family_Medical_History_Conditions__r.size() > 0) {
                result.addAll(history.Family_Medical_History_Conditions__r);
            }
        }

        return result;
    }
    private String generateFilename(Account patient) {
        return String.join(new String[]{
                patient.LastName, patient.FirstName, Label.Export_Medical_History_Main_Heading
        }, '_');
    }

    private void setFilenameHeader(String filename) {
        ApexPages.currentPage().getHeaders().put('content-disposition', 'attachment; filename=' + filename + '.pdf');
    }

    @TestVisible
    private class MedicalHistoryControllerException extends Exception {
    }
}