unpackaged/main/default/objects/Account/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Using Trigger, Update Payment Date from Payment obj.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track Health Insurance Information for a Patient</description>
    <label>Application</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Email__c</fullName>
    <description>Application Email ID</description>
    <label>Applicant Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Applicant_within_income_guideline__c.field-meta.xml
<CustomField>
    <fullName>Applicant_within_income_guideline__c</fullName>
    <description>Whether the Applicant comes under Income Guidelines? This field get Auto Populated.</description>
    <inlineHelpText>Is Applicant within income guidelines?</inlineHelpText>
    <label>Applicant Within Income Guidelines?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Incomplete Application</fullName>
            </value>
            <value>
                <fullName>No Income Guidelines On Care Program</fullName>
            </value>
            <value>
                <fullName>Care Program Not Selected</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>The Status from the Application Submitted/New to till Approved or Rejected.</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Need More Information</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Payment Error</fullName>
                <isActive>false</isActive>
                <label>Payment Error</label>
            </value>
            <value>
                <fullName>Payment Processing</fullName>
                <isActive>false</isActive>
                <label>Payment Processing</label>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Care_Program__c.field-meta.xml
<CustomField>
    <fullName>Care_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Care Program, Populate Name of the Care Program for the Application.</description>
    <label>Care Program</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CareProgram.Care_Program_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.Application_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>CareProgram.Status</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Applications (Care Program)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Deferred_Status_Duration__c.field-meta.xml
<CustomField>
    <fullName>Deferred_Status_Duration__c</fullName>
    <description>The Duration from Deferred to any other Stage. Using Trigger this field get Update.</description>
    <label>Deferred Status Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/In_Review_Status_Duration__c.field-meta.xml
<CustomField>
    <fullName>In_Review_Status_Duration__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The Duration from In Review to any other Stage. Using Trigger this field get Update.</description>
    <label>In Review Status Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Income_Verification_is_Valid__c.field-meta.xml
<CustomField>
    <fullName>Income_Verification_is_Valid__c</fullName>
    <description>Check true if Patient/Relative provided income documents are valid.</description>
    <inlineHelpText>Check true if Patient/Relative provided income documents are valid.</inlineHelpText>
    <label>Income Verification Is Valid?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Need_More_Info_Status_Duration__c.field-meta.xml
<CustomField>
    <fullName>Need_More_Info_Status_Duration__c</fullName>
    <description>The Duration from Need More Information Status to any other Stage . Using Trigger this field get Update.</description>
    <label>Need More Info Status Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/New_Status_Duration__c.field-meta.xml
<CustomField>
    <fullName>New_Status_Duration__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The Duration from New to any other Stage.</description>
    <label>New Status Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup with Account, to Populate Patient or Applicant Name.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Using Trigger, Update Payment Date from Payment obj.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Physician_confirms_patient_inactive_tre__c.field-meta.xml
<CustomField>
    <fullName>Physician_confirms_patient_inactive_tre__c</fullName>
    <description>Has physician confirmed if patient is in active breast cancer treatment?</description>
    <inlineHelpText>Has physician confirmed if patient is in active breast cancer treatment?</inlineHelpText>
    <label>Physician Confirms Active Treatment?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Poverty_Level__c.field-meta.xml
<CustomField>
    <fullName>Poverty_Level__c</fullName>
    <description>This field get Auto Calculated based on Financial Information.</description>
    <label>Poverty Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Status_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Change_Date__c</fullName>
    <label>Status Change Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/Eligibility_Detail__c.object-meta.xml
<CustomObject>
    <description>This objects holds data details of Care Program eligibility criteria.</description>
    <label>Eligibility Detail</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Eligibility Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligibility Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/Care_Program__c.field-meta.xml
<CustomField>
    <fullName>Care_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Eligibility Details</relationshipLabel>
    <relationshipName>Eligibility_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TAP_Application_Helper_Test.cls
@isTest
public class TAP_Application_Helper_Test {
    @testSetup static void setup() {
        
        //List<User> createUser = TAP_TestDataFactory.createUser();
        
        //Create common test accounts
        List<Account> testaccounts = TAP_TestDataFactory.createAccount(2,'Account');
        
        // Create common test care Program
        List<CareProgram> testCarePrograms = TAP_TestDataFactory.createCareProgram(2,'careProgram');
        
        // Create common test application
        List<Application__c> testapplications = TAP_TestDataFactory.createApplication(1,testaccounts[0].Id,testCarePrograms[0].Id);
        // Create common test EnrollmentEligibilityCriteria
        List<EnrollmentEligibilityCriteria> enrollmentEligibilityCriterias = TAP_TestDataFactory.createEnrollmentEligibilityCriteria(1,'Income','TestIncomeCriteria');
        
        // Create common test CareProgramEligibilityRule
        List<CareProgramEligibilityRule> careProgramRules = TAP_TestDataFactory.careProgramEligibilityRule(1,enrollmentEligibilityCriterias[0].Id,testCarePrograms[0].Id);
        
        // Create common test CareProgramEligibilityRule
        List<Eligibility_Detail__c> eligibilityDetails =TAP_TestDataFactory.createEligibilityDetail('Income',enrollmentEligibilityCriterias[0].Id,'NY','10001'); 
        
    }
    
    @isTest static void calculateStatusDurationTest(){
        
        //SOQL to get Account
        List<Account> accounts = [SELECT Id,Payment_Date__c,PersonEmail FROM Account  WHERE LastName = 'Account0'];
        
        //SOQL to get Care Program
        List<CareProgram> careProgram = [Select Id FROM CareProgram WHERE Name = 'careProgram0'];
        
        //SOQL to get Application
        Application__c application = [SELECT ID,New_Status_Duration__c FROM Application__c WHERE Patient__c =:accounts[0].id];
        
        //Update Application
        application.Application_Status__c = TAP_Constants.APPLICATION_STATUS_IN_REVIEW;
        application.Status_Change_Date__c = date.newInstance(2020, 07,15);
        update application;
		
        //Update Application
        application.Application_Status__c = TAP_Constants.APPLICATION_STATUS_NEED_MORE_INFO;
        application.Status_Change_Date__c = date.newInstance(2020, 07,18);
        update application;
		
        //Update Application
        application.Application_Status__c = TAP_Constants.APPLICATION_STATUS_DEFERRED;
        application.Status_Change_Date__c = date.newInstance(2020, 07,20);
        update application;
        
        //Update Application
        application.Status_Change_Date__c = date.newInstance(2020, 07,25);
        application.Application_Status__c = TAP_Constants.APPLICATION_STATUS_APPROVED; 
        update application;

        test.startTest();
        TAP_Application_Helper.calculateStatusDuration(application,'new');
        test.stopTest(); 
        
        //SOQL to get Application
        Application__c applications = [SELECT ID,In_Review_Status_Duration__c,Need_More_Info_Status_Duration__c,Deferred_Status_Duration__c 
                                            FROM Application__c WHERE Patient__c =:accounts[0].id];
        
        //Asserts for Duration check
        system.assertEquals(true,applications.In_Review_Status_Duration__c != null);
        system.assertEquals(true,applications.Need_More_Info_Status_Duration__c != null);
        system.assertEquals(true,applications.Deferred_Status_Duration__c != null);   
    }
    
    @isTest static void updateIncomeGuidelinesCheck(){
        String incomeGuideLines ='No Income Guidelines On Care Program';
        List<Account> accounts = [SELECT Id,Payment_Date__c,PersonEmail FROM Account  WHERE LastName = 'Account0'];
        
        List<Application__c> applications = [SELECT ID,Care_Program__c,Poverty_Level__c FROM Application__c WHERE Patient__c =:accounts[0].id];
        test.startTest();
        TAP_Application_Helper.updateIncomeGuidelinesCheck(applications);
        test.stopTest();
        
        Application__c application = [SELECT Id,Care_Program__c,Poverty_Level__c,Applicant_within_income_guideline__c 
                                      FROM Application__c WHERE Id=:applications[0].Id];
        
        // system.debug('@@application'+application);
        system.assertEquals(incomeGuideLines, application.Applicant_within_income_guideline__c);  
    }
    
    @isTest static void getIncompleteReviewChecksTest(){
        
        String comments  = '(Invalid income proof, Patient is not in active Breast Cancer treatment, Income not withing income guidelines)';
        
        //SOQL to get Account
        List<Account> accounts = [SELECT Id,Payment_Date__c,PersonEmail FROM Account WHERE LastName = 'Account0'];
        
        //SOQL to get Application
        Application__c application = [SELECT ID,Care_Program__c FROM Application__c WHERE Patient__c =:accounts[0].id];
        application.Income_Verification_is_Valid__c = TAP_Constants.NO;
        application.Physician_confirms_patient_inactive_tre__c = TAP_Constants.NO;
        application.Applicant_within_income_guideline__c = TAP_Constants.NO;
        update application;
        
        test.startTest();
        List<String> reviewCheck = TAP_Application_Helper.getIncompleteReviewChecks(application.id);
        String returnComments = String.valueOf(reviewCheck);
        test.stopTest();
        
        //Asserts to checking rejection commentxs
        system.assertEquals(comments,returnComments);  
    }
    
    @isTest static void getIncompleteReviewCheckwithNoProofTest(){
        
        String comment  = '(Income details not provided)';
        
        List<Account> accounts = [SELECT Id,Payment_Date__c,PersonEmail FROM Account  WHERE LastName = 'Account0'];
       
        //SOQL to get Application   
        Application__c application = [SELECT ID,Care_Program__c FROM Application__c WHERE Patient__c =:accounts[0].id];
        application.Income_Verification_is_Valid__c = TAP_Constants.YES;
        application.Physician_confirms_patient_inactive_tre__c = TAP_Constants.YES;
		application.Applicant_within_income_guideline__c = TAP_Constants.UNKNOWN;
        update application;
        
        test.startTest();
        List<String> reviewCheckwithNoProof = TAP_Application_Helper.getIncompleteReviewChecks(application.id);
        test.stopTest();
        
        String returnComment = String.valueOf(reviewCheckwithNoProof);
        //Asserts forrejection comments
        system.assertEquals(comment,returnComment); 
    }   
    @isTest static void copyEmailIdFromAccountTest(){
        
        List<Account> accounts = [SELECT Id,Payment_Date__c,PersonEmail FROM Account];
        
        Map<Id,Application__c> oldApplicationsMap = New Map<Id,Application__c>();
        List<Application__c> applications = [SELECT ID,Patient__c,Care_Program__c FROM Application__c WHERE Patient__c =:accounts[0].id];
        oldApplicationsMap.put(applications[0].id,applications[0]);
        system.debug('@@oldApplicationsMap :: '+oldApplicationsMap);
        applications[0].Patient__c = accounts[1].Id;
        update applications[0];
        system.debug('@@updatedApplication::'+applications);
        
        test.startTest();
        TAP_Application_Helper.copyEmailIdFromAccount(applications,oldApplicationsMap);
        test.stopTest();
        
        Application__c application = [SELECT Id,Applicant_Email__c,Patient__c FROM Application__c WHERE Patient__c =:accounts[1].id];
        system.debug('@@application'+application);
        system.assertEquals(accounts[1].PersonEmail, application.Applicant_Email__c);
        
        
        
    }
}