unpackaged/main/default/objects/Account/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Using Trigger, Update Payment Date from Payment obj.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track Health Insurance Information for a Patient</description>
    <label>Application</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Applicant_within_income_guideline__c.field-meta.xml
<CustomField>
    <fullName>Applicant_within_income_guideline__c</fullName>
    <description>Whether the Applicant comes under Income Guidelines? This field get Auto Populated.</description>
    <inlineHelpText>Is Applicant within income guidelines?</inlineHelpText>
    <label>Applicant Within Income Guidelines?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Incomplete Application</fullName>
            </value>
            <value>
                <fullName>No Income Guidelines On Care Program</fullName>
            </value>
            <value>
                <fullName>Care Program Not Selected</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>The Status from the Application Submitted/New to till Approved or Rejected.</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Need More Information</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Payment Error</fullName>
                <isActive>false</isActive>
                <label>Payment Error</label>
            </value>
            <value>
                <fullName>Payment Processing</fullName>
                <isActive>false</isActive>
                <label>Payment Processing</label>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Income_Verification_is_Valid__c.field-meta.xml
<CustomField>
    <fullName>Income_Verification_is_Valid__c</fullName>
    <description>Check true if Patient/Relative provided income documents are valid.</description>
    <inlineHelpText>Check true if Patient/Relative provided income documents are valid.</inlineHelpText>
    <label>Income Verification Is Valid?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup with Account, to Populate Patient or Applicant Name.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Using Trigger, Update Payment Date from Payment obj.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Physician_confirms_patient_inactive_tre__c.field-meta.xml
<CustomField>
    <fullName>Physician_confirms_patient_inactive_tre__c</fullName>
    <description>Has physician confirmed if patient is in active breast cancer treatment?</description>
    <inlineHelpText>Has physician confirmed if patient is in active breast cancer treatment?</inlineHelpText>
    <label>Physician Confirms Active Treatment?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TAP_Application_Ctlr_Test.cls
@isTest
public class TAP_Application_Ctlr_Test {
    @testSetup static void setup() {
        
        // Create common test User
        List<User> testUser = TAP_TestDataFactory.createUser();
        
        //Create common test accounts
        List<Account> testaccounts = TAP_TestDataFactory.createAccount(2,'Account');
        
        // Create common test care Program
        List<CareProgram> testCarePrograms = TAP_TestDataFactory.createCareProgram(2,'careProgram');
        
        // Create common test application
        List<Application__c> testapplications = TAP_TestDataFactory.createApplication(2,testaccounts[0].Id,testCarePrograms[0].Id);   
    }
    
    @isTest static void initialValueTest(){
  
        //SOQL to get Account
        List<Account> accounts = [SELECT Id,Payment_Date__c,PersonEmail FROM Account WHERE LastName = 'Account0'];
        
        //SOQL to get Care Program
        List<CareProgram> careProgram = [SELECT Id FROM CareProgram  WHERE Name = 'careProgram0'];
        
        //SOQL to get Application
        Application__c application = [SELECT ID FROM Application__c WHERE Patient__c =:accounts[0].id LIMIT 1];
        
        Test.startTest();
        String Status = TAP_Application_ctlr.initialValue(application.Id);
        Test.stopTest();
        
        //Assert for checking status
        system.assertEquals('New',status);
    }
    
    @isTest static void loadProgramsTest(){
        
        //SOQL to get Account
        List<Account> accounts = [SELECT Id,Payment_Date__c,PersonEmail FROM Account WHERE LastName = 'Account0'];
        
        //SOQL to get Care Program
        List<CareProgram> careProgram = [SELECT Id FROM CareProgram WHERE Name = 'careProgram0'];
        
        //SOQL to get Application
        Application__c application = [SELECT ID FROM Application__c WHERE Patient__c =:accounts[0].id LIMIT 1];
        
        Test.startTest();
        Map<String,List<CareProgram>> careProgramMap = TAP_Application_ctlr.loadPrograms(application.Id);
        Test.stopTest();
        
        //Assert for checking size of care Program
        system.assertEquals(3,careProgramMap.size());  
    }
    
    @isTest static void relatedApplicationlistTest(){
        
        //SOQL to get Account
        List<Account> accounts = [SELECT Id,Payment_Date__c,PersonEmail FROM Account WHERE LastName = 'Account0'];
        
        //SOQL to get Care Program
        List<CareProgram> careProgram = [SELECT Id FROM CareProgram WHERE  Name = 'careProgram0'];
        
        //SOQL to get Application
        Application__c application = [SELECT ID FROM Application__c WHERE Patient__c =:accounts[0].id LIMIT 1];
        
        test.startTest();
        List<Application__c> apps= TAP_Application_ctlr.relatedApplicationlist(application.Id);
        test.stopTest();
        
        //List of Application
        List<Application__c> otherApplication = [SELECT ID FROM Application__c WHERE Id != :application.Id];
        
        //Assert for checking application other than current application
        system.assertEquals(1,otherApplication.size());    
    }
    
    @isTest static  void calculateRejectionCommentTest(){
        
        String rejectionComment ='<html><body><ul><li>Patient is not in active Breast Cancer treatment</li></ul></body></html>';
        
        //SOQL to get Account
        List<Account> accounts = [SELECT Id,Payment_Date__c,PersonEmail FROM Account WHERE LastName = 'Account0'];
        
        //SOQL to get Application
        Application__c application = [SELECT ID FROM Application__c WHERE Patient__c =:accounts[0].id LIMIT 1];
        application.Income_Verification_is_Valid__c = TAP_Constants.YES;
        application.Physician_confirms_patient_inactive_tre__c = TAP_Constants.NO;
        application.Applicant_within_income_guideline__c = TAP_Constants.YES;
        update application;
        
        test.startTest();
        String rejectionComments =  TAP_Application_ctlr.calculateRejectionComment(application.Id);  
        test.stopTest();
        
        //Assert for checking rejection comments
        system.assertEquals(rejectionComment, rejectionComments);
    }
    
    @isTest static void checkAccessTest(){
        
        test.startTest();
        Map<String,Boolean> hasEditAccessToApplicationMap = TAP_Application_ctlr.checkAccessOnApplication(); 
        test.stopTest();
        
        // Checking User have dit access on application or not
        system.assertEquals(true, hasEditAccessToApplicationMap.get('hasEditAccess'));   
    }

    @isTest static void checkEditTest(){
        //SOQL to get Account
        List<Account> accounts = [SELECT Id,Payment_Date__c,PersonEmail FROM Account WHERE LastName = 'Account0'];
        
        //SOQL to get Care Program
        List<CareProgram> careProgram = [Select Id FROM CareProgram WHERE Name = 'careProgram0'];
        
        //SOQL to get Application
        List<Application__c> application = [SELECT ID,Application_Status__c FROM Application__c WHERE Patient__c =:accounts[0].id];
        application[0].Application_Status__c = TAP_Constants.APPLICATION_STATUS_APPROVED;
        update application;
        
        test.startTest();
        Map<String,Boolean> hasEditAccessToApplicationMap = TAP_Application_ctlr.checkAccessesOnApplication(application[0].Id); 
        test.stopTest();
        
        //Asserts for checking access
        system.assertEquals(true, hasEditAccessToApplicationMap.get('hasEditAccess'));
        system.assertEquals(true, hasEditAccessToApplicationMap.get('isAdmin'));
        
    }
    
    
    @isTest static void isCareProgramSuggestedTest(){
        
        ///SOQL to get Account
        List<Account> accounts = [SELECT Id,Payment_Date__c,PersonEmail FROM Account WHERE LastName = 'Account0'];
        
        //SOQL to get Care Program
        List<CareProgram> careProgram = [Select Id FROM CareProgram WHERE Name = 'careProgram0'];
        
        //SOQL to get Application
        List<Application__c> application = [SELECT ID FROM Application__c WHERE Patient__c =:accounts[0].id LIMIT 1];

        test.startTest();
        Boolean isCareProgramSuggested = TAP_Application_ctlr.isCareProgramSuggested(application[0].Id,careProgram[0].Id); 
        test.stopTest();
        
        //Asserts for checking care program is in Suggested Care Program
        system.assertEquals(true, isCareProgramSuggested);
    }
}