unpackaged/main/default/objects/Account/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Using Trigger, Update Payment Date from Payment obj.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/PeopleSoft_Id__c.field-meta.xml
<CustomField>
    <fullName>PeopleSoft_Id__c</fullName>
    <description>Map this field with People Soft(Vendor) Id for Import/Export data.</description>
    <externalId>true</externalId>
    <inlineHelpText>PeopleSoft Vendor Id</inlineHelpText>
    <label>PeopleSoft Id (Vendor)</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track Health Insurance Information for a Patient</description>
    <label>Application</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>The Status from the Application Submitted/New to till Approved or Rejected.</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Need More Information</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Payment Error</fullName>
                <isActive>false</isActive>
                <label>Payment Error</label>
            </value>
            <value>
                <fullName>Payment Processing</fullName>
                <isActive>false</isActive>
                <label>Payment Processing</label>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Care_Program__c.field-meta.xml
<CustomField>
    <fullName>Care_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Care Program, Populate Name of the Care Program for the Application.</description>
    <label>Care Program</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CareProgram.Care_Program_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.Application_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>CareProgram.Status</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Applications (Care Program)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup with Account, to Populate Patient or Applicant Name.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Using Trigger, Update Payment Date from Payment obj.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <description>Using Trigger, Update Payment Status from Payment obj.</description>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payment Processing</fullName>
            </value>
            <value>
                <fullName>Payment Error</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/PeopleSoft_Id__c.field-meta.xml
<CustomField>
    <fullName>PeopleSoft_Id__c</fullName>
    <description>Map this field with People Soft(Vendor) Id while Import/Export data.</description>
    <externalId>true</externalId>
    <label>PeopleSoft Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CareProgram/fields/Current_Monthly_Payout__c.field-meta.xml
<CustomField>
    <fullName>Current_Monthly_Payout__c</fullName>
    <description>Current Monthly Payout Amount for the Care Program.</description>
    <label>Current Monthly Payout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/CareProgram/fields/Payout_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payout_Amount__c</fullName>
    <description>Payout Amount for this Care Program.</description>
    <label>Payout Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>this Object is used to track Payment Information for Patient/Applicant.</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup with Account to Populate Name of the Patient/Applicant.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Enter Award Amount for Applicant.</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup with Application, to Populate Application Id.</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Care_Program__c.field-meta.xml
<CustomField>
    <fullName>Care_Program__c</fullName>
    <description>Populate Care Program Name from Care Program.</description>
    <label>Care Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Application Payment Date.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <description>Status of Application Payment. default the Payment Status is Pending.</description>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payment Processing</fullName>
            </value>
            <value>
                <fullName>Payment Error</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Payout_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payout_Amount__c</fullName>
    <description>Lookup with  Care Program, to Populate Payout Amount from Care Program.</description>
    <formula>Care_Program__r.Payout_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payout Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/PeopleSoft_Id__c.field-meta.xml
<CustomField>
    <fullName>PeopleSoft_Id__c</fullName>
    <description>Map with People Soft, while import/export data.</description>
    <externalId>true</externalId>
    <inlineHelpText>PeopleSoft Voucher ID</inlineHelpText>
    <label>PeopleSoft Id (Voucher)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Supplier_ID__c.field-meta.xml
<CustomField>
    <fullName>Supplier_ID__c</fullName>
    <label>Supplier ID</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/TAP_Payment_Helper.cls
/****************************************************************************************************************************************************************
* @author IVL Dev
* @date 18-July-2020
* @description Helper of Payment Trigger Handler.
****************************************************************************************************************************************************************/
public without sharing class TAP_Payment_Helper {

    /***********************************************************************************************
    * @description create or update payment information
    * @param List<Application__c> applications of Application  
    * @param Map<Id,Application__c> oldApplicationsMap of Application
    ************************************************************************************************/
    public static void updatePaymentStatus(List<Application__c> applications,Map<Id,Application__c> oldApplicationsMap){
       
        List<Payment__c> upsertPayments = new List<Payment__C>();
        List<Application__c> applicationList = [SELECT ID,Care_Program__c,Care_Program__r.Payout_Amount__c,Application_Status__c,Patient__c,
                                                (SELECT id, Amount__c, Care_Program__c,Payment_Status__c FROM Payments__r) 
                                                FROM Application__c WHERE ID in :applications];
       // system.debug('applicationlist :: ' + applicationList);
        for (Application__c application : applicationList){
           //  system.debug('application id :: ' + application.Id);
            Application__c oldApplication =oldApplicationsMap.get(application.Id);
           // system.debug('oldApplication :: ' + oldApplication);
           // if condition to check oldApplication is not null is added by Sachin
          
            if(oldApplication != null){
                if ((application.Application_Status__c != oldApplication.Application_Status__c || application.Care_Program__c != oldApplication.Care_Program__c) && application.Application_Status__c == TAP_Constants.APPLICATION_STATUS_APPROVED){
                    
                    if(application.Payments__r != null && application.Payments__r.size() > 0){
                        upsertPayments.add(populatePayment(application.Payments__r.get(0),application,
                                                           application.Care_Program__r.Payout_Amount__c));
                    }else{
                        Payment__c payment = populatePayment(new Payment__c(),application,
                                                             application.Care_Program__r.Payout_Amount__c);
                        upsertPayments.add(payment);   
                    }
                }  
            }
        }
        if(upsertPayments.size() > 0) {
            Database.upsert(upsertPayments, false);
        }
    }
    
    /***********************************************************************************************
    * @description method to replicate the info after Peoplesoft updates Payments details
    * @param List<Payment__c> payments of Payment      
    ************************************************************************************************/
    
    public static void syncAfterPeoplesoftPaymentUpdate(List<Payment__c> payments) {
        
        List<Account> accounts = new List<Account>();
        List<Application__c> applications = new List<Application__c>();
        for(Payment__c payment : payments) {
            if(payment.Supplier_ID__c != null) {
                Account account = new Account(id=payment.Account__c);
                account.PeopleSoft_Id__c = payment.Supplier_ID__c;
                if(payment.Payment_Status__c == TAP_Constants.PAYMENT_STATUS_PAID) {
                	account.Payment_Date__c = payment.Payment_Date__c;
            	}
                accounts.add(account);
            }
            applications.add(new Application__c(id = payment.Application__c, Payment_Status__c = payment.Payment_Status__c,
                                                           Payment_Date__c = payment.Payment_Date__c));
        }
        if(accounts.size() > 0) {
            Database.update(accounts,false);
        }
        if(applications.size() > 0) {
            Database.update(applications,false);
        }
    }
    /***********************************************************************************************
	* @description method to replicate Amount of payment object on  Current Monthly Payout  of 
	* careProgram object
    * @param payments list of Payments    
    ************************************************************************************************/
     
    public static void updateCarePrograms(List<Payment__c> payments) {
        List<Id> careProgramIds = new List<Id>();
        Map<Id, CareProgram> careProgramsMap = new Map<Id, CareProgram>();
        for(Payment__c payment : payments) {
            careProgramIds.add(payment.Care_Program__c);
        }
        
        careProgramsMap = new Map<Id, CareProgram>([SELECT Id, Current_Monthly_Payout__c FROM CareProgram WHERE Id in :careProgramIds]);
        
        for(Payment__c payment : payments) {
            CareProgram careProgram = careProgramsMap.get(payment.Care_Program__c);
            if(careProgram.Current_Monthly_Payout__c <> null && payment.Amount__c <> null){
                careProgram.Current_Monthly_Payout__c = careProgram.Current_Monthly_Payout__c + payment.Amount__c;    
            }else{
                if(payment.Amount__c <> null){
                	careProgram.Current_Monthly_Payout__c =  payment.Amount__c;    
                }
            }
        }

        if(careProgramsMap.size() > 0) {
            Database.update(careProgramsMap.values(), false);
        }
    }

    private static Payment__c populatePayment(Payment__c payment,Application__c application,Decimal amount) {
        payment.Application__c = application.Id;
        payment.Account__c = application.Patient__c;
        payment.Payment_Status__c = TAP_Constants.PAYMENT_STATUS_PENDING;
        payment.Care_Program__c = application.Care_Program__c;
        payment.Amount__c = amount;
        return payment;
    }
}