unpackaged/main/default/objects/Account/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Using Trigger, Update Payment Date from Payment obj.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track Health Insurance Information for a Patient</description>
    <label>Application</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Applicant_within_income_guideline__c.field-meta.xml
<CustomField>
    <fullName>Applicant_within_income_guideline__c</fullName>
    <description>Whether the Applicant comes under Income Guidelines? This field get Auto Populated.</description>
    <inlineHelpText>Is Applicant within income guidelines?</inlineHelpText>
    <label>Applicant Within Income Guidelines?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Incomplete Application</fullName>
            </value>
            <value>
                <fullName>No Income Guidelines On Care Program</fullName>
            </value>
            <value>
                <fullName>Care Program Not Selected</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>The Status from the Application Submitted/New to till Approved or Rejected.</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Need More Information</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Payment Error</fullName>
                <isActive>false</isActive>
                <label>Payment Error</label>
            </value>
            <value>
                <fullName>Payment Processing</fullName>
                <isActive>false</isActive>
                <label>Payment Processing</label>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/New_Status_Duration__c.field-meta.xml
<CustomField>
    <fullName>New_Status_Duration__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The Duration from New to any other Stage.</description>
    <label>New Status Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup with Account, to Populate Patient or Applicant Name.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Using Trigger, Update Payment Date from Payment obj.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Status_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Change_Date__c</fullName>
    <label>Status Change Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Suggested_Care_Program__c/Suggested_Care_Program__c.object-meta.xml
<CustomObject>
    <label>Suggested Care Program</label>
    <nameField>
        <label>Suggested Programs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suggested Care Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Suggested_Care_Program__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>Suggested_Program</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/TAP_ApplicationTrigger_Handler_Test.cls
@isTest
public class TAP_ApplicationTrigger_Handler_Test { 
    @testSetup static void setup() {
        
        // Create common test User
        List<User> testUser = TAP_TestDataFactory.createUser();
        
        //Create common test accounts
        List<Account> testaccounts = TAP_TestDataFactory.createAccount(2,'Account');
        
        // Create common test care Program
        List<CareProgram> testCarePrograms = TAP_TestDataFactory.createCareProgram(2,'careProgram');
        
        // Create common test application
        List<Application__c> testapplications = TAP_TestDataFactory.createApplication(1,testaccounts[0].Id,testCarePrograms[0].Id);    
    }
    
    @isTest static void applicationTest(){
        
        //SOQL to get Account
        List<Account> accounts = [SELECT Id,Payment_Date__c,PersonEmail FROM Account WHERE LastName = 'Account0'];
        
        //SOQL to get Care Program
        List<CareProgram> careProgram = [Select Id FROM CareProgram WHERE Name = 'careProgram0'];
        
        //SOQL to get Application
        List<Application__c> application = [SELECT ID,Status_Change_Date__c,Applicant_within_income_guideline__c FROM Application__c WHERE Patient__c =:accounts[0].id];
        
        //Assert for checking Status Change Date
        system.assertEquals(system.today(), application[0].Status_Change_Date__c);
        
        //query to get Suggested Care Program
        List<Suggested_Care_Program__c> suggestedCareProgram = [SELECT Id,Name,Application__c FROM Suggested_Care_Program__c WHERE Application__c =:application[0].Id];
        
        //Assert for checking application on Suggested Care Programs
        system.assertEquals('No Income Guidelines On Care Program', application[0].Applicant_within_income_guideline__c);
        
        //Update Application
        application[0].Application_Status__c =TAP_Constants.APPLICATION_STATUS_IN_REVIEW;
        update application;
        
        //query to get Application
        List<Application__c> applicationToUse = [SELECT ID,Status_Change_Date__c,New_Status_Duration__c FROM Application__c WHERE Patient__c =:accounts[0].Id];
        //Asserts for checking 
        system.assertEquals(system.today(), applicationToUse[0].Status_Change_Date__c);
        
        //Update Applucation status
        application[0].Application_Status__c =TAP_Constants.APPLICATION_STATUS_APPROVED;
        update application;
        
        // List of Suggested Care Programs
        List<Suggested_Care_Program__c> suggestedCarePrograms = [select Id from Suggested_Care_Program__c where Id =:suggestedCareProgram[0].Id];
        //Asserts for checking Suggested Care Programs get deleted or not
        system.assertEquals(0,suggestedCarePrograms.size());
    }  
}