unpackaged/main/default/objects/Account/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Using Trigger, Update Payment Date from Payment obj.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track Health Insurance Information for a Patient</description>
    <label>Application</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Applicant_has_no_award_in_last_12months__c.field-meta.xml
<CustomField>
    <fullName>Applicant_has_no_award_in_last_12months__c</fullName>
    <description>Has the applicant been awarded treatment assistance in the last 12 months?</description>
    <formula>IF( CEILING(( TODAY()  -  Patient__r.Payment_Date__c ) / 365 * 12) &lt; 12 , &quot;No&quot;, &quot;Yes&quot;)</formula>
    <inlineHelpText>Is this applicant been awarded medical treatment assistance in past 12 Months?</inlineHelpText>
    <label>Applicant Has No Award In Last 12Months?</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Applicant_resides_US_Territory__c.field-meta.xml
<CustomField>
    <fullName>Applicant_resides_US_Territory__c</fullName>
    <description>Is this Applicant Resides under US Territory?</description>
    <formula>IF( ISPICKVAL( Patient__r.PersonContact.MailingCountryCode ,&apos;US&apos;), &quot;Yes&quot;, &quot;No&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Resides In US Territory?</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>The Status from the Application Submitted/New to till Approved or Rejected.</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Need More Information</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Payment Error</fullName>
                <isActive>false</isActive>
                <label>Payment Error</label>
            </value>
            <value>
                <fullName>Payment Processing</fullName>
                <isActive>false</isActive>
                <label>Payment Processing</label>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <description>Type of Application. default TAP.</description>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Treatment_Application_Program</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Care_Program__c.field-meta.xml
<CustomField>
    <fullName>Care_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Care Program, Populate Name of the Care Program for the Application.</description>
    <label>Care Program</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CareProgram.Care_Program_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.Application_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>CareProgram.Status</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Applications (Care Program)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Is_patient_in_active_treatment__c.field-meta.xml
<CustomField>
    <fullName>Is_patient_in_active_treatment__c</fullName>
    <description>Is this Patient  in Active Treatment?</description>
    <label>Is Patient In Active Treatment?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/No_of_People_in_the_Household__c.field-meta.xml
<CustomField>
    <fullName>No_of_People_in_the_Household__c</fullName>
    <description>Number of People in the Patient/Applicant House.</description>
    <label>No. Of People In The Household</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup with Account, to Populate Patient or Applicant Name.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Using Trigger, Update Payment Date from Payment obj.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Physician_confirms_patient_inactive_tre__c.field-meta.xml
<CustomField>
    <fullName>Physician_confirms_patient_inactive_tre__c</fullName>
    <description>Has physician confirmed if patient is in active breast cancer treatment?</description>
    <inlineHelpText>Has physician confirmed if patient is in active breast cancer treatment?</inlineHelpText>
    <label>Physician Confirms Active Treatment?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Poverty_Level__c.field-meta.xml
<CustomField>
    <fullName>Poverty_Level__c</fullName>
    <description>This field get Auto Calculated based on Financial Information.</description>
    <label>Poverty Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Total_annual_Household_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_annual_Household_Income__c</fullName>
    <description>Combined gross income of all members of a household.</description>
    <label>Total Annual Household Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/CareProgram/fields/Care_Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Program_Type__c</fullName>
    <label>Care Program Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Treatment_Application_Program</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CareProgramEligibilityRule/fields/Care_Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Program_Type__c</fullName>
    <formula>TEXT( CareProgram.Care_Program_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Care Program Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/Eligibility_Detail__c.object-meta.xml
<CustomObject>
    <description>This objects holds data details of Care Program eligibility criteria.</description>
    <label>Eligibility Detail</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Eligibility Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligibility Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/Care_Program__c.field-meta.xml
<CustomField>
    <fullName>Care_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Eligibility Details</relationshipLabel>
    <relationshipName>Eligibility_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/Eligibility_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Criteria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Eligibility Criteria</label>
    <referenceTo>EnrollmentEligibilityCriteria</referenceTo>
    <relationshipLabel>Eligibility Details</relationshipLabel>
    <relationshipName>Eligibility_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/Per_Person_Incremental_Amount__c.field-meta.xml
<CustomField>
    <fullName>Per_Person_Incremental_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Per Person Incremental Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/Single_Person_Income_Limit__c.field-meta.xml
<CustomField>
    <fullName>Single_Person_Income_Limit__c</fullName>
    <label>Single Person Income Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/ZIP_Code__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Code__c</fullName>
    <label>ZIP Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EnrollmentEligibilityCriteria/fields/Criteria_Type__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Type__c</fullName>
    <label>Criteria Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZIP</fullName>
            </value>
            <value>
                <fullName>Income</fullName>
            </value>
            <value>
                <fullName>USA Resident</fullName>
            </value>
            <value>
                <fullName>No Awards</fullName>
            </value>
            <value>
                <fullName>Patient Needs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EnrollmentEligibilityCriteria/fields/No_Income_in_Last_N_months__c.field-meta.xml
<CustomField>
    <fullName>No_Income_in_Last_N_months__c</fullName>
    <inlineHelpText>This denotes that the Care Program can be selected only if there is no awards in Last N months.</inlineHelpText>
    <label>No Award In Last N Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EnrollmentEligibilityCriteria/fields/Percent_Of_Poverty_Guideline__c.field-meta.xml
<CustomField>
    <fullName>Percent_Of_Poverty_Guideline__c</fullName>
    <inlineHelpText>This field should be selected when a criteria as Income based, It denotes that the patient/applicant eligibility for care program only with in his/her income or household income below the poverty guidelines.</inlineHelpText>
    <label>Income Guideline/Percent Of Poverty</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Suggested_Care_Program__c/Suggested_Care_Program__c.object-meta.xml
<CustomObject>
    <label>Suggested Care Program</label>
    <nameField>
        <label>Suggested Programs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suggested Care Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Suggested_Care_Program__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>Suggested_Program</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Suggested_Care_Program__c/fields/Care_Program__c.field-meta.xml
<CustomField>
    <fullName>Care_Program__c</fullName>
    <label>Care Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Suggested Care Programs</relationshipLabel>
    <relationshipName>Suggested_Program</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/globalValueSets/Treatment_Application_Program.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Treatment Assistance Program</fullName>
        <default>true</default>
        <label>Treatment Assistance Program</label>
    </customValue>
    <masterLabel>Treatment Application Program</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TAP_SuggestedProgramHelper.cls
/***************************************************************************************************************************************************************
* @author IVL Dev
* @date 20-May-2020
* @description Helper class to calculate Suggested Care Programs based on Application and Patient information.
***************************************************************************************************************************************************************/
public without sharing class TAP_SuggestedProgramHelper {
    
    static List<Application__c> applications = new List<Application__c>();
    static Map<String,List<Application__c>> applicationTypeMap = new Map<String,List<Application__c>>();
    static Map<String,List<CareProgram>> careProgramTypeMap = new Map<String,List<CareProgram>>();
    static Map<String,List<CareProgram>> careProgramTypeNoCriteriaMap = new Map<String,List<CareProgram>>();
    Static Map<Id,List<Id>> careProgramRelatedToApplicationMap = new Map<Id,List<Id>>();
    static Map<Id,List<Eligibility_Detail__c>> criteriaDetailsMap = new Map<Id,List<Eligibility_Detail__c>>();
    static List<Eligibility_Detail__c> incomeEligDetails = new List<Eligibility_Detail__c>();
    static Map<String,Set<Id>> zipCriteriaMap = new Map<String,Set<Id>>();
    static Map<Id,List<Id>> existingCareProgramsOnApplicationMap = new Map<Id,List<Id>>();
    static Map<Id,List<Suggested_Care_Program__c>> existingSuggestedProgramsMap = new Map<Id,List<Suggested_Care_Program__c>>();
    static List<Suggested_Care_Program__c> suggestedCareProgramsToInsert = new List<Suggested_Care_Program__c>();
    static List<Id> suggestedCareProgramsToDelete = new List<Id>();
    
    /*******************************************************************************************************
    * @description Calculates Suggested Care Programs for Applications
    * @param applicationIds List of Application Ids
    * @return Map with key Application Id and value as list of Suggested Care Program Ids
    ********************************************************************************************************/
    public static Map<Id,List<Id>> calculateSuggestedPrograms(List<Id> applicationIds) {
        
        applications = [SELECT Id,Application_Type__c,Patient__r.PersonMailingPostalCode,Care_Program__c,
                        Patient__r.PersonMailingStateCode,
                        Patient__r.PersonContact.MailingCountryCode,
                        Patient__r.Payment_Date__c,
                        Applicant_has_no_award_in_last_12months__c,
                        Physician_confirms_patient_inactive_tre__c,
                        Is_patient_in_active_treatment__c,
                        Applicant_resides_US_Territory__c,
                        Poverty_Level__c,
                        Total_annual_Household_Income__c,No_of_People_in_the_Household__c FROM Application__c 
                        WHERE Id IN :applicationIds AND Application_Status__c != :TAP_Constants.APPLICATION_STATUS_APPROVED];
        if(applications.size() > 0) {
            calculateSuggestedPrograms();
        }
        
        return careProgramRelatedToApplicationMap;
    }
    
    /*******************************************************************************************************
    * @description Calculates Suggested Care Programs for Applications related to Accounts
    * @param accounts List of Accounts
    * @return Map with key Application Id and value as list of Suggested Care Program Ids
    ********************************************************************************************************/
    public static Map<Id,List<Id>> calculateSuggestedPrograms(List<Account> accounts) {
        
        applications = [SELECT Id,Application_Type__c,Patient__r.PersonMailingPostalCode,Care_Program__c,
                        Patient__r.PersonMailingStateCode,
                        Patient__r.PersonContact.MailingCountryCode,
                        Patient__r.Payment_Date__c,
                        Applicant_has_no_award_in_last_12months__c,
                        Physician_confirms_patient_inactive_tre__c,
                        Is_patient_in_active_treatment__c,
                        Applicant_resides_US_Territory__c,
                        Poverty_Level__c,
                        Total_annual_Household_Income__c,No_of_People_in_the_Household__c FROM Application__c 
                        WHERE Patient__c IN :accounts 
                        AND Application_Status__c IN (:TAP_Constants.APPLICATION_STATUS_NEW,
                                                      :TAP_Constants.APPLICATION_STATUS_IN_REVIEW,
                                                      :TAP_Constants.APPLICATION_STATUS_NEED_MORE_INFO,
                                                      :TAP_Constants.APPLICATION_STATUS_DEFERRED)];
        if(applications.size() > 0) {
            calculateSuggestedPrograms();
        }
        
        return careProgramRelatedToApplicationMap;
    }
    
    /*******************************************************************************************************
    * @description Delete Suggested Care Programs for Applications
    * @param applicationIds List of Application Ids
    * @return List with  Application
    ********************************************************************************************************/
    
    public static void deleteSuggestedCarePrograms(List<Application__c> applications) {
        
        List<Suggested_Care_Program__c> suggestedCarePrograms = [SELECT Id from Suggested_Care_Program__c 
                                                                 WHERE Application__c IN :applications];
        Database.delete(suggestedCarePrograms,false);
    }
    
    /*******************************************************************************************************
    * @description check whether Suggested Care Programs are available for Applications
    * @param applicationId which is  Application Id and  careProgramId which is careProgram Id
    * @return Boolean with  YES - suggested care program is available , NO -  suggested care program not available
    ********************************************************************************************************/
    
    public static Boolean isSelectedCareProgramSuggested(Id applicationId, Id careProgramId) {
        
        List<Suggested_Care_Program__c> suggestedCarePrograms = [SELECT Id from Suggested_Care_Program__c 
                                                                 WHERE Application__c = :applicationId AND Care_Program__c = :careProgramId];
        return suggestedCarePrograms.size() > 0;
    }
    
    private static void calculateSuggestedPrograms() {
        for(Application__c application : applications) {
            if (applicationTypeMap.get(application.Application_Type__c) == null) {
                applicationTypeMap.put(application.Application_Type__c,new List<Application__c>());
            }
            applicationTypeMap.get(application.Application_Type__c).add(application);
        }
        
        getCareProgramsForApplicationTypes(applicationTypeMap.keySet());
        
        getExistingSuggestedCarePrograms(applications);
        
        calculateCarePrograms();
    }
    
    private static void calculateCarePrograms() {
        
        for(Application__c application : applications) {
            List<CareProgram> carePrograms = careProgramTypeMap.get(application.Application_Type__c);
            if(carePrograms != null) {
                for(CareProgram careProgram : carePrograms) {
                    if(hasMatchingCriterias(application,careProgram.CProgram_Eligibility_Rules)) {
                        //check if suggested program for this care program and application exists. If not create one
                        createSuggestedProgram(application,careProgram);
                    } else {
                        // delete if present
                        removeSuggestedProgramIfPresent(application,careProgram);
                    }
                }
            }
        }
        
        
        Database.insert(suggestedCareProgramsToInsert,false);
        Database.delete(suggestedCareProgramsToDelete,false);
    }
    
    static Boolean hasMatchingCriterias(Application__c application,List<CareProgramEligibilityRule> rules) {
        //if (eligibilityCriteria.size() > 0)
        //p = eligibilityCriteria[0].Id;                                                          
        if(rules != null) {
            for(CareProgramEligibilityRule rule : rules) {
                EnrollmentEligibilityCriteria criteria = rule.EligibilityCriteria;
                List<Eligibility_Detail__c> eligibilityDetails = criteriaDetailsMap.get(criteria.Id);
                if(!hasMatchingCriteria(application,criteria,eligibilityDetails)) {
                    return false;
                }
            }
        }
        return true;
        
    }
    
    static Boolean hasMatchingCriteria(Application__c application,EnrollmentEligibilityCriteria criteria,List<Eligibility_Detail__c> eligibilityDetails) {
        Boolean isMatching = false;
        if(criteria.Criteria_Type__c == TAP_Constants.ELIGIBILITY_CRITERIA_ZIP_BASED) {
            isMatching = hasMatchingZIPCriteria(application,criteria);
        } else if(criteria.Criteria_Type__c == TAP_Constants.ELIGIBILITY_CRITERIA_INCOME_BASED) {
            isMatching = hasMatchingIncomeCriteria(application,criteria,incomeEligDetails);
        } else if(criteria.Criteria_Type__c == TAP_Constants.ELIGIBILITY_CRITERIA_USA_RESIDENT) {
            isMatching = hasMatchingUSResidentCriteria(application,criteria,eligibilityDetails);
        } else if(criteria.Criteria_Type__c == TAP_Constants.ELIGIBILITY_CRITERIA_NO_AWARD ) {
            isMatching = hasMatchingNoAwardCriteria(application,criteria,eligibilityDetails);
        } else if(criteria.Criteria_Type__c == TAP_Constants.ELIGIBILITY_CRITERIA_ACTIVE_TREATMENT) {
            isMatching = hasMatchingActiveTreatmentCriteria(application,criteria,eligibilityDetails);
        }
        return isMatching;
    }
    
    static Boolean hasMatchingZIPCriteria(Application__c application,EnrollmentEligibilityCriteria criteria) {
        
        if(application.Patient__r != null && zipCriteriaMap.get(application.Patient__r.PersonMailingPostalCode) != null) {
            return zipCriteriaMap.get(application.Patient__r.PersonMailingPostalCode).contains(criteria.Id);
        }
        return false;
    }
    
    static Boolean hasMatchingIncomeCriteria(Application__c application,EnrollmentEligibilityCriteria criteria,List<Eligibility_Detail__c> eligibilityDetails) {
        
        return application.Poverty_Level__c != null && criteria.Percent_Of_Poverty_Guideline__c >= application.Poverty_Level__c;
        
    }
    
    static Boolean hasMatchingUSResidentCriteria(Application__c application,EnrollmentEligibilityCriteria criteria,List<Eligibility_Detail__c> eligibilityDetails) {
        
        return application.Patient__r.PersonContact.MailingCountryCode == TAP_Constants.COUNTRY_CODE_US;
    }
    
    static Boolean hasMatchingNoAwardCriteria(Application__c application,EnrollmentEligibilityCriteria criteria,List<Eligibility_Detail__c> eligibilityDetails) {
        
        Date paymentdate = Date.valueof(application.Patient__r.Payment_Date__c);
        Date today = Date.valueof(System.today());
        return paymentdate != null ? (paymentdate.monthsBetween(today) >= criteria.No_Income_in_Last_N_months__c) : true;
        
        
    }
    
    static Boolean hasMatchingActiveTreatmentCriteria(Application__c application,EnrollmentEligibilityCriteria criteria,List<Eligibility_Detail__c> eligibilityDetails) {
        
        return application.Is_patient_in_active_treatment__c == TAP_Constants.YES;
    }
    
    static void createSuggestedProgram(Application__c application,CareProgram careProgram) {
        
        if (careProgramRelatedToApplicationmap.get(application.Id) == null) {
            careProgramRelatedToApplicationmap.put(application.Id,new List<Id>());
        }
        careProgramRelatedToApplicationmap.get(application.Id).add(careProgram.id);
        if(existingCareProgramsOnApplicationMap.get(application.Id) == null || !existingCareProgramsOnApplicationMap.get(application.Id).contains(careProgram.Id)) {
            
            suggestedCareProgramsToInsert.add(populateSuggestedCareProgram(application,careProgram));
        }
    }
    
    static void removeSuggestedProgramIfPresent(Application__c application,CareProgram careProgram) {
        
        if(existingCareProgramsOnApplicationMap.get(application.Id) != null && existingCareProgramsOnApplicationMap.get(application.Id).contains(careProgram.Id)) {
            for(Suggested_Care_Program__c suggestedCP : existingSuggestedProgramsMap.get(application.Id)) {
                if(suggestedCP.Care_Program__c == careProgram.Id) {
                    suggestedCareProgramsToDelete.add(suggestedCP.Id);
                }
            }
        }
    }
    
    static Suggested_Care_Program__c populateSuggestedCareProgram(Application__c application,CareProgram careProgram) {
        
        Suggested_Care_Program__c suggestedCareProgram = new Suggested_Care_Program__c();
        suggestedCareProgram.Care_Program__c = careProgram.Id;
        suggestedCareProgram.Application__c = application.Id;
        suggestedCareProgram.Name = careProgram.name;
        return suggestedCareProgram;
    }
    
    static void getCareProgramsForApplicationTypes(Set<String> types) {
        
        List<CareProgram> carePrograms = [SELECT id,name,Care_Program_Type__c,
                                          (SELECT id,name,EligibilityCriteria.id,EligibilityCriteria.Criteria_Type__c,
                                           EligibilityCriteria.Percent_Of_Poverty_Guideline__c,EligibilityCriteria.No_Income_in_Last_N_months__c,EligibilityCriteria.Status 
                                           FROM CProgram_Eligibility_Rules) FROM CareProgram 
                                          WHERE Status = :TAP_Constants.CARE_PROGRAM_STATUS_ACTIVE AND Care_Program_Type__c IN :types];
        List<Id> eligCriterias = new List<Id>();
        for(CareProgram careProgram :carePrograms) {
            
            if(careProgram.CProgram_Eligibility_Rules != null) {
                if (careProgramTypeMap.get(careProgram.Care_Program_Type__c) == null) {
                    careProgramTypeMap.put(careProgram.Care_Program_Type__c,new List<CareProgram>());
                }
                careProgramTypeMap.get(careProgram.Care_Program_Type__c).add(careProgram);
                for(CareProgramEligibilityRule rule : careProgram.CProgram_Eligibility_Rules) {
                    eligCriterias.add(rule.EligibilityCriteria.id);
                }
            } else {
                if (careProgramTypeNoCriteriaMap.get(careProgram.Care_Program_Type__c) == null) {
                    careProgramTypeNoCriteriaMap.put(careProgram.Care_Program_Type__c,new List<CareProgram>());
                }
                careProgramTypeNoCriteriaMap.get(careProgram.Care_Program_Type__c).add(careProgram);
            }
        }
        
        getEligibilityDetailsForCriterias(eligCriterias);
    }
    
    public static void getEligibilityDetailsForCriterias(List<Id> criteriaIds) {
        
        List<Eligibility_Detail__c> eligibilityDetails = [SELECT Id, ZIP_Code__c,Eligibility_Criteria__c,RecordType.DeveloperName,State__c,
                                                          Per_Person_Incremental_Amount__c,Single_Person_Income_Limit__c
                                                          FROM Eligibility_Detail__c 
                                                          WHERE Eligibility_Criteria__c IN :criteriaIds 
                                                          OR (RecordType.DeveloperName = :TAP_Constants.ELIGIBILITY_DETAIL_INCOME_RECORD_TYPE AND is_Active__c = true)];
        
        for(Eligibility_Detail__c eligibilityDetail : eligibilityDetails) {
            if (criteriaDetailsMap.get(eligibilityDetail.Eligibility_Criteria__c) == null) {
                criteriaDetailsMap.put(eligibilityDetail.Eligibility_Criteria__c,new List<Eligibility_Detail__c>());
            }
            criteriaDetailsMap.get(eligibilityDetail.Eligibility_Criteria__c).add(eligibilityDetail);
            if(eligibilityDetail.RecordType.DeveloperName == TAP_Constants.ELIGIBILITY_DETAIL_INCOME_RECORD_TYPE) {
                incomeEligDetails.add(eligibilityDetail);
            }
            if (zipCriteriaMap.get(eligibilityDetail.ZIP_Code__c) == null) {
                zipCriteriaMap.put(eligibilityDetail.ZIP_Code__c, new Set<Id>());
            }
            zipCriteriaMap.get(eligibilityDetail.ZIP_Code__c).add(eligibilityDetail.Eligibility_Criteria__c);
        }
    }
    
    static void getExistingSuggestedCarePrograms(List<Application__c> applications) {
        
        List<Suggested_Care_Program__c> existingSuggestedPrograms = [SELECT id,Application__c,Care_Program__c 
                                                                     FROM Suggested_Care_Program__c 
                                                                     WHERE Application__c IN :applications];
        for(Suggested_Care_Program__c suggProgs : existingSuggestedPrograms) {
            if (existingCareProgramsOnApplicationMap.get(suggProgs.Application__c) == null) {
                existingCareProgramsOnApplicationMap.put(suggProgs.Application__c, new List<Id>());
            }
            existingCareProgramsOnApplicationMap.get(suggProgs.Application__c).add(suggProgs.Care_Program__c);
            if (existingSuggestedProgramsMap.get(suggProgs.Application__c) == null) {
                existingSuggestedProgramsMap.put(suggProgs.Application__c, new List<Suggested_Care_Program__c>());
            }
            existingSuggestedProgramsMap.get(suggProgs.Application__c).add(suggProgs);
        }
    }
}