unpackaged/main/default/objects/Account/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Using Trigger, Update Payment Date from Payment obj.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/PeopleSoft_Id__c.field-meta.xml
<CustomField>
    <fullName>PeopleSoft_Id__c</fullName>
    <description>Map this field with People Soft(Vendor) Id for Import/Export data.</description>
    <externalId>true</externalId>
    <inlineHelpText>PeopleSoft Vendor Id</inlineHelpText>
    <label>PeopleSoft Id (Vendor)</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track Health Insurance Information for a Patient</description>
    <label>Application</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>The Status from the Application Submitted/New to till Approved or Rejected.</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Need More Information</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Payment Error</fullName>
                <isActive>false</isActive>
                <label>Payment Error</label>
            </value>
            <value>
                <fullName>Payment Processing</fullName>
                <isActive>false</isActive>
                <label>Payment Processing</label>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Care_Program__c.field-meta.xml
<CustomField>
    <fullName>Care_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Care Program, Populate Name of the Care Program for the Application.</description>
    <label>Care Program</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CareProgram.Care_Program_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.Application_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>CareProgram.Status</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Applications (Care Program)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup with Account, to Populate Patient or Applicant Name.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Using Trigger, Update Payment Date from Payment obj.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <description>Using Trigger, Update Payment Status from Payment obj.</description>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payment Processing</fullName>
            </value>
            <value>
                <fullName>Payment Error</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/PeopleSoft_Id__c.field-meta.xml
<CustomField>
    <fullName>PeopleSoft_Id__c</fullName>
    <description>Map this field with People Soft(Vendor) Id while Import/Export data.</description>
    <externalId>true</externalId>
    <label>PeopleSoft Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CareProgram/fields/Payout_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payout_Amount__c</fullName>
    <description>Payout Amount for this Care Program.</description>
    <label>Payout Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>this Object is used to track Payment Information for Patient/Applicant.</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup with Account to Populate Name of the Patient/Applicant.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup with Application, to Populate Application Id.</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Care_Program__c.field-meta.xml
<CustomField>
    <fullName>Care_Program__c</fullName>
    <description>Populate Care Program Name from Care Program.</description>
    <label>Care Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Application Payment Date.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <description>Status of Application Payment. default the Payment Status is Pending.</description>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payment Processing</fullName>
            </value>
            <value>
                <fullName>Payment Error</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Payout_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payout_Amount__c</fullName>
    <description>Lookup with  Care Program, to Populate Payout Amount from Care Program.</description>
    <formula>Care_Program__r.Payout_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payout Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/PeopleSoft_Id__c.field-meta.xml
<CustomField>
    <fullName>PeopleSoft_Id__c</fullName>
    <description>Map with People Soft, while import/export data.</description>
    <externalId>true</externalId>
    <inlineHelpText>PeopleSoft Voucher ID</inlineHelpText>
    <label>PeopleSoft Id (Voucher)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Supplier_ID__c.field-meta.xml
<CustomField>
    <fullName>Supplier_ID__c</fullName>
    <label>Supplier ID</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Contact.AccountId</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/TAP_PaymentTrigger_Handler_Test.cls
@isTest
public class TAP_PaymentTrigger_Handler_Test {
    @testSetup static void setup() {
        
        // Create common test User
        List<User> testUser = TAP_TestDataFactory.createUser();
        
        //Create common test accounts
        List<Account> testaccounts = TAP_TestDataFactory.createAccount(2,'Account'); 
        
        // Create common test Care Programs
        List<CareProgram> testCarePrograms = TAP_TestDataFactory.createCareProgram(2,'careProgram');
        
        // Create common test applications
        List<Application__c> testapplications = TAP_TestDataFactory.createApplication(1,testaccounts[0].Id,testCarePrograms[0].Id);   
    }
    
    @isTest static void creatPaymentTest(){
        // List<User> userList =[Select Id,Name FROM User WHERE Alias =:TAP_Constants.MISSION_ALIAS];
        //system.debug('@@user'+userList);
        test.startTest();
        //SOQL to get Account
        Account account = [SELECT Id,Payment_Date__c FROM Account WHERE LastName ='Account0'];
        
        //SOQL to get Care Program
        List<CareProgram> careProgram = [SELECT ID,Payout_Amount__c FROM CareProgram WHERE Name='careProgram0'];
        
        //SOQL to get Application
        Application__c application = [SELECT ID, Application_Status__c,Care_Program__c FROM Application__c WHERE Patient__c =:account.Id];
        application.Application_Status__c = TAP_Constants.APPLICATION_STATUS_APPROVED;
        update application;
        
        List<Payment__c> payments = [Select Id,Application__c,Account__c,Supplier_ID__c,Payment_Date__c,Payment_Status__c From Payment__c where Application__c =:application.id];
        System.assert(payments.size()>0);
        system.assertEquals(account.id, payments[0].Account__c);
        
        Payment__c payment  = [SELECT Id,Application__c,Supplier_ID__c,Payment_Date__c,Payment_Status__c From Payment__c where Id =:payments[0].id];
        payment.Payment_Date__c = date.newInstance(2020, 07, 22);
        payment.Supplier_ID__c = TAP_Constants.PAYMENT_SUPPLIER_ID;
        payment.Payment_Status__c =TAP_Constants.PAYMENT_STATUS_PAID;
        update payment;
        
        Account accounts = [SELECT Id,Payment_Date__c,PeopleSoft_Id__c FROM Account WHERE LastName ='Account0' LImit 1];
        system.assertEquals(payment.Supplier_ID__c, accounts.PeopleSoft_Id__c);
        test.stopTest();
    }
}