unpackaged/main/default/objects/Account/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Using Trigger, Update Payment Date from Payment obj.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track Health Insurance Information for a Patient</description>
    <label>Application</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Care_Program__c.field-meta.xml
<CustomField>
    <fullName>Care_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Care Program, Populate Name of the Care Program for the Application.</description>
    <label>Care Program</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CareProgram.Care_Program_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.Application_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>CareProgram.Status</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Applications (Care Program)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup with Account, to Populate Patient or Applicant Name.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Using Trigger, Update Payment Date from Payment obj.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Status_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Change_Date__c</fullName>
    <label>Status Change Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/Eligibility_Detail__c.object-meta.xml
<CustomObject>
    <description>This objects holds data details of Care Program eligibility criteria.</description>
    <label>Eligibility Detail</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Eligibility Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligibility Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/Care_Program__c.field-meta.xml
<CustomField>
    <fullName>Care_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Eligibility Details</relationshipLabel>
    <relationshipName>Eligibility_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Suggested_Care_Program__c/Suggested_Care_Program__c.object-meta.xml
<CustomObject>
    <label>Suggested Care Program</label>
    <nameField>
        <label>Suggested Programs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suggested Care Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Suggested_Care_Program__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>Suggested_Program</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Suggested_Care_Program__c/fields/Care_Program__c.field-meta.xml
<CustomField>
    <fullName>Care_Program__c</fullName>
    <label>Care Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Suggested Care Programs</relationshipLabel>
    <relationshipName>Suggested_Program</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/TAP_SuggestedProgramHelper_Test.cls
@isTest
public class TAP_SuggestedProgramHelper_Test {
    @testSetup static void setup() {
        
        //Create common test accounts
        List<Account> testaccounts = TAP_TestDataFactory.createAccount(2,'Account'); 
        
        // Create common test care Program
        List<CareProgram> testCarePrograms = TAP_TestDataFactory.createCareProgram(3,'careProgram');

        // Create common test application
        List<Application__c> testapplication1 = TAP_TestDataFactory.createApplication(1,testaccounts[0].Id,testCarePrograms[0].Id);
        
        // Create common test application
        List<Application__c> testapplication2 = TAP_TestDataFactory.createApplication(1,testaccounts[0].Id,testCarePrograms[1].Id);
        
        // Create common test application
        List<Application__c> testapplication3 = TAP_TestDataFactory.createApplication(1,testaccounts[0].Id,testCarePrograms[2].Id);
        
        // Create common test EnrollmentEligibilityCriteria Income Based
        List<EnrollmentEligibilityCriteria> enrollmentEligibilityCriteriaIncomeBased = TAP_TestDataFactory.createEnrollmentEligibilityCriteria(1,'Income','TestIncomeBasedCriteria');
        
        // Create common test EnrollmentEligibilityCriteria Zip Based
        List<EnrollmentEligibilityCriteria> enrollmentEligibilityCriteriaZipBased = TAP_TestDataFactory.createEnrollmentEligibilityCriteria(1,'Zip','TestZipBasedCriteria');
        
        // Create common test EnrollmentEligibilityCriteria Income Based
        List<EnrollmentEligibilityCriteria> enrollmentEligibilityCriteriasUSAResidentBased = TAP_TestDataFactory.createEnrollmentEligibilityCriteria(1,'USA Resident','TestUSAResidentBasedCriteria');
        
        // Create common test CareProgramEligibilityRule With Income Based Criteria
        List<CareProgramEligibilityRule> careProgramRuleWithIncomeBasedCriteria = TAP_TestDataFactory.careProgramEligibilityRule(1,enrollmentEligibilityCriteriaIncomeBased[0].Id,testCarePrograms[0].Id);
        
        // Create common test CareProgramEligibilityRule With Zip Based Criteria
        List<CareProgramEligibilityRule> careProgramRuleWithZipBasedCriteria = TAP_TestDataFactory.careProgramEligibilityRule(1,enrollmentEligibilityCriteriaZipBased[0].Id,testCarePrograms[1].Id);
        
        // Create common test CareProgramEligibilityRule With USA Resident Based Criteria
        List<CareProgramEligibilityRule> careProgramRuleWithUSAResidentBasedCriteria = TAP_TestDataFactory.careProgramEligibilityRule(1,enrollmentEligibilityCriteriasUSAResidentBased[0].Id,testCarePrograms[2].Id);
        
        // Create common test CareProgramEligibilityRule With Income Based Criteria
        List<Eligibility_Detail__c> eligibilityDetailWithZipBasedCriteria =TAP_TestDataFactory.createEligibilityDetail('Income',enrollmentEligibilityCriteriaIncomeBased[0].Id,'NY','10001');
        
        // Create common test CareProgramEligibilityRule With Income Based Criteria
        List<Eligibility_Detail__c> eligibilityDetailIncomeBasedCriteria =TAP_TestDataFactory.createEligibilityDetail('Location',enrollmentEligibilityCriteriaZipBased[0].Id,'TX','73301');
        
        // Create common test CareProgramEligibilityRule With Income Based Criteria
        List<Eligibility_Detail__c> eligibilityDetailUSAResidentBasedCriteria =TAP_TestDataFactory.createEligibilityDetail('Income',enrollmentEligibilityCriteriasUSAResidentBased[0].Id,'CA','90002');   
    }
    
    @isTest 
    static void calculateSuggestedProgramsTest(){
        
        //SOQL to get Account
        List<Account> accounts = [SELECT Id,Payment_Date__c,PersonEmail FROM Account WHERE LastName ='Account0'];
        
        //SOQL to get Care Program
        List<CareProgram> careProgram = [Select Id FROM CareProgram WHERE NAME = 'careProgram0'];
        
        //SOQL to get Application
        List<Id> applicationId = new List<Id>();
        List<Application__c> applications = [SELECT ID,Status_Change_Date__c FROM Application__c WHERE Patient__c =:accounts[0].id];
        applicationId.add(applications[0].Id);
        
        test.startTest();
        Map<Id,List<Id>> mapOfCareProgramAndApplicaion = TAP_SuggestedProgramHelper.calculateSuggestedPrograms(applicationId);
        test.stopTest();
        
        List<Application__c> applicationList = [Select Id,Care_Program__c From Application__c where Id=:mapOfCareProgramAndApplicaion.Keyset()];
        system.assertEquals(1,mapOfCareProgramAndApplicaion.get(applicationId[0]).size());   
    }
    
    @isTest 
    static void suggestedProgramsTest(){
        //SOQL to get Account
        List<Account> accounts = [SELECT Id,Payment_Date__c,PersonEmail FROM Account WHERE LastName ='Account0'];
        
        //SOQL to get Applications  
        List<Application__c> applications = [SELECT ID,Status_Change_Date__c,Care_Program__c FROM Application__c WHERE Patient__c =:accounts[0].id];
 
        test.startTest();
        Map<Id,List<Id>> mapOfCareProgramAndApplicaion = TAP_SuggestedProgramHelper.calculateSuggestedPrograms(accounts);
        test.stopTest();
        
        List<Id> careProgramIds = new List<Id>();
        careProgramIds.addAll(mapOfCareProgramAndApplicaion.get(applications[0].id));
        
        //Asserts to check Care Programs related to application
        system.assertEquals(1,careProgramIds.size()); 
    }
    
    @isTest 
    static void deleteSuggestedCarePrograms(){
        
        //SOQL to get Account
        List<Account> accounts = [SELECT Id,Payment_Date__c,PersonEmail FROM Account WHERE LastName ='Account0'];
        
        //SOQL to get Applications
        List<Application__c> applications = [SELECT ID,Status_Change_Date__c FROM Application__c WHERE Patient__c =:accounts[0].id];
        
        test.startTest();
        TAP_SuggestedProgramHelper.deleteSuggestedCarePrograms(applications);
        test.stopTest();
        
        //List for suggested care Programs
        List<Suggested_Care_Program__c> listOfDeletedSuggestedCareProgram = [SELECT Id,Name from Suggested_Care_Program__c 
                                                                             WHERE Application__c IN :applications];
        //Asserts for checking suggested care Programs is null
        system.assertEquals(0,listOfDeletedSuggestedCareProgram.size());  
    }
    
    @isTest 
    static void isSelectedCareProgramSuggestedTest(){
        
        //SOQL to get Account
        List<Account> accounts = [SELECT Id,Payment_Date__c,PersonEmail FROM Account WHERE LastName ='Account0'];
        
        //SOQL to get Applications
        List<Application__c> applications = [SELECT ID,Status_Change_Date__c FROM Application__c WHERE Patient__c =:accounts[0].id];
        
        //SOQL to get Care Programs
        List<CareProgram> careProgram = [Select Id FROM CareProgram WHERE NAME = 'careProgram0'];
        
        test.startTest();
        Boolean iscareProgramInSuuggested = TAP_SuggestedProgramHelper.isSelectedCareProgramSuggested(applications[0].Id,careProgram[0].id);
        test.stopTest();
        system.assertEquals(true, iscareProgramInSuuggested);         
    }  
}