unpackaged/main/default/objects/Account/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Using Trigger, Update Payment Date from Payment obj.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track Health Insurance Information for a Patient</description>
    <label>Application</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/No_of_People_in_the_Household__c.field-meta.xml
<CustomField>
    <fullName>No_of_People_in_the_Household__c</fullName>
    <description>Number of People in the Patient/Applicant House.</description>
    <label>No. Of People In The Household</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup with Account, to Populate Patient or Applicant Name.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Using Trigger, Update Payment Date from Payment obj.</description>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Poverty_Level__c.field-meta.xml
<CustomField>
    <fullName>Poverty_Level__c</fullName>
    <description>This field get Auto Calculated based on Financial Information.</description>
    <label>Poverty Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Status_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Change_Date__c</fullName>
    <label>Status Change Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Total_annual_Household_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_annual_Household_Income__c</fullName>
    <description>Combined gross income of all members of a household.</description>
    <label>Total Annual Household Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/Eligibility_Detail__c.object-meta.xml
<CustomObject>
    <description>This objects holds data details of Care Program eligibility criteria.</description>
    <label>Eligibility Detail</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Eligibility Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligibility Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/Eligibility_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Criteria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Eligibility Criteria</label>
    <referenceTo>EnrollmentEligibilityCriteria</referenceTo>
    <relationshipLabel>Eligibility Details</relationshipLabel>
    <relationshipName>Eligibility_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/Per_Person_Incremental_Amount__c.field-meta.xml
<CustomField>
    <fullName>Per_Person_Incremental_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Per Person Incremental Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/Single_Person_Income_Limit__c.field-meta.xml
<CustomField>
    <fullName>Single_Person_Income_Limit__c</fullName>
    <label>Single Person Income Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/TAP_CareProgram_Helper_Test.cls
@isTest
public class TAP_CareProgram_Helper_Test {
    @testSetup static void setup() {
        
        //List<User> createUser = TAP_TestDataFactory.createUser();
        
        //Create common test accounts
        List<Account> testaccounts = TAP_TestDataFactory.createAccount(2,'Account'); 
        
        // Create common test care Program
        List<CareProgram> testCarePrograms = TAP_TestDataFactory.createCareProgram(2,'careProgram');
        
        // Create Care Program With Criteria and details
        //List<CareProgram> careProgramWithCriteria = TAP_TestDataFactory.createCareProgramWithCriteriaDetails();
        List<CareProgram> careProgramWithCriteria = TAP_TestDataFactory.createCareProgram(2,'careProgram');
        
        // Create common test application
        List<Application__c> testapplications = TAP_TestDataFactory.createApplication(1,testaccounts[0].Id,testCarePrograms[0].Id);
        
        // Create common test EnrollmentEligibilityCriteria
        List<EnrollmentEligibilityCriteria> enrollmentEligibilityCriterias = TAP_TestDataFactory.createEnrollmentEligibilityCriteria(1,'Income','TestIncomeCriteria');
        
        // Create common test CareProgramEligibilityRule
        List<CareProgramEligibilityRule> careProgramRules = TAP_TestDataFactory.careProgramEligibilityRule(1,enrollmentEligibilityCriterias[0].Id,testCarePrograms[0].Id);
        
        // Create common test CareProgramEligibilityRule
        List<Eligibility_Detail__c> eligibilityDetails =TAP_TestDataFactory.createEligibilityDetail('Income',enrollmentEligibilityCriterias[0].Id,'NJ','07001'); 
        
    }
    
    @isTest static void calculatePovertyLevelForApplicationTest(){
        //SOQL to get Account
        List<Account> accounts = [SELECT Id,Payment_Date__c,PersonEmail FROM Account WHERE  LastName = 'Account0'];
        
        //SOQL to get Care Program
        List<CareProgram> careProgram = [Select Id FROM CareProgram WHERE Name = 'careProgram0'];
        
        //SOQL to get Application
        Application__c application = [SELECT ID,Status_Change_Date__c,Total_annual_Household_Income__c,No_of_People_in_the_Household__c
                                      FROM Application__c WHERE Patient__c =:accounts[0].id];
        
        List<EnrollmentEligibilityCriteria> enrollmentEligibilityCriteria = [SELECT Id FROM EnrollmentEligibilityCriteria WHERE Name ='TestIncomeCriteria'];
        
        //SOQL to get ligibility_Detail__c
        List<Eligibility_Detail__c> eligibilityDetailsList = [SELECT Eligibility_Criteria__c,State__c,Per_Person_Incremental_Amount__c,Single_Person_Income_Limit__c
                                                               FROM Eligibility_Detail__c WHERE Eligibility_Criteria__c = :enrollmentEligibilityCriteria[0].Id];
        system.debug('@@eligibilityDetailsList'+eligibilityDetailsList);
        test.startTest();
        Integer povertLevel = TAP_CareProgram_Helper.calculatePovertyLevelForApplication( application);
        test.stopTest();
        system.debug('@@povertLevel'+povertLevel);
        
        
    }
    
     @isTest static void calculatePovertyLevelForApplicantTest(){
        //SOQL to get Account
        List<Account> accounts = [SELECT Id,Payment_Date__c,PersonEmail FROM Account WHERE LastName = 'Account0'];
        
        //SOQL to get Care Program
        List<CareProgram> careProgram = [Select Id FROM CareProgram WHERE Name = 'careProgram0'];
        
        //SOQL to get Application
        Application__c application = [SELECT ID,Status_Change_Date__c,Total_annual_Household_Income__c,No_of_People_in_the_Household__c
                                      FROM Application__c WHERE Patient__c =:accounts[0].id];
        
        List<EnrollmentEligibilityCriteria> enrollmentEligibilityCriteria = [SELECT Id FROM EnrollmentEligibilityCriteria WHERE Name ='TestIncomeCriteria'];
        
        //SOQL to get ligibility_Detail__c
        List<Eligibility_Detail__c> eligibilityDetailsList = [SELECT Eligibility_Criteria__c,State__c,Per_Person_Incremental_Amount__c,Single_Person_Income_Limit__c
                                                               FROM Eligibility_Detail__c WHERE Eligibility_Criteria__c = :enrollmentEligibilityCriteria[0].Id];
        //system.debug('@@eligibilityDetailsList'+eligibilityDetailsList);
        test.startTest();
        TAP_CareProgram_Helper.updatePovertyLevelForApplicant(accounts);
        test.stopTest();
         Application__c applications = [SELECT ID,Status_Change_Date__c,Poverty_Level__c,Total_annual_Household_Income__c,No_of_People_in_the_Household__c
                                      FROM Application__c WHERE Patient__c =:accounts[0].id];
        system.debug('@@application '+applications);
        
        
    }

}