unpackaged/main/default/objects/Account/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <label>Preferred Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track Health Insurance Information for a Patient</description>
    <label>Application</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>The Status from the Application Submitted/New to till Approved or Rejected.</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Need More Information</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Payment Error</fullName>
                <isActive>false</isActive>
                <label>Payment Error</label>
            </value>
            <value>
                <fullName>Payment Processing</fullName>
                <isActive>false</isActive>
                <label>Payment Processing</label>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup with Account, to Populate Patient or Applicant Name.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TAP_EmailUtility.cls
/****************************************************************************************************************************************************************
* @author IVL Dev
* @date  17-June-2020,
* @description class to send email based on application status.
****************************************************************************************************************************************************************/

public without sharing class TAP_EmailUtility {
    
    /**********************************************************************************************************************************************************
    * @description send email as per the status of Application and email send in English or Spanish languages depend upon Preferred Language of Patient
    * @param  List of emailRequests  of EmailRequest wrapper class
    ***********************************************************************************************************************************************************/
    
    @InvocableMethod
    public static void sendEmail(List<EmailRequest> emailRequests){
        Map<Id,String> applicationTemplateMap = new Map<Id,String>();
        List<String> templateNames = new List<String>();
        OrgWideEmailAddress ordWideId = [SELECT  Id  FROM OrgWideEmailAddress where Address='treatmentassistance@komen.org'];
        for(EmailRequest emailRequest: emailRequests) {
            applicationTemplateMap.put(emailRequest.appId, emailRequest.emailTemplateName);
            templateNames.add(emailRequest.emailTemplateName);
            templateNames.add(emailRequest.emailTemplateName + '_Spanish');
        }
        List<Application__c> applications = [Select Id,Application_Status__c,Patient__c,
                                             Patient__r.PersonEmail,Patient__r.Name,
                                             Patient__r.Preferred_Language__c,
                                             Patient__r.personContactId
                                             From application__c Where Id IN :applicationTemplateMap.keySet()];
        List<EmailTemplate> templates = [SELECT Id,DeveloperName,Body,HtmlValue from EmailTemplate WHERE DeveloperName IN :templateNames];
        Map<String,Id> templateMap = new Map<String,Id>();
        for(EmailTemplate template : templates) {
            templateMap.put(template.DeveloperName, template.Id);
        }
        Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage>();
        for(Application__c application: applications) {
            if(application.Patient__c != null && application.Patient__r.personContactId != null){
                Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                message.setTargetObjectId(application.Patient__r.personContactId);
                message.setSaveAsActivity(true);
                if(application.Patient__r.Preferred_Language__c == 'Spanish' 
                   && templateMap.get(applicationTemplateMap.get(application.Id) +'_Spanish') != null) {
                       message.setTemplateID(templateMap.get(applicationTemplateMap.get(application.Id) +'_Spanish'));
                   }else {
                       message.setTemplateID(templateMap.get(applicationTemplateMap.get(application.Id)));
                   }
                message.setWhatId(application.Id);
                
                message.setOrgWideEmailAddressId(ordWideId.Id);
                messages.add(message);
            }
            Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
        }
    }
    
    /*******************************************************************************************************
    * @description Wrapper class created for sending different parameter to class
    * @ (@invocableVariable) annotation to identify variables used by invocable methods in custom classes
    ********************************************************************************************************/
    
    public class EmailRequest {
        @InvocableVariable(Label = 'Application Id' Required = true)
        public String appId;
        
        @InvocableVariable(Label = 'Email Template Unique Name' Required = true)
        public String emailTemplateName;
    }
}