unpackaged/main/default/objects/Account/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <label>Preferred Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track Health Insurance Information for a Patient</description>
    <label>Application</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>The Status from the Application Submitted/New to till Approved or Rejected.</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Need More Information</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Payment Error</fullName>
                <isActive>false</isActive>
                <label>Payment Error</label>
            </value>
            <value>
                <fullName>Payment Processing</fullName>
                <isActive>false</isActive>
                <label>Payment Processing</label>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Hospital_Clinic__c.field-meta.xml
<CustomField>
    <fullName>Hospital_Clinic__c</fullName>
    <description>Name of the Hospital/Clinic.</description>
    <label>Hospital/Clinic</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Hospital_Clinic_Address__c.field-meta.xml
<CustomField>
    <fullName>Hospital_Clinic_Address__c</fullName>
    <description>Hospital Address(Street, Postal etc).</description>
    <label>Hospital/Clinic Street Address</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Hospital_Clinic_City__c.field-meta.xml
<CustomField>
    <fullName>Hospital_Clinic_City__c</fullName>
    <description>Hospital Address(City).</description>
    <label>Hospital/Clinic City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Hospital_Clinic_Phone__c.field-meta.xml
<CustomField>
    <fullName>Hospital_Clinic_Phone__c</fullName>
    <description>Hospital Phone Number.</description>
    <label>Hospital/Clinic Phone</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Hospital_Clinic_State__c.field-meta.xml
<CustomField>
    <fullName>Hospital_Clinic_State__c</fullName>
    <description>Hospital Address(State).</description>
    <label>Hospital/Clinic State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>Armed Forces Americas</fullName>
            </value>
            <value>
                <fullName>Armed Forces Pacific</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>New York</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Hospital_Clinic_Zip__c.field-meta.xml
<CustomField>
    <fullName>Hospital_Clinic_Zip__c</fullName>
    <description>Hospital Address (Zip Code).</description>
    <label>Hospital/Clinic Zip</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Is_patient_in_active_treatment__c.field-meta.xml
<CustomField>
    <fullName>Is_patient_in_active_treatment__c</fullName>
    <description>Is this Patient  in Active Treatment?</description>
    <label>Is Patient In Active Treatment?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Medical_Provider_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Medical_Provider_First_Name__c</fullName>
    <label>Medical Provider First Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Medical_Provider_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Medical_Provider_Last_Name__c</fullName>
    <label>Medical Provider Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/No_of_People_in_the_Household__c.field-meta.xml
<CustomField>
    <fullName>No_of_People_in_the_Household__c</fullName>
    <description>Number of People in the Patient/Applicant House.</description>
    <label>No. Of People In The Household</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup with Account, to Populate Patient or Applicant Name.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Relationship_to_Patient__c.field-meta.xml
<CustomField>
    <fullName>Relationship_to_Patient__c</fullName>
    <description>My Relationship to Patient?</description>
    <label>Relationship to Patient</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
                <default>true</default>
                <label>Self</label>
            </value>
            <value>
                <fullName>Parent_or_Guardian</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Social_Worker</fullName>
                <label>Social Worker</label>
            </value>
            <value>
                <fullName>Patient_Navigator</fullName>
                <label>Patient Navigator</label>
            </value>
            <value>
                <fullName>Healthcare Provider</fullName>
            </value>
            <value>
                <fullName>Other (please specify)</fullName>
            </value>
            <value>
                <fullName>Doctor</fullName>
                <isActive>false</isActive>
                <label>Doctor</label>
            </value>
            <value>
                <fullName>Nurse</fullName>
                <isActive>false</isActive>
                <label>Nurse</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Spouse or Partner</fullName>
                <isActive>false</isActive>
                <label>Spouse or Partner</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Signatory_Name__c.field-meta.xml
<CustomField>
    <fullName>Signatory_Name__c</fullName>
    <label>Signatory Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>Signed_Date__c</fullName>
    <description>The date on which the Medical Provider/Others Signed on.</description>
    <label>Signed Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Status_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Change_Date__c</fullName>
    <label>Status Change Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Total_annual_Household_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_annual_Household_Income__c</fullName>
    <description>Combined gross income of all members of a household.</description>
    <label>Total Annual Household Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/HealthCloudTestFactoryData.cls
@isTest
public class HealthCloudTestFactoryData {
    public Static void createAccountAndApplication(){
        Account account = new Account(FirstName='john',LastName='Smith',Race__pc='Asian',PersonBirthdate=system.today(),Preferred_Language__c ='English',
                                      Gender__pc='Male',Ethnicity__pc='Hispanic/LatinX',PersonEmail='abc@gmail.com');
        insert account;
        
        Application__c application = new Application__c(Patient__c =account.id,Total_annual_Household_Income__c =40000,No_of_People_in_the_Household__c=3,
                                                        Is_patient_in_active_treatment__c='yes',Medical_Provider_First_Name__c='Mark',  Medical_Provider_Last_Name__c='Waugh',
                                                        Hospital_Clinic__c='New Hospital',  Hospital_Clinic_Address__c='Oxford Lane',Hospital_Clinic_Phone__c='1258',
                                                        Hospital_Clinic_City__c='New York', Hospital_Clinic_State__c='New York',Hospital_Clinic_Zip__c='10001',
                                                        Signatory_Name__c='Adam',Signed_Date__c=system.today(),Relationship_to_Patient__c='Self',Application_Status__c='New',
                                                        Status_Change_Date__c= system.today());
        insert application;
    }  
}