unpackaged/main/default/objects/HealthCloudGA__EHRProcedure__c/fields/Procedure_Type__c.field-meta.xml
<CustomField>
    <fullName>Procedure_Type__c</fullName>
    <label>Procedure Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mammogram</fullName>
                <isActive>false</isActive>
            </value>
            <value>
                <fullName>Screening</fullName>
                <isActive>false</isActive>
            </value>
            <value>
                <fullName>Biopsy</fullName>
            </value>
            <value>
                <fullName>Vitals</fullName>
                <isActive>false</isActive>
            </value>
            <value>
                <fullName>Blood Draw</fullName>
                <isActive>false</isActive>
            </value>
            <value>
                <fullName>Xray</fullName>
                <isActive>false</isActive>
            </value>
            <value>
                <fullName>MRI</fullName>
                <isActive>false</isActive>
            </value>
            <value>
                <fullName>CT Scan</fullName>
                <isActive>false</isActive>
            </value>
            <value>
                <fullName>Screening/ Imaging</fullName>
                <label>CT Scan</label>
            </value>
            <value>
                <fullName>Diagnostic Imaging</fullName>
                <label>CT Scan</label>
            </value>
            <value>
                <fullName>Chemotherapy (Infusion)</fullName>
                <label>CT Scan</label>
            </value>
            <value>
                <fullName>Chemotherapy (Oral)</fullName>
                <label>CT Scan</label>
            </value>
            <value>
                <fullName>Hormone Therapy</fullName>
            </value>
            <value>
                <fullName>Immunotherapy</fullName>
            </value>
            <value>
                <fullName>Radiation</fullName>
            </value>
            <value>
                <fullName>Lumpectomy</fullName>
            </value>
            <value>
                <fullName>Mastectomy</fullName>
            </value>
            <value>
                <fullName>Palliative Care</fullName>
            </value>
            <value>
                <fullName>End of life care</fullName>
            </value>
            <value>
                <fullName>Other (please specify in notes)</fullName>
            </value>    
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/kHC_MyProceduresController.cls
/**
 * Created by vupneja on 10/2/2020.
 */

public with sharing class kHC_MyProceduresController {

    @AuraEnabled
    public static List<HealthCloudGA__EHRProcedure__c > getProcedures(Id currentLoggedAccount){

        List<HealthCloudGA__EHRProcedure__c> proceduresInfo = [
                SELECT  Id, HealthCloudGA__PerformedDateTime__c,Procedure_Type__c
                FROM HealthCloudGA__EHRProcedure__c
                WHERE HealthCloudGA__Account__c = :currentLoggedAccount
        ];

        return proceduresInfo;
    }

    @AuraEnabled
    public static List<HealthCloudGA__EHRProcedure__c > getEditProcedure(Id currentLoggedAccount, Id recordId) {
        List<HealthCloudGA__EHRProcedure__c> procedure = [
                SELECT HealthCloudGA__PerformedDateTime__c, Procedure_Type__c, HealthCloudGA__Account__c
                FROM HealthCloudGA__EHRProcedure__c
                WHERE HealthCloudGA__Account__c = :currentLoggedAccount AND Id = :recordId
                LIMIT 1
        ];

        if(procedure.isEmpty()) {
            throw new SObjectException('Unable to retrieve procedure');
        }
        return procedure;
    }

}