unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track Health Insurance Information for a Patient</description>
    <label>Application</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>The Status from the Application Submitted/New to till Approved or Rejected.</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Need More Information</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Payment Error</fullName>
                <isActive>false</isActive>
                <label>Payment Error</label>
            </value>
            <value>
                <fullName>Payment Processing</fullName>
                <isActive>false</isActive>
                <label>Payment Processing</label>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/No_of_People_in_the_Household__c.field-meta.xml
<CustomField>
    <fullName>No_of_People_in_the_Household__c</fullName>
    <description>Number of People in the Patient/Applicant House.</description>
    <label>No. Of People In The Household</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup with Account, to Populate Patient or Applicant Name.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Poverty_Level__c.field-meta.xml
<CustomField>
    <fullName>Poverty_Level__c</fullName>
    <description>This field get Auto Calculated based on Financial Information.</description>
    <label>Poverty Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Total_annual_Household_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_annual_Household_Income__c</fullName>
    <description>Combined gross income of all members of a household.</description>
    <label>Total Annual Household Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/Eligibility_Detail__c.object-meta.xml
<CustomObject>
    <description>This objects holds data details of Care Program eligibility criteria.</description>
    <label>Eligibility Detail</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Eligibility Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligibility Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/Per_Person_Incremental_Amount__c.field-meta.xml
<CustomField>
    <fullName>Per_Person_Incremental_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Per Person Incremental Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/Single_Person_Income_Limit__c.field-meta.xml
<CustomField>
    <fullName>Single_Person_Income_Limit__c</fullName>
    <label>Single Person Income Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/TAP_CareProgram_Helper.cls
/****************************************************************************************************************************************************************
* @author IVL Dev
* @date 18-July-2020
* @description Helper class for Care Program Object
****************************************************************************************************************************************************************/
public without sharing class TAP_CareProgram_Helper {

    /*******************************************************************************************************
    * @description Calculates poverty level based on Application information
    * @param application Application for which poverty level is to be calculated
	********************************************************************************************************/
    public static Integer calculatePovertyLevelForApplication(Application__c application) {
        Application__c app = new Application__c();
        if(application.id == null) {
            Account acc = [SELECT Id,PersonMailingStateCode FROM Account 
                           WHERE Id = :application.Patient__c];
            app.Patient__r = acc;
            
        } else {
            app = [SELECT Id,Patient__r.PersonMailingStateCode 
                   FROM Application__c 
                   WHERE Id = :application.Id];
        }
        
        app.Total_annual_Household_Income__c = application.Total_annual_Household_Income__c;
        app.No_of_People_in_the_Household__c = application.No_of_People_in_the_Household__c;
        List<Eligibility_Detail__c> incomeBasedEligibilityDetails = [SELECT Id, State__c,Per_Person_Incremental_Amount__c,Single_Person_Income_Limit__c
                                                                     FROM Eligibility_Detail__c 
                                                                     WHERE RecordType.DeveloperName = :TAP_Constants.ELIGIBILITY_DETAIL_INCOME_RECORD_TYPE 
                                                                     AND is_Active__c = true];
        return (Integer)getPovertyLevel(app,incomeBasedEligibilityDetails);
    }

    /*******************************************************************************************************
    * @description check poverty level value  for Patient, populated on Applications
    * @param accounts List of Account
	********************************************************************************************************/
    
    public static void updatePovertyLevelForApplicant(List<Account> accounts) {
        
        List<Application__c> applications = [SELECT Id,Patient__r.PersonMailingStateCode,
                                             Total_annual_Household_Income__c,No_of_People_in_the_Household__c 
                                             FROM Application__c 
                                             WHERE Patient__c IN :accounts 
                                             AND Application_Status__c IN (:TAP_Constants.APPLICATION_STATUS_NEW,
                                                                           :TAP_Constants.APPLICATION_STATUS_IN_REVIEW,
                                                                           :TAP_Constants.APPLICATION_STATUS_NEED_MORE_INFO,
                                                                           :TAP_Constants.APPLICATION_STATUS_DEFERRED)];
        List<Eligibility_Detail__c> incomeBasedEligibilityDetails = [SELECT Id, State__c,Per_Person_Incremental_Amount__c,Single_Person_Income_Limit__c
                                                                     FROM Eligibility_Detail__c 
                                                                     WHERE RecordType.DeveloperName = :TAP_Constants.ELIGIBILITY_DETAIL_INCOME_RECORD_TYPE 
                                                                     AND is_Active__c = true];
        for(Application__c app : applications) {
            app.Poverty_Level__c =  getPovertyLevel(app,incomeBasedEligibilityDetails);
        }
        Database.update(applications,false);
    }
    
    static Decimal getPovertyLevel(Application__c application,List<Eligibility_Detail__c> eligibilityDetails) {
        
        Decimal level = null;
        if(application.Patient__r != null && application.Total_annual_Household_Income__c != null && application.No_of_People_in_the_Household__c != null) {
            for(Eligibility_Detail__c detail : eligibilityDetails) {
                if(detail.State__c == application.Patient__r.PersonMailingStateCode) {
                    Decimal incomeLimit = getIncomeLimit(detail,application);
                    if(incomeLimit > 0) {
                        level = (application.Total_annual_Household_Income__c / incomeLimit) * 100;
                    }
                }
            }
        }
        
        return level;
    }

    private static Decimal getIncomeLimit(Eligibility_Detail__c detail, Application__c application) {
        Decimal incomeLimit = 0.0;
        if(detail.Per_Person_Incremental_Amount__c != null && detail.Single_Person_Income_Limit__c != null) {
            incomeLimit = detail.Single_Person_Income_Limit__c;
            if(application.No_of_People_in_the_Household__c > 1) {
                incomeLimit = ((application.No_of_People_in_the_Household__c-1) * detail.Per_Person_Incremental_Amount__c) + 
                    detail.Single_Person_Income_Limit__c;
            }
        }
        return incomeLimit;
    }

}