unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Knowledge__kav/recordTypes/Knowledge.recordType-meta.xml
<RecordType>
    <fullName>Knowledge</fullName>
    <active>true</active>
    <label>Knowledge</label>
</RecordType>

unpackaged/main/default/objects/Referral_Record__c/Referral_Record__c.object-meta.xml
<CustomObject>
    <label>Referral Record</label>
    <nameField>
        <displayFormat>RR-{00000}</displayFormat>
        <label>Referral Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Referral_Record__c/fields/Knowledge_Article_Referred__c.field-meta.xml
<CustomField>
    <fullName>Knowledge_Article_Referred__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Knowledge Article Referred</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Referral Records</relationshipLabel>
    <relationshipName>Referral_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/KHC_SyncReferralRecordsTest.cls
@isTest
public class KHC_SyncReferralRecordsTest {
    static String testingEmail = 'test@test.com';
    private static Id knowledgeRecordTypeId = Schema.SObjectType.Knowledge__kav.getRecordTypeInfosByName().get('Knowledge').getRecordTypeId();

    @TestSetup
    static void makeData(){
        Account a = MKH_TestDataFactory.createPersonAccount('First', 'Last', testingEmail, true);
        Contact con = [SELECT FirstName, LastName, Email FROM Contact WHERE AccountId = :a.Id];
        MKH_TestDataFactory.createCommunityUser( con, true, true);
        User commUsr = [SELECT Id, AccountId FROM User WHERE  email = :testingEmail LIMIT 1];

        Knowledge__kav newArticle = KHC_TestUtility.insertKnowledgeArticleVersion( 'xyz', 'Article', true, knowledgeRecordTypeId, false);
        newArticle = [SELECT Id,Title,KnowledgeArticleId FROM knowledge__kav WHERE id =: newArticle.Id];
        KbManagement.PublishingService.publishArticle( newArticle.KnowledgeArticleId, true );    

        Referral_Record__c refRecord = KHC_TestUtility.insertReferralRecord( commUsr.AccountId, newArticle.Id, true );
        String draftId = KbManagement.PublishingService.editOnlineArticle( newArticle.KnowledgeArticleId, true );
        KbManagement.PublishingService.publishArticle( newArticle.KnowledgeArticleId, true );    
    }

    @isTest
    static void syncReferralBatchTest(){
        List<Referral_Record__c> refRecords = [SELECT Id FROM Referral_Record__c WHERE Knowledge_Article_Referred__r.IsLatestVersion = FALSE];
        System.assertEquals( 1, refRecords.size(), '1 Referal record should have old article');
        Test.startTest();
        KHC_SyncReferralRecordsBatch syncReferralBatch = new KHC_SyncReferralRecordsBatch();
        Database.executeBatch( syncReferralBatch );
        Test.stopTest();
        refRecords = [SELECT Id FROM Referral_Record__c WHERE Knowledge_Article_Referred__r.IsLatestVersion = FALSE];
        System.assertEquals( 0, refRecords.size(), '0 Referal record should have old article');
    }
    @isTest
    static void syncReferralSchTest(){
        Test.startTest();
        KHC_SyncReferralRecordsSchedule syncReefRecordSchedule = new KHC_SyncReferralRecordsSchedule();
        String sch = '0 0 23 * * ?';
		system.schedule( 'Sync Ref Record', sch, syncReefRecordSchedule );
        Test.stopTest();
    }
}