unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Rhesus_Negative__c.field-meta.xml
<CustomField>
    <fullName>Rhesus_Negative__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, the Rh Factor is negative</description>
    <label>Rhesus Negative</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrMedicationStatement__c/HealthCloudGA__EhrMedicationStatement__c.object-meta.xml
<CustomObject>
    <description>A record of medication being taken by a patient, or that the medication has been given to a patient where the record is the result of a report from the patient or another clinician.</description>
    <label>EHR Medication Statement</label>
    <nameField>
        <displayFormat>Stat-{0}</displayFormat>
        <label>EHR Medication Statement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EHR Medication Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/HealthCloudGA__EhrMedicationStatement__c/fields/HealthCloudGA__MedicationName__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__MedicationName__c</fullName>
    <description>Common / Commercial name</description>
    <inlineHelpText>Common / Commercial name</inlineHelpText>
    <label>Medication Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrMedicationStatement__c/fields/Medication__c.field-meta.xml
<CustomField>
    <fullName>Medication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medication</label>
    <referenceTo>Medication__c</referenceTo>
    <relationshipLabel>Medication Statements</relationshipLabel>
    <relationshipName>Medication_Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Medication__c/Medication__c.object-meta.xml
<CustomObject>
    <description>Holds information about medications in use by Patients.  Intended to be populated either manually, or via integration with an API.</description>
    <label>Medication</label>
    <nameField>
        <label>Medication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Medication__c/fields/SetID__c.field-meta.xml
<CustomField>
    <fullName>SetID__c</fullName>
    <label>SetID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/kHC_MyHeathProfileControllerTest.cls
/**
 * Tests for kHC_MyHeathProfileController
 *
 * @author Sabrina Perardt, Traction on Demand
 *
 * @date 2020-09-02
 */
@IsTest
private class kHC_MyHeathProfileControllerTest {
    private static final String PERSON_EMAIL = 'peggy@komen.org';

    @TestSetup
    static void setup() {
        Account person =
                MKH_TestDataFactory.createPersonAccount('Peggy', 'Peggerson', PERSON_EMAIL, false);
        person.Organ_Donor__pc = true;

        Medication__c medication = new Medication__c(Name = 'Advil', SetID__c= '1234567890');

        insert new SObject[]{ person, medication};

        HealthCloudGA__EhrMedicationStatement__c myMed = new HealthCloudGA__EhrMedicationStatement__c(
                Medication__c = medication.Id,
                HealthCloudGA__MedicationName__c = 'Advil',
                HealthCloudGA__Account__c = person.Id

        );
        insert myMed;
    }

    @IsTest
    static void getMyHealthProfileTest() {// TODO write test for negative result
        Account myAccount = getMyAccount();

        Test.startTest();

        List<Account> healthProfileInfo = kHC_MyHeathProfileController.getMyInformation(myAccount.Id);

        Test.stopTest();

        System.assertEquals(healthProfileInfo[0].HealthCloudGA__MedicationStatements__r[0].HealthCloudGA__MedicationName__c,
                'Advil',
                'Medication Name should be Advil'
        );
    }

    @IsTest
    static void updateAccountTest() { // TODO write test for negative result

        Account myAccount = getMyAccount();
        System.assertEquals(myAccount.Organ_Donor__pc, true,
                'This person should be organ donor before updating it');

        Contact myContact = getMyContact();
        System.assertEquals(myContact.Rhesus_Negative__c, false,
                'This person should be organ donor before updating it');

        Test.startTest();
        myAccount.Organ_Donor__pc = false;
        myContact.Rhesus_Negative__c = true;
        kHC_MyHeathProfileController.getBloodTypePicklistValues();
        kHC_MyHeathProfileController.getRelationShipValues();
        kHC_MyHeathProfileController.getInsurancesByMemberId(myContact.Id);
        kHC_MyHeathProfileController.getProvidersByPatientId(myContact.Id);
        kHC_MyHeathProfileController.updateAccount(myAccount, myContact);
        Test.stopTest();

        Account myAccountAfterUpdate = getMyAccount();
        Contact myContactAfterUpdate = getMyContact();
        System.assertEquals(myAccountAfterUpdate.Organ_Donor__pc, false,
                'This person should NOT be organ donor after update');
        System.assertEquals(myContactAfterUpdate.Rhesus_Negative__c, true,
                'This person should have Rhesus Negative equals true after update');
    }

    @IsTest
    static void getBreastHealthTopicTest() {
        List<String> breastHealthTopics = kHC_MyHeathProfileController.getBreastHealthTopic();
        system.assertNotEquals(0, breastHealthTopics.size());
    }

    private static Account getMyAccount() {
        return [SELECT Organ_Donor__pc FROM Account WHERE PersonEmail = :PERSON_EMAIL];
    }

    private static Contact getMyContact() {
        return [SELECT Rhesus_Negative__c FROM Contact WHERE Email = :PERSON_EMAIL];
    }
}