unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/HealthCloudGA__EhrCondition__c/HealthCloudGA__EhrCondition__c.object-meta.xml
<CustomObject>
    <description>Use to record detailed information about conditions, problems or diagnoses recognized by a clinician. There are many uses including: recording a Diagnosis during an Encounter; populating a problem List or a Summary Statement, such as a Discharge Summary.</description>
    <label>EHR Condition</label>
    <nameField>
        <displayFormat>Cond-{0}</displayFormat>
        <label>EHR Condition ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EHR Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/HealthCloudGA__EhrCondition__c/fields/Breast_Cancer_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Breast_Cancer_Sub_Type__c</fullName>
    <label>Breast Cancer Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TNBC (ER-/PR-/HER2-)</fullName>
            </value>
            <value>
                <fullName>TPBC (ER+/PR+/HER2+)</fullName>
            </value>
            <value>
                <fullName>ER+/HER2-</fullName>
            </value>
            <value>
                <fullName>ER-/HER2+</fullName>
            </value>
            <value>
                <fullName>Other (please specify)</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrCondition__c/fields/Breast_Cancer_Sub_Type_Other__c.field-meta.xml
<CustomField>
    <fullName>Breast_Cancer_Sub_Type_Other__c</fullName>
    <description>To be filled in when Breast Cancer Sub Type selection is &quot;Other (please specify)&quot;</description>
    <label>Breast Cancer Sub Type Other</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrCondition__c/fields/Breast_Cancer_Type__c.field-meta.xml
<CustomField>
    <fullName>Breast_Cancer_Type__c</fullName>
    <label>Breast Cancer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Breast_Cancer_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrCondition__c/fields/Breast_Cancer_Type_Other__c.field-meta.xml
<CustomField>
    <fullName>Breast_Cancer_Type_Other__c</fullName>
    <description>If Other (please specify) is selected in the Breast Cancer Type, this field should be filled in with that detail</description>
    <label>Breast Cancer Type Other</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrCondition__c/fields/Condition_Name__c.field-meta.xml
<CustomField>
    <fullName>Condition_Name__c</fullName>
    <label>Condition Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrCondition__c/fields/Date_Abated__c.field-meta.xml
<CustomField>
    <fullName>Date_Abated__c</fullName>
    <description>The estimated or actual date when the condition, problem, or diagnosis was no longer experienced / was resolved.</description>
    <label>Date Abated</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrCondition__c/fields/HealthCloudGA__DateAsserted__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__DateAsserted__c</fullName>
    <inlineHelpText>The estimated or actual date when the condition, problem, or diagnosis was first detected or suspected.</inlineHelpText>
    <label>Date Asserted</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrCondition__c/fields/Stage_at_Diagnosis__c.field-meta.xml
<CustomField>
    <fullName>Stage_at_Diagnosis__c</fullName>
    <label>Stage at Diagnosis</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stage-0/In Situ (DCIS)</fullName>
            </value>
            <value>
                <fullName>Stage-I</fullName>
            </value>
            <value>
                <fullName>Stage-II</fullName>
            </value>
            <value>
                <fullName>Stage-III</fullName>
            </value>
            <value>
                <fullName>Stage-IV</fullName>
            </value>
            <value>
                <fullName>Undesignated﻿</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrCondition__c/fields/Treatment_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Treatment_End_Date__c</fullName>
    <description>Can be approximate, use first of the month or first month of the year if unsure</description>
    <label>Treatment End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrCondition__c/fields/Treatment_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Start_Date__c</fullName>
    <description>Can be approximate, use the start of the month, or the first month of the year if unsure.</description>
    <label>Treatment Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/globalValueSets/Breast_Cancer_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Ductal carcinoma in situ (DCIS)</fullName>
    </customValue>
    <customValue>
        <fullName>Invasive Ductal Carcinoma</fullName>
    </customValue>
    <customValue>
        <fullName>Invasive Lobular Carcinoma</fullName>
    </customValue>
    <customValue>
        <fullName>Inflammatory Breast Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Metaplastic Breast Cancer</fullName>
    </customValue>
    <customValue>
        <fullName>Other (please specify)</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <masterLabel>Breast Cancer Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/kHC_MyHeathConditionsController.cls
/**
 * @description Controller class for My Health Profile Page.
 * @author Vikrant Upneja , Traction on Demand
 * @date 9/14/2020.
 */
public with sharing class kHC_MyHeathConditionsController {

    /**
     * Get the Map of Type of Health Condition and Health Conditions
     * @param recordId current Logged in Account Id
     *
     * @return Map of Type and List of Condition.
     */
    /*
    @AuraEnabled
    //public static List<HealthCloudGA__EhrCondition__c> getBreastCancerConditions(Id currentLoggedAccount){
    public static Map<String, List<HealthCloudGA__EhrCondition__c>> getBreastCancerConditions(Id currentLoggedAccount){
          Map<String, List<HealthCloudGA__EhrCondition__c>>  healthConditionMap = new Map<String, List<HealthCloudGA__EhrCondition__c>>();
        system.debug('** currentLoggedAccount '+ currentLoggedAccount);
        List<HealthCloudGA__EhrCondition__c> breastCancerInfo = [
                                                                    SELECT  Id, Breast_Cancer_Sub_Type__c,Breast_Cancer_Type__c, Stage_at_Diagnosis__c,
                                                                            HealthCloudGA__DateAsserted__c, Date_Abated__c, Condition_Name__c, HealthCloudGA__IsAbated__c,
                                                                            HealthCloudGA__Notes__c, recordtype.Name, recordtype.Id
                                                                    FROM HealthCloudGA__EhrCondition__c
                                                                    WHERE HealthCloudGA__Account__c = :currentLoggedAccount  and Condition_Name__c != ''
                                                                ];

        system.debug('** breastCancerInfo.size() '+ breastCancerInfo.size());

        if(breastCancerInfo.size() >0) {
            for (HealthCloudGA__EhrCondition__c condition : breastCancerInfo) {
                if (healthConditionMap.containsKey((condition.RecordType).Name)) {
                    healthConditionMap.get((condition.RecordType).Name).add(condition);
                } else {
                    List<HealthCloudGA__EhrCondition__c> healthConditionList = new List<HealthCloudGA__EhrCondition__c>();
                    healthConditionList.add(condition);
                    healthConditionMap.put((condition.RecordType).Name, healthConditionList);
                }
            }
            return healthConditionMap;
        }
        //return breastCancerInfo;
        return null;
    }
    */
/**
 * Get the List of Chronic Conditions
 * @param recordId current Logged in Account Id
 *
 * @return List of Chronic Condition.
 */

    @AuraEnabled
    public static List<HealthCloudGA__EhrCondition__c> getChronicConditions(Id currentLoggedAccount){
        system.debug('** currentLoggedAccount '+ currentLoggedAccount);
        List<HealthCloudGA__EhrCondition__c> chronicConditionsInfo = [
                SELECT  Id, HealthCloudGA__DateAsserted__c, Date_Abated__c, Condition_Name__c, HealthCloudGA__IsAbated__c,
                        HealthCloudGA__Notes__c, recordtype.Name, recordtype.Id
                FROM HealthCloudGA__EhrCondition__c
                WHERE HealthCloudGA__Account__c = :currentLoggedAccount  and Condition_Name__c != ''
                and RecordType.Name = 'Chronic Condition'
        ];

        system.debug('** breastCancerInfo.size() '+ chronicConditionsInfo.size());
        return chronicConditionsInfo;
    }

/**
 * Get the List of Breast Cancer Conditions
 * @param recordId current Logged in Account Id
 *
 * @return  List of Breast Cancer Condition.
 */
    @AuraEnabled
    public static List<HealthCloudGA__EhrCondition__c> getBCancerConditions(Id currentLoggedAccount){
        system.debug('** currentLoggedAccount '+ currentLoggedAccount);
        List<HealthCloudGA__EhrCondition__c> breastCancerInfo = [
                SELECT  Id, Breast_Cancer_Sub_Type__c,Breast_Cancer_Type__c, Stage_at_Diagnosis__c,
                        HealthCloudGA__DateAsserted__c, Date_Abated__c, Condition_Name__c, HealthCloudGA__IsAbated__c,
                        HealthCloudGA__Notes__c, recordtype.Name, recordtype.Id
                FROM HealthCloudGA__EhrCondition__c
                WHERE HealthCloudGA__Account__c = :currentLoggedAccount  and Condition_Name__c != ''
                and RecordType.Name = 'Breast Cancer'
        ];

        system.debug('** breastCancerInfo.size() '+ breastCancerInfo.size());

        return breastCancerInfo;
    }

 /**
 *
 * @return List of recordTypes for Condition.
 */
    @AuraEnabled
    public static list<RecordType> getConditionRecordType(){
        return [select Id,Name, Developername from RecordType where sObjectType='HealthCloudGA__EhrCondition__c'];
        //return null;
    }

    @AuraEnabled
    public static List<HealthCloudGA__EhrCondition__c> getCondition(Id recordId, Id currentLoggedAccount) {
        List<HealthCloudGA__EhrCondition__c> conditions = [
                SELECT Id, Breast_Cancer_Type__c, Breast_Cancer_Type_Other__c,
                        Breast_Cancer_Sub_Type__c, Breast_Cancer_Sub_Type_Other__c, HealthCloudGA__IsAbated__c, Date_Abated__c, Is_Recurrence__c,
                        Condition_Name__c, Stage_at_Diagnosis__c, HealthCloudGA__DateAsserted__c, Treatment_Start_Date__c, Treatment_End_Date__c,
                        HealthCloudGA__Notes__c, HealthCloudGA__Account__c
                FROM HealthCloudGA__EhrCondition__c
                WHERE HealthCloudGA__Account__c = :currentLoggedAccount AND Id = :recordId
                LIMIT 1
        ];

        return conditions;
    }
}