unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Knowledge__kav/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Knowledge</relationshipLabel>
    <relationshipName>Knowledge</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/fields/Account_Billing_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Account_Billing_Address_City__c</fullName>
    <formula>Account__r.BillingCity</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Billing Address City</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/fields/Account_Billing_Address_Country__c.field-meta.xml
<CustomField>
    <fullName>Account_Billing_Address_Country__c</fullName>
    <formula>Account__r.BillingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Billing Address Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/fields/Account_Billing_Address_State__c.field-meta.xml
<CustomField>
    <fullName>Account_Billing_Address_State__c</fullName>
    <formula>Account__r.BillingState</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Billing Address State</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/fields/Account_Billing_Address_Street__c.field-meta.xml
<CustomField>
    <fullName>Account_Billing_Address_Street__c</fullName>
    <formula>Account__r.BillingStreet</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Billing Address Street</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/fields/Account_Billing_Address_Zip__c.field-meta.xml
<CustomField>
    <fullName>Account_Billing_Address_Zip__c</fullName>
    <formula>Account__r.BillingPostalCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Billing Address Zip</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/fields/Komen_Site_URL__c.field-meta.xml
<CustomField>
    <fullName>Komen_Site_URL__c</fullName>
    <inlineHelpText>Enter the URL of the page on the Komen Public web site.</inlineHelpText>
    <label>Site URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <formula>Account__r.Phone</formula>
    <label>Phone</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/fields/Relationship_To_Cancer__c.field-meta.xml
<CustomField>
    <fullName>Relationship_To_Cancer__c</fullName>
    <label>Relationship To Cancer</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Relationship_To_Cancer</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <label>Resource Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Article</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/recordTypes/Knowledge.recordType-meta.xml
<RecordType>
    <fullName>Knowledge</fullName>
    <active>true</active>
    <label>Knowledge</label>
</RecordType>

unpackaged/main/default/objects/Knowledge_Resource_Recommendation__c/Knowledge_Resource_Recommendation__c.object-meta.xml
<CustomObject>
    <label>Knowledge Resource Recommendation</label>
    <nameField>
        <label>Knowledge Resource Recommendation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knowledge Resource Recommendations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Knowledge_Resource_Recommendation__c/fields/Community_Topics__c.field-meta.xml
<CustomField>
    <fullName>Community_Topics__c</fullName>
    <description>not for display on the Knowledge Resource Recommendation page, used to power picklist options in flows.</description>
    <label>Community Topics</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Community_Topics</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Knowledge_Resource_Recommendation__c/fields/US_States__c.field-meta.xml
<CustomField>
    <fullName>US_States__c</fullName>
    <description>Not for display - used in Flow</description>
    <label>US States</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>Armed Forces Americas</fullName>
            </value>
            <value>
                <fullName>Armed Forces Europe</fullName>
            </value>
            <value>
                <fullName>Armed Forces Pacific</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Guam</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Referral_Record__c/Referral_Record__c.object-meta.xml
<CustomObject>
    <label>Referral Record</label>
    <nameField>
        <displayFormat>RR-{00000}</displayFormat>
        <label>Referral Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Referral_Record__c/fields/Favourite__c.field-meta.xml
<CustomField>
    <fullName>Favourite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Favorite</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Referral_Record__c/fields/Featured__c.field-meta.xml
<CustomField>
    <fullName>Featured__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Featured</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Referral_Record__c/fields/Knowledge_Article_Referred__c.field-meta.xml
<CustomField>
    <fullName>Knowledge_Article_Referred__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Knowledge Article Referred</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Referral Records</relationshipLabel>
    <relationshipName>Referral_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Referral_Record__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referral Records</relationshipLabel>
    <relationshipName>Referral_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Referral_Record__c/fields/Referred__c.field-meta.xml
<CustomField>
    <fullName>Referred__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Referred</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Contact.AccountId</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Relationship_To_Cancer.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Never been diagnosed</fullName>
    </customValue>
    <customValue>
        <fullName>Recently diagnosed</fullName>
    </customValue>
    <customValue>
        <fullName>Undergoing treatment</fullName>
    </customValue>
    <customValue>
        <fullName>In Survivorship</fullName>
    </customValue>
    <customValue>
        <fullName>Care-giver or Co-Survivor</fullName>
    </customValue>
    <customValue>
        <fullName>Living with MBC</fullName>
    </customValue>
    <description>Values set during the initial onboarding to MyKomen Health</description>
    <masterLabel>Relationship To Cancer</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/KHC_ResourceLibraryCtrl.cls
public with sharing class KHC_ResourceLibraryCtrl {

    private static Set<String> refRecordFieldSet;
    private static Id knowledgeRecordTypeId = Schema.SObjectType.Knowledge__kav.getRecordTypeInfosByName().get('Knowledge').getRecordTypeId();

    static{
        refRecordFieldSet = new Set<String>();
        refRecordFieldSet.add( 'Favourite__c' );
        refRecordFieldSet.add( 'Knowledge_Article_Referred__r.Featured__c' );
        refRecordFieldSet.add( 'Knowledge_Article_Referred__r.Phone__c' );
        refRecordFieldSet.add( 'Knowledge_Article_Referred__r.Email__c' );
        refRecordFieldSet.add( 'Knowledge_Article_Referred__c' );
        refRecordFieldSet.add( 'Knowledge_Article_Referred__r.Resource_Type__c' );
        refRecordFieldSet.add( 'Knowledge_Article_Referred__r.Title' );
        refRecordFieldSet.add( 'Knowledge_Article_Referred__r.Summary' );
        refRecordFieldSet.add( 'Knowledge_Article_Referred__r.Account_Name__c' );
        refRecordFieldSet.add( 'Knowledge_Article_Referred__r.Account_Billing_Address_Street__c' );
        refRecordFieldSet.add( 'Knowledge_Article_Referred__r.Account_Billing_Address_City__c' );
        refRecordFieldSet.add( 'Knowledge_Article_Referred__r.Account_Billing_Address_State__c' );
        refRecordFieldSet.add( 'Knowledge_Article_Referred__r.Account_Billing_Address_Country__c' );
        refRecordFieldSet.add( 'Knowledge_Article_Referred__r.Account_Billing_Address_Zip__c' );
        refRecordFieldSet.add( 'Knowledge_Article_Referred__r.Komen_Site_URL__c' );
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getTopics(){
        List<String> topicOptions = new List<String>();
        Schema.DescribeFieldResult fieldResult = Knowledge__kav.Community_Topics__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			topicOptions.add(pickListVal.getLabel());
		}

		return topicOptions;
    }

    @AuraEnabled(cacheable=true)
    public static List<String> getTypes(){
        List<String> typeOptions = new List<String>();
        Schema.DescribeFieldResult fieldResult = Knowledge__kav.Resource_Type__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			typeOptions.add( pickListVal.getLabel() );
		}     
		return typeOptions;
    }

    @AuraEnabled(cacheable=true)
    public static List<String> getLocations(){
        List<String> locationOptions = new List<String>();
        Schema.DescribeFieldResult fieldResult = Knowledge_Resource_Recommendation__c.US_States__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			locationOptions.add( pickListVal.getLabel() );
		}
		return locationOptions;
    }

    public static List<Referral_Record__c> removeDuplicateReferralRecords(List<Referral_Record__c> referrals) {

        if (referrals.isEmpty()) {
            return referrals;
        }

        Set<Id> mySet = new Set<Id>();
        List<Referral_Record__c> refs = new List<Referral_Record__c>();

        for (Integer i = 0; i < referrals.size(); i++) {
            if (!mySet.contains(referrals[i].Knowledge_Article_Referred__c)) {
                mySet.add(referrals[i].Knowledge_Article_Referred__c);
                refs.add(referrals[i]);
            }
        }
        return refs;
    }

    @AuraEnabled
    public static List<Referral_Record__c> getMyReferrals(){
        User currUser = MyKomenHealthUtility.getLoggedInUserDetails();
        if( currUser != null ){
            Id accId = currUser.AccountId;
            String query = 'SELECT Id ';
            for( String fieldStr : refRecordFieldSet ){
                query += ', ' + fieldStr;
            }
            query += ' FROM  Referral_Record__c';
            query += ' WHERE Patient__c =: accId';
            query += ' AND Knowledge_Article_Referred__c != NULL';
            query += ' AND Knowledge_Article_Referred__r.IsVisibleInCsp = TRUE';
            query += ' AND Referred__c = TRUE';
            query += ' AND Knowledge_Article_Referred__r.ArchivedById = NULL';
            query += ' AND Knowledge_Article_Referred__r.IsLatestVersion = TRUE';
            query += ' AND Knowledge_Article_Referred__r.PublishStatus = \'Online\'';
            query += ' ORDER BY CreatedDate DESC';
            query += ' LIMIT 3';
            return removeDuplicateReferralRecords(Database.query(query));
        }
        return null;
    }

    @AuraEnabled
    public static List<Referral_Record__c> getMyFavorites(){
        User currUser = MyKomenHealthUtility.getLoggedInUserDetails();
        if( currUser != null ){
            Id accId = currUser.AccountId;
            String query = 'SELECT Id ';
            for( String fieldStr : refRecordFieldSet ){
                query += ', ' + fieldStr;
            }
            query += ' FROM  Referral_Record__c';
            query += ' WHERE Patient__c =: accId';
            query += ' AND Knowledge_Article_Referred__c != NULL';
            query += ' AND Knowledge_Article_Referred__r.IsVisibleInCsp = TRUE';
            query += ' AND Favourite__c = TRUE';
            query += ' AND Knowledge_Article_Referred__r.ArchivedById = NULL';
            query += ' AND Knowledge_Article_Referred__r.IsLatestVersion = TRUE';
            query += ' AND Knowledge_Article_Referred__r.PublishStatus = \'Online\'';
            query += ' ORDER BY CreatedDate DESC';
            query += ' LIMIT 3';
            return removeDuplicateReferralRecords(Database.query(query));
        }
        return null;
    }

    @AuraEnabled
    public static List<Knowledge__kav> getOtherResources(){
        // Return null if Guest User
        Boolean isGuestUser = MyKomenHealthUtility.isGuestUser();
        if ( isGuestUser ) {
            return null;
        }

        // Get current User
        User currUser = MyKomenHealthUtility.getLoggedInUserDetails();
        if (currUser == null) {
            return null;
        }

        // Get current Account for User
        Account currentLoggedInAccount;
        List<Account> userAcc = [SELECT Id, Relationship_To_Cancer__pc FROM Account WHERE Id = :currUser.AccountId LIMIT 1];
        if ( userAcc.size() > 0 ) {
            currentLoggedInAccount = userAcc[0];
        }

        // Other resources are only related by the Relationship_To_Cancer__pc field
        // Return null if no Account or if no values in Relationship_To_Cancer__pc
        if (currentLoggedInAccount.Id == null ||
            currentLoggedInAccount.Relationship_To_Cancer__pc == null ) {
            return null;
        }

        // Build a query clause to ensure Articles contain one or more of the Relationships to Cancer on the Account
        // Need to loop through each relationship value because we can't bind values to INCLUDES as you'd expect
        List<String> relationshipToCancerField = currentLoggedInAccount.Relationship_To_Cancer__pc.split(';');
        String includesQueryVarString = '(';
        for ( String s : relationshipToCancerField ) {
            includesQueryVarString += ' Relationship_To_Cancer__c INCLUDES (\'' + s + '\') OR';
        }
        // Remove the last "OR" from the string and close the clause
        includesQueryVarString = includesQueryVarString.substring(0, (includesQueryVarString.length()-3));
        includesQueryVarString += ')';

        // Limit to 3 for quick view
        Integer recordLimit = 3;

        // Get count of all possible other resources
        String countQuery = 'SELECT COUNT() FROM Knowledge__kav\n' +
                'WHERE ArchivedById = NULL\n' +
                'AND RecordTypeId != NULL\n' +
                'AND RecordTypeId = :knowledgeRecordTypeId\n' +
                'AND IsLatestVersion = TRUE\n' +
                'AND PublishStatus = \'Online\' AND';
        countQuery += includesQueryVarString;
        Integer count = Database.countQuery( countQuery );

        // Determine "random" offset based on count of possible other resources
        Integer rand = Math.floor(Math.random() * count).intValue();
        Integer diff = count - rand;
        rand = ( rand + recordLimit ) > count ? ( rand - (  recordLimit - diff ) ): rand;
        rand = rand < 0 ? 0 : rand;

        // Query fields
        String query = 'SELECT Id, Title, Summary, Resource_Type__c, Community_Topics__c, Phone__c, Email__c';
        query += ', Account__c';
        query += ', Account_Name__c';
        query += ', Account_Billing_Address_Street__c';
        query += ', Account_Billing_Address_City__c';
        query += ', Account_Billing_Address_State__c';
        query += ', Account_Billing_Address_Country__c';
        query += ', Account_Billing_Address_Zip__c';
        query += ', Komen_Site_URL__c';
        query += ', Body__c';

        // Query clauses
        query += ' FROM Knowledge__kav ';
        query += ' WHERE ArchivedById = NULL';
        query += ' And RecordTypeId != NULL';
        query += ' AND RecordTypeId = :knowledgeRecordTypeId';
        query += ' AND IsLatestVersion = TRUE';
        query += ' AND PublishStatus = \'Online\' AND';
        query += includesQueryVarString;
        query += ' LIMIT :recordLimit';
        query += ' OFFSET :rand';

        return Database.query( query );
    }


    @AuraEnabled
    public static Referral_Record__c toggleFavourite(Id currentAccountId, Boolean isFavourited, Id knowledgeArticleId, Boolean isKnowledgeFeatured){
        if ( isFavourited ) {
            unfavouriteReferralRecordsForArticle(currentAccountId, knowledgeArticleId);
            return null;
        } else {
            return createNewFavouritedReferralRecord(currentAccountId, knowledgeArticleId, isKnowledgeFeatured);
        }
    }

    private static void unfavouriteReferralRecordsForArticle (Id currentAccountId, Id knowledgeArticleId) {
        List<Referral_Record__c> existingFavouritedReferralRecords = [SELECT Id, Patient__c, Knowledge_Article_Referred__c
        FROM Referral_Record__c
        WHERE Patient__c = :currentAccountId
        AND Knowledge_Article_Referred__c = :knowledgeArticleId
        AND Favourite__c = true];

        for ( Referral_Record__c r : existingFavouritedReferralRecords ) {
            r.Favourite__c = false;
        }
        update existingFavouritedReferralRecords;
    }

    private static Referral_Record__c createNewFavouritedReferralRecord (Id currentAccountId, Id knowledgeArticleId, Boolean isKnowledgeFeatured) {
        Referral_Record__c r = new Referral_Record__c();
        r.Patient__c = currentAccountId;
        r.Knowledge_Article_Referred__c = knowledgeArticleId;
        r.Favourite__c = true;
        if ( isKnowledgeFeatured ) {
            r.Featured__c = true;
        }
        insert r;
        return r;
    }

    @AuraEnabled
    public static Referral_Record__c removeReferral(Id knowledgeArticleId, String dismissalReason){
        // Return null if Guest User
        Boolean isGuestUser = MyKomenHealthUtility.isGuestUser();
        if ( isGuestUser ) {
            return null;
        }

        // Get current User
        User currUser = MyKomenHealthUtility.getLoggedInUserDetails();
        if (currUser == null) {
            return null;
        }

        List<Referral_Record__c> existingReferredReferrals = [SELECT Id, Patient__c, Knowledge_Article_Referred__c
        FROM Referral_Record__c
        WHERE Patient__c = :currUser.AccountId
        AND Knowledge_Article_Referred__c = :knowledgeArticleId
        AND Referred__c = true];

        if ( existingReferredReferrals.size() > 0 ) {
            for( Referral_Record__c rr : existingReferredReferrals ) {
                rr.Referred__c = false;
                rr.Dismissal_Reason__c = dismissalReason;
            }
            update existingReferredReferrals;
        }

        return null;
    }

}