unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track Health Insurance Information for a Patient</description>
    <label>Application</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>The Status from the Application Submitted/New to till Approved or Rejected.</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Need More Information</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Payment Error</fullName>
                <isActive>false</isActive>
                <label>Payment Error</label>
            </value>
            <value>
                <fullName>Payment Processing</fullName>
                <isActive>false</isActive>
                <label>Payment Processing</label>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/recordTypes/Patient_Navigation.recordType-meta.xml
<RecordType>
    <fullName>Patient_Navigation</fullName>
    <active>true</active>
    <label>Patient Navigation</label>
</RecordType>

unpackaged/main/default/objects/User/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Contact.AccountId</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/KHC_ApplicationController.cls
/**
 * Created by vupneja on 3/1/2021.
 */

public with sharing class KHC_ApplicationController {

    private static ApplicationEnrollmentReqSelector applicationEnrollmentReqSelector = new ApplicationEnrollmentReqSelector();

    @AuraEnabled
    // To fetch the Application records.
    public static List<Application__c> getApplications(){
        User currUser = getLoggedInUserDetails();
        if( currUser != null ){
            return applicationEnrollmentReqSelector.selectApplicationEnrollmentReq( currUser.Account__c);
        }
        return null;
    }

    @AuraEnabled
    //Method to get logged in user
    public static User getLoggedInUserDetails(){
        List<User> loggedInUsers = [SELECT Id,
                                    Account__c
                                    FROM User
                                    WHERE Id = :UserInfo.getUSerId()];
        if( loggedInUsers != null && !loggedInUsers.isEmpty() ){
            return loggedInUsers[0];
        }
        return null;
    }

    @AuraEnabled
    //Method to update Application Status = Canceled
    public static Boolean withdrawApplication(Id enrollmentId){

        List<Application__c> Enrollment = [SELECT Id,
                                            Application_Status__c
                                            FROM Application__c
                                            WHERE Id = :enrollmentID];

            if( Enrollment.size() > 0 ){
                Enrollment[0].Application_Status__c = 'Canceled';
                update Enrollment;
                return true;
        }
        return false;
    }

    @AuraEnabled
    //Method to get logged in Patient Details
    public static Account getPatientDetails(Id accId){

        List<Account> patientDetails = [SELECT
                                        PersonEmail
                                        FROM Account
                                        WHERE Id = :accId];
            if( patientDetails != null && !patientDetails.isEmpty() ){
                return patientDetails[0];
        }
        return null;
    }

    @AuraEnabled
    //Method to get RecordType Id
    public static String getPatientNavigationRecordTypeID(){
        Id recordTypeId =  Schema.SObjectType.Application__c.getRecordTypeInfosByDeveloperName().get('Patient_Navigation').getRecordTypeId();
        return String.valueof(recordTypeId);
    }
}