unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track Health Insurance Information for a Patient</description>
    <label>Application</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CareProgram/fields/Payout_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payout_Amount__c</fullName>
    <description>Payout Amount for this Care Program.</description>
    <label>Payout Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Eligibility_Detail__c/Eligibility_Detail__c.object-meta.xml
<CustomObject>
    <description>This objects holds data details of Care Program eligibility criteria.</description>
    <label>Eligibility Detail</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Eligibility Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligibility Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Eligibility_Detail__c/fields/Eligibility_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Criteria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Eligibility Criteria</label>
    <referenceTo>EnrollmentEligibilityCriteria</referenceTo>
    <relationshipLabel>Eligibility Details</relationshipLabel>
    <relationshipName>Eligibility_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TAP_CareProgram_Ctlr_Test.cls
@isTest
public class TAP_CareProgram_Ctlr_Test {
    @testSetup static void setup() {
        
        //Create common test accounts
        List<Account> testaccounts = TAP_TestDataFactory.createAccount(2,'Account'); 
        
        // Create common test care Program
        List<CareProgram> testCarePrograms = TAP_TestDataFactory.createCareProgram(2,'careProgram');
        
        // Create common test application
        List<Application__c> testapplications = TAP_TestDataFactory.createApplication(1,testaccounts[0].Id,testCarePrograms[0].Id);
        
        // Create common test EnrollmentEligibilityCriteria
        List<EnrollmentEligibilityCriteria> enrollmentEligibilityCriterias = TAP_TestDataFactory.createEnrollmentEligibilityCriteria(1,'Income','TestIncomeCriteria');
        
        // Create common test CareProgramEligibilityRule
        List<CareProgramEligibilityRule> careProgramRules = TAP_TestDataFactory.careProgramEligibilityRule(1,enrollmentEligibilityCriterias[0].Id,testCarePrograms[0].Id); 
    }

    @isTest static void loadProgramDetails(){
        
        //List of CarePrograms
        CareProgram careProgram = [SELECT ID,Payout_Amount__c FROM CareProgram WHERE Name = 'careProgram0'];
        
        test.startTest();
        Map<String,Integer> loadProgramDetailsMap = TAP_CareProgram_Ctlr.loadProgramDetails(careProgram.id);
        test.stopTest();
       
        //List of EnrollmentEligibilityCriteria
        List<EnrollmentEligibilityCriteria> enrollmentEligibilityCriteria = [SELECT Id FROM EnrollmentEligibilityCriteria WHERE Name ='TestIncomeCriteria'];
        system.assertEquals(1, enrollmentEligibilityCriteria.size());
        
        //List of CareProgramEligibilityRule
        List<CareProgramEligibilityRule> careProgramRule = [SELECT Id FROM CareProgramEligibilityRule WHERE CareProgramId =:careProgram.Id];
        system.assertEquals(1, careProgramRule.size());
        
        //List of Eligibility Details
        List<Eligibility_Detail__c> eligibilityDetail =  [SELECT Id FROM Eligibility_Detail__c WHERE Eligibility_Criteria__c =:enrollmentEligibilityCriteria[0].Id];
        system.assertEquals(0, eligibilityDetail.size());   
    }
}