unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/HealthCloudGA__EHRProcedure__c/fields/Procedure_Type__c.field-meta.xml
<CustomField>
    <fullName>Procedure_Type__c</fullName>
    <label>Procedure Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mammogram</fullName>
                <isActive>false</isActive>
            </value>
            <value>
                <fullName>Screening</fullName>
                <isActive>false</isActive>
            </value>
            <value>
                <fullName>Biopsy</fullName>
            </value>
            <value>
                <fullName>Vitals</fullName>
                <isActive>false</isActive>
            </value>
            <value>
                <fullName>Blood Draw</fullName>
                <isActive>false</isActive>
            </value>
            <value>
                <fullName>Xray</fullName>
                <isActive>false</isActive>
            </value>
            <value>
                <fullName>MRI</fullName>
                <isActive>false</isActive>
            </value>
            <value>
                <fullName>CT Scan</fullName>
                <isActive>false</isActive>
            </value>
            <value>
                <fullName>Screening/ Imaging</fullName>
                <label>CT Scan</label>
            </value>
            <value>
                <fullName>Diagnostic Imaging</fullName>
                <label>CT Scan</label>
            </value>
            <value>
                <fullName>Chemotherapy (Infusion)</fullName>
                <label>CT Scan</label>
            </value>
            <value>
                <fullName>Chemotherapy (Oral)</fullName>
                <label>CT Scan</label>
            </value>
            <value>
                <fullName>Hormone Therapy</fullName>
            </value>
            <value>
                <fullName>Immunotherapy</fullName>
            </value>
            <value>
                <fullName>Radiation</fullName>
            </value>
            <value>
                <fullName>Lumpectomy</fullName>
            </value>
            <value>
                <fullName>Mastectomy</fullName>
            </value>
            <value>
                <fullName>Palliative Care</fullName>
            </value>
            <value>
                <fullName>End of life care</fullName>
            </value>
            <value>
                <fullName>Other (please specify in notes)</fullName>
            </value>    
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/kHC_MyProceduresControllerTest.cls
/**
 * Created by vupneja on 10/9/2020.
 */

@isTest
public with sharing class kHC_MyProceduresControllerTest {
    private static final String PERSON_EMAIL = 'peggy@komen.org';

    @TestSetup
    static void setup() {
        String picklistValue = 'Lumpectomy';
        List<String> picklistValues = getPickListValuesIntoList();
        if(picklistValues.size() > 0) {
            picklistValue = picklistValues[0];
        }
        Account person1 = MKH_TestDataFactory.createPersonAccount('Peggy', 'Peggerson', 'peggy@komen.org', true);

        HealthCloudGA__EHRProcedure__c myProcedure = new HealthCloudGA__EHRProcedure__c(HealthCloudGA__Account__c = person1.Id,
                Procedure_Type__c = picklistValue, HealthCloudGA__PerformedDateTime__c =  DateTime.now());
        insert myProcedure;
    }

     private static List<String> getPickListValuesIntoList(){
        List<String> pickListValuesList= new List<String>();
        Schema.DescribeFieldResult fieldResult = HealthCloudGA__EHRProcedure__c.Procedure_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
        }
        return pickListValuesList;
    }

    private static Account getMyAccount() {
        return [SELECT Organ_Donor__pc FROM Account WHERE PersonEmail = :PERSON_EMAIL];
    }


    @IsTest
    static void getMyProcedureTest() {

        String picklistValue = 'Lumpectomy';
        List<String> picklistValues = getPickListValuesIntoList();
        if(picklistValues.size() > 0) {
            picklistValue = picklistValues[0];
        }

        Account myAccount = getMyAccount();

        Test.startTest();
        List<HealthCloudGA__EHRProcedure__c> procedureInfo = kHC_MyProceduresController.getProcedures(myAccount.Id);
        Test.stopTest();

        System.assertEquals(procedureInfo[0].Procedure_Type__c, picklistValue, 'Procedure should be ' + picklistValue);
    }

    private static List<HealthCloudGA__EHRProcedure__c> getProcedure() {
        Account account = getMyAccount();
        return [
                SELECT Procedure_Type__c, HealthCloudGA__PerformedDateTime__c, HealthCloudGA__Account__c, Id
                FROM HealthCloudGA__EHRProcedure__c
                WHERE HealthCloudGA__Account__c = :account.Id
                LIMIT 1
        ];
    }

    @IsTest
    static void getEditProcedureTest() {
        String picklistValue = 'Lumpectomy';
        List<String> picklistValues = getPickListValuesIntoList();
        if(picklistValues.size() > 0) {
            picklistValue = picklistValues[0];
        }

        Account account = getMyAccount();
        HealthCloudGA__EHRProcedure__c procedure = getProcedure()[0];

        List<HealthCloudGA__EHRProcedure__c> editProcedure = kHC_MyProceduresController.getEditProcedure(account.Id, procedure.Id);
        System.assertEquals(1, editProcedure.size());
        System.assertEquals(account.Id, editProcedure[0].HealthCloudGA__Account__c);
        System.assertEquals(procedure.Id, editProcedure[0].Id); 
    }
}