unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Knowledge__kav/fields/Komen_Site_URL__c.field-meta.xml
<CustomField>
    <fullName>Komen_Site_URL__c</fullName>
    <inlineHelpText>Enter the URL of the page on the Komen Public web site.</inlineHelpText>
    <label>Site URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/recordTypes/Knowledge.recordType-meta.xml
<RecordType>
    <fullName>Knowledge</fullName>
    <active>true</active>
    <label>Knowledge</label>
</RecordType>

unpackaged/main/default/objects/Referral_Record__c/Referral_Record__c.object-meta.xml
<CustomObject>
    <label>Referral Record</label>
    <nameField>
        <displayFormat>RR-{00000}</displayFormat>
        <label>Referral Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Referral_Record__c/fields/Favourite__c.field-meta.xml
<CustomField>
    <fullName>Favourite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Favorite</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Referral_Record__c/fields/Referred__c.field-meta.xml
<CustomField>
    <fullName>Referred__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Referred</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/KHC_ResourceSearchControllerTest.cls
@isTest
public class KHC_ResourceSearchControllerTest {
    
    static String testingEmail = 'test@test.com';
    private static Id knowledgeRecordTypeId = Schema.SObjectType.Knowledge__kav.getRecordTypeInfosByName().get('Knowledge').getRecordTypeId();

    @TestSetup
    static void makeData(){
        Account a = MKH_TestDataFactory.createPersonAccount('First', 'Last', testingEmail, true);
        Contact con = [SELECT FirstName, LastName, Email FROM Contact WHERE AccountId = :a.Id];
        MKH_TestDataFactory.createCommunityUser( con, true, true);
        User commUsr = [SELECT Id, AccountId FROM User WHERE  email = :testingEmail LIMIT 1];

        List<Knowledge__kav> newArticles = new List<Knowledge__kav>();
        newArticles.add( KHC_TestUtility.insertKnowledgeArticleVersion( 'SampleArticle', 'Article',
                false, knowledgeRecordTypeId, true) );
        newArticles.add( KHC_TestUtility.insertKnowledgeArticleVersion( 'SampleWeb', 'Web',
                false, knowledgeRecordTypeId, false ) );
        newArticles[1].Komen_Site_URL__c = 'https://test.com';
        newArticles[1].Community_Topics__c = 'Care coordination, logistics;Screening & Mammograms';
        INSERT newArticles;
        for( Knowledge__kav knowledge : [SELECT Id,Title,KnowledgeArticleId FROM knowledge__kav] ){
            KbManagement.PublishingService.publishArticle( knowledge.KnowledgeArticleId, true );   
        }

        Referral_Record__c refRecord = KHC_TestUtility.insertReferralRecord( a.Id, newArticles[1].Id, false );
        refRecord.Referred__c = true;
        refRecord.Favourite__c = true;

        INSERT refRecord;
    }

    @isTest
    static void getResourcesNullFilters(){
        User commUsr = [SELECT Id, AccountId FROM User WHERE  email = :testingEmail LIMIT 1];
        System.runAs( commUsr ){
            Test.startTest();
            List<Knowledge__kav> articles = KHC_ResourceSearchController.getResources( null );
            System.assertEquals( 2, articles.size(), 'All articles must be returned.');
            Test.stopTest();
        }
    }

    @isTest
    static void getResourcesFilterByType(){
        User commUsr = [SELECT Id, AccountId FROM User WHERE  email = :testingEmail LIMIT 1];
        System.runAs( commUsr ){
            Test.startTest();
            KHC_ResourceSearchController.ResourceFilterWrapper filter = new KHC_ResourceSearchController.ResourceFilterWrapper();
            filter.type = new List<String>{'Web'};
            List<Knowledge__kav> articles = KHC_ResourceSearchController.getResources( filter );
            System.assertEquals( 1, articles.size(), '1 article must be returned.');
            Test.stopTest();
        }
    }

    @isTest
    static void getResourcesFilterByTopics(){
        User commUsr = [SELECT Id, AccountId FROM User WHERE  email = :testingEmail LIMIT 1];
        System.runAs( commUsr ){
            Test.startTest();
            KHC_ResourceSearchController.ResourceFilterWrapper filter = new KHC_ResourceSearchController.ResourceFilterWrapper();
            filter.topics = new List<String>{'Care coordination, logistics'};
            List<Knowledge__kav> articles = KHC_ResourceSearchController.getResources( filter );
            System.assertEquals( 1, articles.size(), '1 article must be returned.');
            Test.stopTest();
        }
    }

    @isTest
    static void getResourcesFilterByFeatured(){
        User commUsr = [SELECT Id, AccountId FROM User WHERE  email = :testingEmail LIMIT 1];
        System.runAs( commUsr ){
            Test.startTest();
            KHC_ResourceSearchController.ResourceFilterWrapper filter = new KHC_ResourceSearchController.ResourceFilterWrapper();
            filter.featured = true;
            List<Knowledge__kav> articles = KHC_ResourceSearchController.getResources( filter );
            System.assertEquals( 1, articles.size(), '1 article must be returned.');
            Test.stopTest();
        }
    }

    @isTest
    static void getResourcesFilterByReferred(){
        User commUsr = [SELECT Id, AccountId FROM User WHERE  email = :testingEmail LIMIT 1];
        System.runAs( commUsr ){
            Test.startTest();
            KHC_ResourceSearchController.ResourceFilterWrapper filter = new KHC_ResourceSearchController.ResourceFilterWrapper();
            filter.referred = true;
            List<Knowledge__kav> articles = KHC_ResourceSearchController.getResources( filter );
            System.assertEquals( 1, articles.size(), '1 article must be returned.');
            Test.stopTest();
        }
    }

    @isTest
    static void getResourcesFilterByFavourites(){
        User commUsr = [SELECT Id, AccountId FROM User WHERE  email = :testingEmail LIMIT 1];
        System.runAs( commUsr ){
            Test.startTest();
            KHC_ResourceSearchController.ResourceFilterWrapper filter = new KHC_ResourceSearchController.ResourceFilterWrapper();
            filter.favourites = true;
            List<Knowledge__kav> articles = KHC_ResourceSearchController.getResources( filter );
            System.assertEquals( 1, articles.size(), '1 article must be returned.');
            Test.stopTest();
        }
    }

    @isTest
    static void getResourcesFilterByLocation(){
        User commUsr = [SELECT Id, AccountId FROM User WHERE  email = :testingEmail LIMIT 1];
        System.runAs( commUsr ){
            Test.startTest();
            KHC_ResourceSearchController.ResourceFilterWrapper filter = new KHC_ResourceSearchController.ResourceFilterWrapper();
            filter.location  = new List<String>{'Colorado'};
            List<Knowledge__kav> articles = KHC_ResourceSearchController.getResources( filter );
            System.assertEquals( 0, articles.size(), 'No article must be returned.');
            Test.stopTest();
        }
    }

    @isTest
    static void getResourcesFilterById(){
        User commUsr = [SELECT Id, AccountId FROM User WHERE  email = :testingEmail LIMIT 1];
        List<knowledge__kav> knowledges = [SELECT Id,Title,KnowledgeArticleId FROM knowledge__kav LIMIT 1];
        System.runAs( commUsr ){
            Test.startTest();
            KHC_ResourceSearchController.ResourceFilterWrapper filter = new KHC_ResourceSearchController.ResourceFilterWrapper();
            filter.articleId  = knowledges[0].Id;
            List<Knowledge__kav> articles = KHC_ResourceSearchController.getResources( filter );
            System.assertEquals( 1, articles.size(), '1 article must be returned.');
            Test.stopTest();
        }
    }

    @isTest
    static void getResourcesFilterByAll(){
        User commUsr = [SELECT Id, AccountId FROM User WHERE  email = :testingEmail LIMIT 1];
        System.runAs( commUsr ){
            Test.startTest();
            KHC_ResourceSearchController.ResourceFilterWrapper filter = new KHC_ResourceSearchController.ResourceFilterWrapper();
            filter.type = new List<String>{'Web', 'Article'};
            List<Knowledge__kav> articles = KHC_ResourceSearchController.getResources( filter );
            System.assertEquals( 2, articles.size(), '2 articles must be returned.');
            filter.referred = true;
            articles = KHC_ResourceSearchController.getResources( filter );
            System.assertEquals( 1, articles.size(), '1 article must be returned.');
            Test.stopTest();
        }
    }
}