unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track Health Insurance Information for a Patient</description>
    <label>Application</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Email__c</fullName>
    <description>Application Email ID</description>
    <label>Applicant Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Applicant_has_no_award_in_last_12months__c.field-meta.xml
<CustomField>
    <fullName>Applicant_has_no_award_in_last_12months__c</fullName>
    <description>Has the applicant been awarded treatment assistance in the last 12 months?</description>
    <formula>IF( CEILING(( TODAY()  -  Patient__r.Payment_Date__c ) / 365 * 12) &lt; 12 , &quot;No&quot;, &quot;Yes&quot;)</formula>
    <inlineHelpText>Is this applicant been awarded medical treatment assistance in past 12 Months?</inlineHelpText>
    <label>Applicant Has No Award In Last 12Months?</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Applicant_resides_US_Territory__c.field-meta.xml
<CustomField>
    <fullName>Applicant_resides_US_Territory__c</fullName>
    <description>Is this Applicant Resides under US Territory?</description>
    <formula>IF( ISPICKVAL( Patient__r.PersonContact.MailingCountryCode ,&apos;US&apos;), &quot;Yes&quot;, &quot;No&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Resides In US Territory?</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Applicant_within_income_guideline__c.field-meta.xml
<CustomField>
    <fullName>Applicant_within_income_guideline__c</fullName>
    <description>Whether the Applicant comes under Income Guidelines? This field get Auto Populated.</description>
    <inlineHelpText>Is Applicant within income guidelines?</inlineHelpText>
    <label>Applicant Within Income Guidelines?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Incomplete Application</fullName>
            </value>
            <value>
                <fullName>No Income Guidelines On Care Program</fullName>
            </value>
            <value>
                <fullName>Care Program Not Selected</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>The Status from the Application Submitted/New to till Approved or Rejected.</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Need More Information</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Payment Error</fullName>
                <isActive>false</isActive>
                <label>Payment Error</label>
            </value>
            <value>
                <fullName>Payment Processing</fullName>
                <isActive>false</isActive>
                <label>Payment Processing</label>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Care_Program__c.field-meta.xml
<CustomField>
    <fullName>Care_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Care Program, Populate Name of the Care Program for the Application.</description>
    <label>Care Program</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CareProgram.Care_Program_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.Application_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>CareProgram.Status</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Applications (Care Program)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Deferred_Status_Duration__c.field-meta.xml
<CustomField>
    <fullName>Deferred_Status_Duration__c</fullName>
    <description>The Duration from Deferred to any other Stage. Using Trigger this field get Update.</description>
    <label>Deferred Status Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/In_Review_Status_Duration__c.field-meta.xml
<CustomField>
    <fullName>In_Review_Status_Duration__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The Duration from In Review to any other Stage. Using Trigger this field get Update.</description>
    <label>In Review Status Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Income_Verification_is_Valid__c.field-meta.xml
<CustomField>
    <fullName>Income_Verification_is_Valid__c</fullName>
    <description>Check true if Patient/Relative provided income documents are valid.</description>
    <inlineHelpText>Check true if Patient/Relative provided income documents are valid.</inlineHelpText>
    <label>Income Verification Is Valid?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Need_More_Info_Status_Duration__c.field-meta.xml
<CustomField>
    <fullName>Need_More_Info_Status_Duration__c</fullName>
    <description>The Duration from Need More Information Status to any other Stage . Using Trigger this field get Update.</description>
    <label>Need More Info Status Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/New_Status_Duration__c.field-meta.xml
<CustomField>
    <fullName>New_Status_Duration__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The Duration from New to any other Stage.</description>
    <label>New Status Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup with Account, to Populate Patient or Applicant Name.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Physician_confirms_patient_inactive_tre__c.field-meta.xml
<CustomField>
    <fullName>Physician_confirms_patient_inactive_tre__c</fullName>
    <description>Has physician confirmed if patient is in active breast cancer treatment?</description>
    <inlineHelpText>Has physician confirmed if patient is in active breast cancer treatment?</inlineHelpText>
    <label>Physician Confirms Active Treatment?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Poverty_Level__c.field-meta.xml
<CustomField>
    <fullName>Poverty_Level__c</fullName>
    <description>This field get Auto Calculated based on Financial Information.</description>
    <label>Poverty Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Status_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Change_Date__c</fullName>
    <label>Status Change Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Type_of_Income_Verification_Provided__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Income_Verification_Provided__c</fullName>
    <description>Select the Type of Incomes that Patient Needs to be Provided during the Application Verification.</description>
    <label>Type Of Income Verification Provided</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Income_Tax_Return</fullName>
                <label>Income Tax Return</label>
            </value>
            <value>
                <fullName>Pay_Stub</fullName>
                <label>Pay Stub</label>
            </value>
            <value>
                <fullName>Unemployment_Check</fullName>
                <label>Unemployment Check</label>
            </value>
            <value>
                <fullName>SSI</fullName>
            </value>
            <value>
                <fullName>SSD</fullName>
            </value>
            <value>
                <fullName>Public_Assistance_Benefit_Notification</fullName>
                <label>Public Assistance Benefit Notification</label>
            </value>
            <value>
                <fullName>Benefit Notification</fullName>
                <isActive>false</isActive>
                <label>Benefit Notification</label>
            </value>
            <value>
                <fullName>Letter of Support</fullName>
                <isActive>false</isActive>
                <label>Letter of Support</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TAP_Application_Helper.cls
/****************************************************************************************************************************************************************
* @author IVL Dev
* @date 18-July-2020
* @description Helper class to Application Trigger Handler.
****************************************************************************************************************************************************************/

public with sharing class TAP_Application_Helper {

    /***********************************************************************************************
    * @description calculate the Application Status Duration for each stage.
    * @param Application__c application of Application
    * @param String previousApplicationStatus of Application Status
    ************************************************************************************************/
    
    public static void calculateStatusDuration(Application__c application, String previousApplicationStatus) {
        if(application.Application_Status__c != previousApplicationStatus){
            if(previousApplicationStatus == TAP_Constants.APPLICATION_STATUS_NEW){
                application.New_Status_Duration__c = getUpdatedDuration(application.New_Status_Duration__c,application);
            } else if(previousApplicationStatus == TAP_Constants.APPLICATION_STATUS_IN_REVIEW){
                application.In_Review_Status_Duration__c = getUpdatedDuration(application.In_Review_Status_Duration__c,application);
            } else if(previousApplicationStatus == TAP_Constants.APPLICATION_STATUS_NEED_MORE_INFO){
                application.Need_More_Info_Status_Duration__c = getUpdatedDuration(application.Need_More_Info_Status_Duration__c,application);
            }else if(previousApplicationStatus == TAP_Constants.APPLICATION_STATUS_DEFERRED){
                application.Deferred_Status_Duration__c = getUpdatedDuration(application.Deferred_Status_Duration__c,application);
            }
            setStatusChangeDate(application);
        }
    }
    
    /***********************************************************************************************
    * @description Updates Income Guidelines review checks on Application
    * @param List<Application__c> applications of Application  
    ************************************************************************************************/
    
    public static void updateIncomeGuidelinesCheck(List<Application__c> applications) {
        List<Id> careProgramIds = new List<Id>();
        for(Application__c application : applications) {
            if(application.Care_Program__c != null) {
                careProgramIds.add(application.Care_Program__c);
            }
        }
        
        Map<Id,CareProgram> carePrograms = new Map<Id,CareProgram>([SELECT id,(SELECT id,EligibilityCriteria.id,EligibilityCriteria.Percent_Of_Poverty_Guideline__c 
                                                                               FROM CProgram_Eligibility_Rules WHERE EligibilityCriteria.Status = :TAP_Constants.ELIGIBILITY_CRITERIA_STATUS 
                                                                               AND EligibilityCriteria.Criteria_Type__c = 
                                                                               :TAP_Constants.ELIGIBILITY_CRITERIA_INCOME_BASED) 
                                                                    FROM CareProgram where Id IN :careProgramIds]);
        for(Application__c application : applications) {
            CareProgram careProgram = carePrograms.get(application.Care_Program__c);
            application.Applicant_within_income_guideline__c = incomeGuidelinesValue(careProgram,application);
        }
    }
    
    /***********************************************************************************************
    * @description copy the Email Id from Account and set it as Applicant Email
    * @param List<Application__c> applications of Application  
    ************************************************************************************************/
    
    public static void copyEmailIdFromAccount(List<Application__c> applications,Map<Id,Application__c> oldApplicationsMap){
        List<Id> accountIds = new List<Id>();
        for(Application__c application : applications){
            if(oldApplicationsMap.get(application.Id) == null 
               || application.Patient__c != oldApplicationsMap.get(application.Id).Patient__c){
                //accountIds.add(application.Id);
                  accountIds.add(application.Patient__c);
            }
        }
        if(accountIds.size() > 0) {
            Map<Id,Account> accountMap  = new Map<Id,Account>(
                                        [Select Id, PersonEmail from Account where Id = :accountIds]);
            for(Application__c application : applications){
                if(accountMap.get(application.Patient__c) != null){
                    application.Applicant_Email__c = accountMap.get(application.Patient__c).PersonEmail;
                }
            }
        }
    }
    
    /***********************************************************************************************
    * @description set status change date of Application to Today's date
    * @param application Application  
    ************************************************************************************************/
    
    public static void setStatusChangeDate(Application__c application) {
        application.Status_Change_Date__c = System.today();
    }

    /***********************************************************************************************
    * @description finds Incomlete review checks on Application and returns it as a list of comments.
    * @param recordId which is Application ID 
    * @return list of comments  
    ************************************************************************************************/
    public static List<String> getIncompleteReviewChecks(Id recordId) {
        Application__c application = [SELECT Id, Income_Verification_is_Valid__c, Type_of_Income_Verification_Provided__c, 
                                      Physician_confirms_patient_inactive_tre__c, Poverty_Level__c, 
                                      Applicant_within_income_guideline__c, Applicant_resides_US_Territory__c, 
                                      Applicant_has_no_award_in_last_12months__c 
                                      FROM Application__c WHERE Id = :recordId];

        List<String> comments = new List<String>();
        if(application.Income_Verification_is_Valid__c == TAP_Constants.NO) {
            comments.add(Label.Application_Income_Verification_Invalid);
        } else if(String.isBlank(application.Income_Verification_is_Valid__c)) {
            comments.add(Label.Application_Income_Verification_Not_Provided);
        }
        if(application.Physician_confirms_patient_inactive_tre__c == TAP_Constants.NO 
            || String.isBlank(application.Physician_confirms_patient_inactive_tre__c)) {
            comments.add(Label.Application_Active_Breast_Cancer_No);
        }
        if(application.Applicant_within_income_guideline__c == TAP_Constants.NO) {
            comments.add(Label.Application_Income_Within_Guidelines_No);
        } else if(application.Applicant_within_income_guideline__c == TAP_Constants.UNKNOWN 
                  || application.Applicant_within_income_guideline__c == Label.Application_Income_Guideline 
                  || String.isBlank(application.Applicant_within_income_guideline__c)) {
            comments.add(Label.Application_Income_Details_No);
        }
        if(application.Applicant_resides_US_Territory__c == TAP_Constants.NO) {
            comments.add(Label.Application_US_Resident_No);
        }
        if(application.Applicant_has_no_award_in_last_12months__c == TAP_Constants.NO) {
            comments.add(Label.Application_Award_In_Last_12_Months_Yes);
        }
        return comments;
    }
    
    private static String incomeGuidelinesValue(CareProgram careProgram, Application__c application) {
        String incomeGuidelinesCheckValue = TAP_Constants.NO;
        if(careProgram == null) {
            incomeGuidelinesCheckValue = Label.Application_Income_Guideline_for_Care_Program ; 
        } else if(careProgram.CProgram_Eligibility_Rules == null || careProgram.CProgram_Eligibility_Rules.size() == 0) {
            incomeGuidelinesCheckValue = Label.Application_No_Income_Guideline_On_Care_Program ; 
        } else if(application.Poverty_Level__c == null || application.Poverty_Level__c == 0) {
            incomeGuidelinesCheckValue = Label.Application_Income_Guideline ;
        } else {
            if (careProgram.CProgram_Eligibility_Rules.get(0).EligibilityCriteria.Percent_Of_Poverty_Guideline__c > application.Poverty_Level__c) {
                incomeGuidelinesCheckValue = TAP_Constants.YES;
            }
        }
        return incomeGuidelinesCheckValue;
    }
    private static Integer getUpdatedDuration(Decimal duration,Application__c application) {
        Integer newDuration = (Integer)(duration != null ? duration : 0);
        if(application.Status_Change_Date__c != null) {
            return newDuration + application.Status_Change_Date__c.date().daysBetween(System.TODAY());
        }
       return newDuration;
    }
}