unpackaged/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track Health Insurance Information for a Patient</description>
    <label>Application</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup with Account, to Populate Patient or Applicant Name.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/TAP_Inbox__c.field-meta.xml
<CustomField>
    <fullName>TAP_Inbox__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Tap Inbox, Populate Tap Inbox Id.</description>
    <label>TAP Inbox</label>
    <referenceTo>TAP_Inbox__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TAP_Inbox__c/TAP_Inbox__c.object-meta.xml
<CustomObject>
    <label>TAP Inbox</label>
    <nameField>
        <displayFormat>TAP Inbox-{0000000}</displayFormat>
        <label>TAP Inbox Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TAP Inbox</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TAP_Inbox__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>Komen_Fax_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TAP_Inbox__c/fields/Email_Body__c.field-meta.xml
<CustomField>
    <fullName>Email_Body__c</fullName>
    <label>Email Body</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/TAP_Inbox__c/fields/From_Email__c.field-meta.xml
<CustomField>
    <fullName>From_Email__c</fullName>
    <label>From: Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TAP_Inbox__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Discard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TAP_TAPInboxTrigger_Handler_Test.cls
@isTest
public class TAP_TAPInboxTrigger_Handler_Test {
    
     @testSetup static void setup() {
         //Create common test accounts
         List<Account> testaccounts = TAP_TestDataFactory.createAccount(2,'Account'); 
         // Create common test care Program
         List<CareProgram> testCarePrograms = TAP_TestDataFactory.createCareProgram(2,'careProgram');
         // Create common test application
         List<Application__c> testapplications = TAP_TestDataFactory.createApplication(1,testaccounts[0].Id,testCarePrograms[0].Id);
         List<Application__c> testapplications1 = TAP_TestDataFactory.createApplication(1,testaccounts[1].Id,testCarePrograms[1].Id);
       
         system.debug('test application id :: ' + testapplications[0].id);
        // Create common Inbox records
         List<TAP_Inbox__c> testInboxes = new List<TAP_Inbox__c>();
         for(Integer i=0;i<1;i++) {
             testInboxes.add(new TAP_Inbox__c(First_Name__c = 'User'+i, Last_Name__c = 'LName' + i, Subject__c =  'New Application Request', Status__c = 'Pending', Application__c = testapplications[0].id));
         }
         insert testInboxes;   
         
         system.debug('textInboxes :: ' + testInboxes);
         
         List<TAP_Inbox__c> testInboxes1 = new List<TAP_Inbox__c>();
         for(Integer i=0;i<1;i++) {
             testInboxes1.add(new TAP_Inbox__c(First_Name__c = 'UFN'+i, Last_Name__c = 'ULN' + i, Subject__c =  'New Application Request', Status__c = 'Pending'));
         }
         insert testInboxes1; 
         
                
       
    }
    
    @isTest
    static void TestMethod1(){
        TAP_Inbox__c objTI = [SELECT Id, First_Name__c, Last_Name__c, Subject__c, Email_Body__c, From_Email__c, Status__c, Application__c FROM TAP_Inbox__c where First_Name__c ='User0']; 
        system.assertEquals(objTI.First_Name__c,'User0');
        system.assertEquals(objTI.Status__c,'Pending');
        objTI.Subject__c = 'New App Request';
        objTI.Status__c = TAP_Constants.TAP_INBOX_STATUS_PENDING;
        update objTI;
    }
    
     @isTest
    static void TestMethod2(){
        Account objAc = [select Id from Account where LastName = 'Account1'];
        Application__c objApp = [select id from Application__c where Patient__c =: objAc.Id];
        TAP_Inbox__c objTI = [SELECT Id, First_Name__c, Last_Name__c, Subject__c, Email_Body__c, From_Email__c, Status__c, Application__c FROM TAP_Inbox__c where First_Name__c ='UFN0']; 
        system.assertEquals(objTI.First_Name__c,'UFN0');
        system.assertEquals(objTI.Status__c,'Pending');
        objTI.Subject__c = 'New App Request';
        objTI.Status__c = TAP_Constants.TAP_INBOX_STATUS_PENDING;
        objTI.Application__c = objApp.Id;
        update objTI;
    }

}