unpackaged/main/default/objects/Site_Feedback__c/Site_Feedback__c.object-meta.xml
<CustomObject>
    <label>Site Feedback</label>
    <nameField>
        <displayFormat>SF-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Site_Feedback__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>Additional comments provided by the user when submitting feedback</description>
    <label>Comments</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Site_Feedback__c/fields/Page__c.field-meta.xml
<CustomField>
    <fullName>Page__c</fullName>
    <description>The community page the user was on when they submitted feedback</description>
    <label>Page</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site_Feedback__c/fields/Positive__c.field-meta.xml
<CustomField>
    <fullName>Positive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, user clicked the &quot;Thumbs up&quot; icon. If unchecked, they clicked thumbs down</description>
    <label>Positive</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Site_Feedback__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user providing the feedback</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Site_Feedback</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/MKH_SiteFeedbackControllerTest.cls
/**
 * Tests for MKH_SiteFeedbackController
 * 
 * @author Grant Adamson, Traction on Demand
 * @date 2020-11-13
 */
@IsTest
private class MKH_SiteFeedbackControllerTest {
    @IsTest
    static void insertFeedback() {
        final Id userId = UserInfo.getUserId();
        final Boolean isPositive = true;
        final String page = '/example';
        final String comments = 'This page is great';

        MKH_SiteFeedbackController.Feedback feedback = new MKH_SiteFeedbackController.Feedback();
        feedback.user = userId;
        feedback.positive = isPositive;
        feedback.page = page;
        feedback.comments = comments;

        Test.startTest();

        MKH_SiteFeedbackController.insertFeedback(feedback);

        Test.stopTest();

        List<Site_Feedback__c> result = [SELECT Id, User__c, Positive__c, Page__c, Comments__c FROM Site_Feedback__c];
        System.assertEquals(1, result.size(), 'One record should have been inserted');

        Site_Feedback__c actual = result[0];
        Site_Feedback__c expected = new Site_Feedback__c(
                Id = actual.Id,
                User__c = userId,
                Positive__c = isPositive,
                Page__c = page,
                Comments__c = comments
        );

        System.assertEquals(expected, actual, 'The record should have the expected values');
    }
}