unpackaged/main/default/objects/Site_Feedback__c/Site_Feedback__c.object-meta.xml
<CustomObject>
    <label>Site Feedback</label>
    <nameField>
        <displayFormat>SF-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Site_Feedback__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>Additional comments provided by the user when submitting feedback</description>
    <label>Comments</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Site_Feedback__c/fields/Page__c.field-meta.xml
<CustomField>
    <fullName>Page__c</fullName>
    <description>The community page the user was on when they submitted feedback</description>
    <label>Page</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site_Feedback__c/fields/Positive__c.field-meta.xml
<CustomField>
    <fullName>Positive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, user clicked the &quot;Thumbs up&quot; icon. If unchecked, they clicked thumbs down</description>
    <label>Positive</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Site_Feedback__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user providing the feedback</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Site_Feedback</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/MKH_SiteFeedbackController.cls
/**
 * Server-side controller for Site Feedback component.
 * Necessary to prevent granting read access to site feedback records to anonymous or community users
 * 
 * @author Grant Adamson, Traction on Demand
 * @date 2020-11-13
 */
public without sharing class MKH_SiteFeedbackController {

    @AuraEnabled
    public static void insertFeedback(Feedback feedback) {
        insert new Site_Feedback__c(
                User__c = feedback.user,
                Page__c = feedback.page,
                Positive__c = feedback.positive,
                Comments__c = feedback.comments
        );
    }

    public class Feedback {
        @AuraEnabled
        public Id user { get; set; }
        @AuraEnabled
        public String page { get; set; }
        @AuraEnabled
        public Boolean positive { get; set; }
        @AuraEnabled
        public String comments { get; set; }
    }
}