unpackaged/main/default/objects/HealthCloudGA__EhrAllergyIntolerance__c/HealthCloudGA__EhrAllergyIntolerance__c.object-meta.xml
<CustomObject>
    <description>Indicates the patient has a susceptibility to an adverse reaction upon exposure to a specified substance.</description>
    <label>EHR Allergy Intolerance</label>
    <nameField>
        <displayFormat>Alle-{0}</displayFormat>
        <label>EHR Allergy Intolerance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EHR Allergy Intolerances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/HealthCloudGA__EhrAllergyIntolerance__c/fields/Allergen_Name__c.field-meta.xml
<CustomField>
    <fullName>Allergen_Name__c</fullName>
    <description>Used to capture the name of the thing the Patient is allergic to</description>
    <label>Allergen Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrAllergyIntolerance__c/fields/Allergy_Type__c.field-meta.xml
<CustomField>
    <fullName>Allergy_Type__c</fullName>
    <label>Allergy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Food Allergy</fullName>
            </value>
            <value>
                <fullName>Materials Allergy</fullName>
            </value>
            <value>
                <fullName>Medication Allergy</fullName>
            </value>
            <value>
                <fullName>Seasonal Allergy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrAllergyIntolerance__c/fields/HealthCloudGA__Reaction__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Reaction__c</fullName>
    <label>Reaction</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrAllergyIntolerance__c/fields/Reaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Reaction_Type__c</fullName>
    <label>Type of Reaction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A sense of “impending doom”</fullName>
            </value>
            <value>
                <fullName>Bloating</fullName>
            </value>
            <value>
                <fullName>Chest tightness and losing your breath</fullName>
            </value>
            <value>
                <fullName>Cough</fullName>
            </value>
            <value>
                <fullName>Diarrhea</fullName>
            </value>
            <value>
                <fullName>Feeling faint, light-headed or “blacking out”</fullName>
            </value>
            <value>
                <fullName>Hives (a rash with raised red patches)</fullName>
            </value>
            <value>
                <fullName>Itchy, watery eyes</fullName>
            </value>
            <value>
                <fullName>Itchy nose</fullName>
            </value>
            <value>
                <fullName>Pain</fullName>
            </value>
            <value>
                <fullName>Rashes</fullName>
            </value>
            <value>
                <fullName>Redness</fullName>
            </value>
            <value>
                <fullName>Runny nose</fullName>
            </value>
            <value>
                <fullName>Sneezing</fullName>
            </value>
            <value>
                <fullName>Stomach cramps</fullName>
            </value>
            <value>
                <fullName>Swelling</fullName>
            </value>
            <value>
                <fullName>Throat closing</fullName>
            </value>
            <value>
                <fullName>Tongue swelling</fullName>
            </value>
            <value>
                <fullName>Vomiting</fullName>
            </value>
            <value>
                <fullName>Wheezing (a whistling sound when you breathe)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrAllergyIntolerance__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mild</fullName>
            </value>
            <value>
                <fullName>Moderate</fullName>
            </value>
            <value>
                <fullName>Severe</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/AllergyIntoleranceSelector.cls
/* * Selector class for HealthCloudGA__EhrAllergyIntolerance__c
 *
 * @author Vikrant Upneja, Traction on Demand
 * @date 2021-01-15
 */
public with sharing class AllergyIntoleranceSelector {

    public List<HealthCloudGA__EhrAllergyIntolerance__c> selectAllergiesIntolerancesByAccId( String accountId ){
        if( String.isNotBlank( accountId ) ){
            return [SELECT Id, Name,
                    Allergy_Type__c,
                    Allergen_Name__c,
                    Reaction_Type__c,
                    HealthCloudGA__Reaction__c,
                    Severity__c ,
                    HealthCloudGA__Account__c
                    FROM HealthCloudGA__EhrAllergyIntolerance__c
                    WHERE HealthCloudGA__Account__c = :accountId];
        }
        return null;
    }
}