unpackaged/main/default/objects/Clinical_Trial__c/Clinical_Trial__c.object-meta.xml
<CustomObject>
    <label>Clinical Trial</label>
    <nameField>
        <displayFormat>CTID-{0000}</displayFormat>
        <label>Clinical Trial ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clinical_Trial__c/fields/Brief_Title__c.field-meta.xml
<CustomField>
    <fullName>Brief_Title__c</fullName>
    <label>Brief Title</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial__c/fields/Clinical_Trial_Description_Brief__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Description_Brief__c</fullName>
    <label>Clinical Trial Description Brief</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial__c/fields/Clinical_Trial_Status__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Status__c</fullName>
    <label>Clinical Trial Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial__c/fields/Clinical_Trial_Type__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Type__c</fullName>
    <label>Clinical Trial Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Intervention</fullName>
            </value>
            <value>
                <fullName>Observational</fullName>
            </value>
            <value>
                <fullName>Patient Registry</fullName>
            </value>
            <value>
                <fullName>Expanded Access</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial__c/fields/Eligibility_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Criteria__c</fullName>
    <label>Eligibility Criteria</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial__c/fields/Healthy_Volunteers__c.field-meta.xml
<CustomField>
    <fullName>Healthy_Volunteers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Healthy Volunteers</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial__c/fields/Maximum_Age__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Age__c</fullName>
    <label>Maximum Age</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial__c/fields/Minimum_Age__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Age__c</fullName>
    <label>Minimum Age</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial__c/fields/NCTId__c.field-meta.xml
<CustomField>
    <fullName>NCTId__c</fullName>
    <externalId>true</externalId>
    <label>NCTId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Early Phase 1;</fullName>
            </value>
            <value>
                <fullName>Phase 1;</fullName>
            </value>
            <value>
                <fullName>Phase 2;</fullName>
            </value>
            <value>
                <fullName>Phase 3;</fullName>
            </value>
            <value>
                <fullName>N/A;</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial__c/fields/Readable_Brief_Description__c.field-meta.xml
<CustomField>
    <fullName>Readable_Brief_Description__c</fullName>
    <label>Readable Brief Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial__c/fields/Readable_Eligibility_Summary__c.field-meta.xml
<CustomField>
    <fullName>Readable_Eligibility_Summary__c</fullName>
    <label>Readable Eligibility Summary</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial__c/fields/Readable_Title__c.field-meta.xml
<CustomField>
    <fullName>Readable_Title__c</fullName>
    <description>A handwritten, readable title - easier for Patients to understand than the ClinicalTrials.gov brief title.</description>
    <label>Readable Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial_Condition__c/Clinical_Trial_Condition__c.object-meta.xml
<CustomObject>
    <label>Clinical Trial Condition</label>
    <nameField>
        <displayFormat>CTCID-{0000}</displayFormat>
        <label>Clinical Trial Condition Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clinical_Trial_Condition__c/fields/Clinical_Trial__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial__c</fullName>
    <label>Clinical Trial</label>
    <referenceTo>Clinical_Trial__c</referenceTo>
    <relationshipLabel>Clinical Trial Conditions</relationshipLabel>
    <relationshipName>Clinical_Trial_Conditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial_Condition__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condition</label>
    <referenceTo>NLM_Condition__c</referenceTo>
    <relationshipName>Study_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial_Condition__c/fields/Condition_Name__c.field-meta.xml
<CustomField>
    <fullName>Condition_Name__c</fullName>
    <formula>Condition__r.MeSH_Heading__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Condition Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial_Criteria__c/Clinical_Trial_Criteria__c.object-meta.xml
<CustomObject>
    <label>Clinical Trial Criteria</label>
    <nameField>
        <displayFormat>CTCID-{0000}</displayFormat>
        <label>Clinical Trial Criteria Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clinical_Trial_Criteria__c/fields/Clinical_Trial__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial__c</fullName>
    <label>Clinical Trial</label>
    <referenceTo>Clinical_Trial__c</referenceTo>
    <relationshipLabel>Clinical Trial Criteria</relationshipLabel>
    <relationshipName>Clinical_Trial_Criteria</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial_Criteria__c/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <label>Criteria</label>
    <referenceTo>Criteria__c</referenceTo>
    <relationshipLabel>Clinical Trial Criteria</relationshipLabel>
    <relationshipName>Clinical_Trial_Criteria</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial_Criteria__c/fields/Include_Exclude__c.field-meta.xml
<CustomField>
    <fullName>Include_Exclude__c</fullName>
    <label>Include/Exclude</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Include</fullName>
            </value>
            <value>
                <fullName>Exclude</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial_Criteria__c/fields/Measure__c.field-meta.xml
<CustomField>
    <fullName>Measure__c</fullName>
    <label>Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Measure</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial_Criteria__c/fields/Specific_Measure__c.field-meta.xml
<CustomField>
    <fullName>Specific_Measure__c</fullName>
    <label>Specific Measure</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial_Intervention__c/Clinical_Trial_Intervention__c.object-meta.xml
<CustomObject>
    <label>Clinical Trial Intervention</label>
    <nameField>
        <displayFormat>CTIID-{0000}</displayFormat>
        <label>Clinical Trial Intervention ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Interventions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clinical_Trial_Intervention__c/fields/Clinical_Trial__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial</label>
    <referenceTo>Clinical_Trial__c</referenceTo>
    <relationshipName>NLM_Interventions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial_Intervention__c/fields/Intervention_Name__c.field-meta.xml
<CustomField>
    <fullName>Intervention_Name__c</fullName>
    <label>Intervention Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial_Patient__c/Clinical_Trial_Patient__c.object-meta.xml
<CustomObject>
    <label>Clinical Trial Patient</label>
    <nameField>
        <displayFormat>CTPID-{0000}</displayFormat>
        <label>Clinical Trial Patient ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clinical_Trial_Patient__c/fields/Clinical_Trial__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial</label>
    <referenceTo>Clinical_Trial__c</referenceTo>
    <relationshipName>Clinical_Trial_Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Criteria__c/Criteria__c.object-meta.xml
<CustomObject>
    <label>Criteria</label>
    <nameField>
        <label>Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Criteria__c/fields/NLM_Condition__c.field-meta.xml
<CustomField>
    <fullName>NLM_Condition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NLM Condition</label>
    <referenceTo>NLM_Condition__c</referenceTo>
    <relationshipLabel>Criteria</relationshipLabel>
    <relationshipName>Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NLM_Condition__c/NLM_Condition__c.object-meta.xml
<CustomObject>
    <label>NLM Condition</label>
    <nameField>
        <label>NLM Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NLM Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/globalValueSets/Measure.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Absolute Neutrophil Count</fullName>
    </customValue>
    <customValue>
        <fullName>BMI</fullName>
    </customValue>
    <customValue>
        <fullName>cm</fullName>
    </customValue>
    <customValue>
        <fullName>Count</fullName>
    </customValue>
    <customValue>
        <fullName>Creatinine</fullName>
    </customValue>
    <customValue>
        <fullName>ECOG Scale</fullName>
    </customValue>
    <customValue>
        <fullName>ml</fullName>
    </customValue>
    <customValue>
        <fullName>Percentage</fullName>
    </customValue>
    <customValue>
        <fullName>Platelets</fullName>
    </customValue>
    <customValue>
        <fullName>Stage</fullName>
    </customValue>
    <customValue>
        <fullName>True/False</fullName>
    </customValue>
    <customValue>
        <fullName>μL</fullName>
    </customValue>
    <masterLabel>Measure</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not yet recruiting</fullName>
    </customValue>
    <customValue>
        <fullName>Recruiting</fullName>
    </customValue>
    <customValue>
        <fullName>Enrolling by invitation</fullName>
    </customValue>
    <customValue>
        <fullName>Active, not recruiting</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Suspended</fullName>
    </customValue>
    <customValue>
        <fullName>Terminated</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown Status</fullName>
    </customValue>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ClinicalTrialsSelector.cls
/**
 * Selector for Clinical Trial records
 * 
 * @author Grant Adamson, Traction on Demand
 * @date 2020-05-28
 */
public inherited sharing class ClinicalTrialsSelector {

    public List<Clinical_Trial__c> selectAllVisible(Integer recordLimit) {
        return [
                SELECT NCTId__c, Name, Brief_Title__c, Readable_Title__c, Clinical_Trial_Type__c, Phase__c,
                (
                        SELECT Condition_Name__c
                        FROM Clinical_Trial_Conditions__r
                        WHERE Condition__r.Non_MeSH_Condition__c = TRUE
                        ORDER BY Name
                ), (
                        SELECT Id
                        FROM Clinical_Trial_Patients__r
                        WHERE OwnerId = :UserInfo.getUserId()
                )
                FROM Clinical_Trial__c
                WHERE Clinical_Trial_Status__c IN :ClinicalTrials.VISIBLE_STATUSES
                ORDER BY Name
                LIMIT :recordLimit
        ];
    }

    public List<Clinical_Trial__c> selectById(Set<Id> recordIds) {
        return [
                SELECT NCTId__c, Name, Brief_Title__c, Readable_Title__c, Clinical_Trial_Type__c, Phase__c,
                (
                        SELECT Condition_Name__c
                        FROM Clinical_Trial_Conditions__r
                        WHERE Condition__r.Non_MeSH_Condition__c = TRUE
                        ORDER BY Name
                ), (
                        SELECT Id
                        FROM Clinical_Trial_Patients__r
                        WHERE OwnerId = :UserInfo.getUserId()
                )
                FROM Clinical_Trial__c
                WHERE Id IN :recordIds
                ORDER BY Name
        ];
    }

    public List<Clinical_Trial__c> selectByIdWithChildren(Set<Id> recordIds) {
        return [
                SELECT NCTId__c, Name, Brief_Title__c, Readable_Title__c, Clinical_Trial_Type__c, Organization__c,
                        Minimum_Age__c, Maximum_Age__c, Gender__c, Healthy_Volunteers__c, Phase__c,
                        Readable_Brief_Description__c, Clinical_Trial_Description_Brief__c,
                        Readable_Eligibility_Summary__c, Eligibility_Criteria__c,
                (
                        SELECT Condition_Name__c, Condition__r.Description__c
                        FROM Clinical_Trial_Conditions__r
                        WHERE Condition__r.Non_MeSH_Condition__c = TRUE
                        ORDER BY Name
                ), (
                        SELECT Id
                        FROM Clinical_Trial_Patients__r
                        WHERE OwnerId = :UserInfo.getUserId()
                ), (
                        SELECT Intervention_Name__c, Description__c
                        FROM NLM_Interventions__r
                ), (
                        SELECT Criteria__r.Name, Include_Exclude__c, Measure__c, Specific_Measure__c
                        FROM Clinical_Trial_Criteria__r
                )
                FROM Clinical_Trial__c
                WHERE Id IN :recordIds
        ];
    }
}