unpackaged/main/default/objects/Clinical_Trial__c/Clinical_Trial__c.object-meta.xml
<CustomObject>
    <label>Clinical Trial</label>
    <nameField>
        <displayFormat>CTID-{0000}</displayFormat>
        <label>Clinical Trial ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clinical_Trial__c/fields/Clinical_Trial_Status__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Status__c</fullName>
    <label>Clinical Trial Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial_Location__c/Clinical_Trial_Location__c.object-meta.xml
<CustomObject>
    <label>Clinical Trial Location</label>
    <nameField>
        <displayFormat>CTLID-{0000}</displayFormat>
        <label>Clinical Trial Location Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clinical_Trial_Location__c/fields/Clinical_Trial__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial__c</fullName>
    <label>Clinical Trial</label>
    <referenceTo>Clinical_Trial__c</referenceTo>
    <relationshipLabel>Clinical Trial Locations</relationshipLabel>
    <relationshipName>Clinical_Trial_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial_Location__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <label>Facility</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial_Location__c/fields/Geocode__c.field-meta.xml
<CustomField>
    <fullName>Geocode__c</fullName>
    <label>Geocode</label>
    <scale>0</scale>
    <type>Location</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial_Location__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial_Location__c/fields/Trial_Location_Key__c.field-meta.xml
<CustomField>
    <fullName>Trial_Location_Key__c</fullName>
    <description>To attempt to avoid duplicating Trial &amp; Location information</description>
    <externalId>true</externalId>
    <label>Trial Location Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not yet recruiting</fullName>
    </customValue>
    <customValue>
        <fullName>Recruiting</fullName>
    </customValue>
    <customValue>
        <fullName>Enrolling by invitation</fullName>
    </customValue>
    <customValue>
        <fullName>Active, not recruiting</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Suspended</fullName>
    </customValue>
    <customValue>
        <fullName>Terminated</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown Status</fullName>
    </customValue>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ClinicalTrialLocationsSelector.cls
/**
 * Selector for Clinical Trial Location records
 * 
 * @author Grant Adamson, Traction on Demand
 * @date 2020-05-28
 */
public inherited sharing class ClinicalTrialLocationsSelector {

    public List<Clinical_Trial_Location__c> selectByTrialId(Set<Id> trialIds) {
        return [
                SELECT Trial_Location_Key__c, Clinical_Trial__c, Geocode__Latitude__s, Geocode__Longitude__s,
                        Facility__c, Street_Address__c, City__c, State__c, Country__c, Zip__c
                FROM Clinical_Trial_Location__c
                WHERE Clinical_Trial__c IN :trialIds
        ];
    }

    public List<Clinical_Trial_Location__c> selectByTrialIdWithDistance(Set<Id> trialIds, Double latitude,
            Double longitude) {

        return [
                SELECT Trial_Location_Key__c, Clinical_Trial__c, Geocode__Latitude__s, Geocode__Longitude__s,
                        DISTANCE(Geocode__c, GEOLOCATION(:latitude, :longitude), 'mi') dist,
                        Facility__c, Street_Address__c, City__c, State__c, Country__c, Zip__c
                FROM Clinical_Trial_Location__c
                WHERE Clinical_Trial__c IN :trialIds
                ORDER BY DISTANCE(Geocode__c, GEOLOCATION(:latitude, :longitude), 'mi') NULLS LAST
        ];
    }
    public List<Clinical_Trial_Location__c> selectVisibleByDistance(Double latitude, Double longitude,
            Integer maxDistance) {

        return [
                SELECT Trial_Location_Key__c, Clinical_Trial__c, Geocode__Latitude__s, Geocode__Longitude__s,
                        DISTANCE(Geocode__c, GEOLOCATION(:latitude, :longitude), 'mi') dist
                FROM Clinical_Trial_Location__c
                WHERE Clinical_Trial__r.Clinical_Trial_Status__c IN :ClinicalTrials.VISIBLE_STATUSES
                AND DISTANCE(Geocode__c, GEOLOCATION(:latitude, :longitude), 'mi') < :maxDistance
                ORDER BY DISTANCE(Geocode__c, GEOLOCATION(:latitude, :longitude), 'mi') NULLS LAST
        ];
    }

    public List<Clinical_Trial_Location__c> selectAllVisibleWithDistance(Double latitude, Double longitude) {

        return [
                SELECT Trial_Location_Key__c, Clinical_Trial__c, Geocode__Latitude__s, Geocode__Longitude__s,
                        DISTANCE(Geocode__c, GEOLOCATION(:latitude, :longitude), 'mi') dist
                FROM Clinical_Trial_Location__c
                WHERE Clinical_Trial__r.Clinical_Trial_Status__c IN :ClinicalTrials.VISIBLE_STATUSES
                ORDER BY DISTANCE(Geocode__c, GEOLOCATION(:latitude, :longitude), 'mi') NULLS LAST
        ];
    }

}