unpackaged/main/default/objects/Clinical_Trial__c/Clinical_Trial__c.object-meta.xml
<CustomObject>
    <label>Clinical Trial</label>
    <nameField>
        <displayFormat>CTID-{0000}</displayFormat>
        <label>Clinical Trial ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clinical_Trial_Patient__c/Clinical_Trial_Patient__c.object-meta.xml
<CustomObject>
    <label>Clinical Trial Patient</label>
    <nameField>
        <displayFormat>CTPID-{0000}</displayFormat>
        <label>Clinical Trial Patient ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clinical_Trial_Patient__c/fields/Clinical_Trial__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial</label>
    <referenceTo>Clinical_Trial__c</referenceTo>
    <relationshipName>Clinical_Trial_Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ClinicalTrialPatientsSelectorTest.cls
/**
 * Tests for ClinicalTrialPatientsSelector
 * 
 * @author Grant Adamson, Traction on Demand
 * @date 2020-06-01
 */
@IsTest
private class ClinicalTrialPatientsSelectorTest {
    @TestSetup
    static void setup() {
        ClinicalTrialsTestDataFactory.insertTrialsAndTrialPatients();
    }

    @IsTest
    static void selectByTrialIdAndUserId() {
        Clinical_Trial__c trial = ClinicalTrialsTestDataFactory.getTrial();
        Clinical_Trial__c trial2 = ClinicalTrialsTestDataFactory.getTrial2();
        Set<Id> trialIds = new Set<Id>{ trial.Id, trial2.Id };

        Test.startTest();

        List<Clinical_Trial_Patient__c> result = new ClinicalTrialPatientsSelector()
                .selectByTrialIdAndUserId(trialIds, new Set<Id>{ UserInfo.getUserId() });

        Test.stopTest();

        System.assertEquals(1, result.size(), 'One record should be returned');
        System.assertEquals(trial2.Id, result[0].Clinical_Trial__c,
                'It should be the record associated with clinical trial 2');
    }
}