unpackaged/main/default/objects/Clinical_Trial__c/Clinical_Trial__c.object-meta.xml
<CustomObject>
    <label>Clinical Trial</label>
    <nameField>
        <displayFormat>CTID-{0000}</displayFormat>
        <label>Clinical Trial ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clinical_Trial__c/fields/Clinical_Trial_Status__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Status__c</fullName>
    <label>Clinical Trial Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial__c/fields/NCTId__c.field-meta.xml
<CustomField>
    <fullName>NCTId__c</fullName>
    <externalId>true</externalId>
    <label>NCTId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial_Location__c/Clinical_Trial_Location__c.object-meta.xml
<CustomObject>
    <label>Clinical Trial Location</label>
    <nameField>
        <displayFormat>CTLID-{0000}</displayFormat>
        <label>Clinical Trial Location Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clinical_Trial_Location__c/fields/Clinical_Trial__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial__c</fullName>
    <label>Clinical Trial</label>
    <referenceTo>Clinical_Trial__c</referenceTo>
    <relationshipLabel>Clinical Trial Locations</relationshipLabel>
    <relationshipName>Clinical_Trial_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial_Location__c/fields/Trial_Location_Key__c.field-meta.xml
<CustomField>
    <fullName>Trial_Location_Key__c</fullName>
    <description>To attempt to avoid duplicating Trial &amp; Location information</description>
    <externalId>true</externalId>
    <label>Trial Location Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial_Patient__c/Clinical_Trial_Patient__c.object-meta.xml
<CustomObject>
    <label>Clinical Trial Patient</label>
    <nameField>
        <displayFormat>CTPID-{0000}</displayFormat>
        <label>Clinical Trial Patient ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clinical_Trial_Patient__c/fields/Clinical_Trial__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial</label>
    <referenceTo>Clinical_Trial__c</referenceTo>
    <relationshipName>Clinical_Trial_Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not yet recruiting</fullName>
    </customValue>
    <customValue>
        <fullName>Recruiting</fullName>
    </customValue>
    <customValue>
        <fullName>Enrolling by invitation</fullName>
    </customValue>
    <customValue>
        <fullName>Active, not recruiting</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Suspended</fullName>
    </customValue>
    <customValue>
        <fullName>Terminated</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown Status</fullName>
    </customValue>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ClinicalTrialsTestDataFactory.cls
/**
 * Test data factory for clinical trials tests
 * 
 * @author Grant Adamson, Traction on Demand
 * @date 2020-06-01
 */
@IsTest
public class ClinicalTrialsTestDataFactory {
    public static final String TRIAL_1_NCTID = '111111111111';
    public static final String TRIAL_2_NCTID = '222222222222';
    public static final String TRIAL_3_NCTID = '333333333333';

    public static final String LOC_1_KEY = 'LOCATION1';
    public static final Double LOC_1_LATITUDE = 49.2598906;
    public static final Double LOC_1_LONGITUDE = -122.9179885;

    public static final String LOC_2_KEY = 'LOCATION2';
    public static final Double LOC_2_LATITUDE= 43.6459318;
    public static final Double LOC_2_LONGITUDE = -79.5240142;

    public static final String LOC_3_KEY = 'LOCATION3';

    public static void insertTrialsAndTrialPatients() {
        List<Clinical_Trial__c> trials = insertTrials();
        insert new Clinical_Trial_Patient__c(Clinical_Trial__c = trials[1].Id);
    }

    public static void insertTrialsAndLocations() {
        List<Clinical_Trial__c> trials = insertTrials();

        Clinical_Trial_Location__c loc = new Clinical_Trial_Location__c(
                Clinical_Trial__c = trials[0].Id,
                Trial_Location_Key__c = LOC_1_KEY,
                Geocode__Latitude__s = LOC_1_LATITUDE,
                Geocode__Longitude__s = LOC_1_LONGITUDE
        );
        Clinical_Trial_Location__c loc2 = new Clinical_Trial_Location__c(
                Clinical_Trial__c = trials[1].Id,
                Trial_Location_Key__c = LOC_2_KEY,
                Geocode__Latitude__s = LOC_2_LATITUDE,
                Geocode__Longitude__s = LOC_2_LONGITUDE
        );
        Clinical_Trial_Location__c loc3 = new Clinical_Trial_Location__c(
                Clinical_Trial__c = trials[2].Id,
                Trial_Location_Key__c = LOC_3_KEY
        );
        insert new Clinical_Trial_Location__c[]{ loc, loc2, loc3 };
    }

    private static List<Clinical_Trial__c> insertTrials() {
        Clinical_Trial__c trial = new Clinical_Trial__c(
                NCTId__c = TRIAL_1_NCTID,
                Clinical_Trial_Status__c = 'Recruiting'
        );
        Clinical_Trial__c trial2 = new Clinical_Trial__c(
                NCTId__c = TRIAL_2_NCTID,
                Clinical_Trial_Status__c = 'Recruiting'
        );
        Clinical_Trial__c trial3 = new Clinical_Trial__c(
                NCTId__c = TRIAL_3_NCTID,
                Clinical_Trial_Status__c = 'Completed'
        );

        List<Clinical_Trial__c> trials = new List<Clinical_Trial__c>{ trial, trial2, trial3 };
        insert trials;

        return trials;
    }

    public static Clinical_Trial__c getTrial() {
        return getTrialByNCTId(TRIAL_1_NCTID);
    }

    public static Clinical_Trial__c getTrial2() {
        return getTrialByNCTId(TRIAL_2_NCTID);
    }

    public static Clinical_Trial__c getTrial3() {
        return getTrialByNCTId(TRIAL_3_NCTID);
    }

    private static Clinical_Trial__c getTrialByNCTId(String nctId) {
        if(clinicalTrialsByNCTId == null) {
            clinicalTrialsByNCTId = new Map<String, Clinical_Trial__c>();

            for (Clinical_Trial__c trial : [SELECT NCTId__c FROM Clinical_Trial__c ORDER BY NCTId__c]) {
                clinicalTrialsByNCTId.put(trial.NCTId__c, trial);
            }
        }

        return clinicalTrialsByNCTId.get(nctId);
    }

    private static Map<String, Clinical_Trial__c> clinicalTrialsByNCTId;
}