unpackaged/main/default/objects/Clinical_Trial__c/Clinical_Trial__c.object-meta.xml
<CustomObject>
    <label>Clinical Trial</label>
    <nameField>
        <displayFormat>CTID-{0000}</displayFormat>
        <label>Clinical Trial ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clinical_Trial__c/fields/NCTId__c.field-meta.xml
<CustomField>
    <fullName>NCTId__c</fullName>
    <externalId>true</externalId>
    <label>NCTId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Clinical_Trial_Patient__c/Clinical_Trial_Patient__c.object-meta.xml
<CustomObject>
    <label>Clinical Trial Patient</label>
    <nameField>
        <displayFormat>CTPID-{0000}</displayFormat>
        <label>Clinical Trial Patient ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clinical_Trial_Patient__c/fields/Clinical_Trial__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial</label>
    <referenceTo>Clinical_Trial__c</referenceTo>
    <relationshipName>Clinical_Trial_Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ClinicalTrialsSelectorTest.cls
/**
 * Tests for ClinicalTrialsSelector
 * 
 * @author Grant Adamson, Traction on Demand
 * @date 2020-06-01
 */
@IsTest
private class ClinicalTrialsSelectorTest {

    @TestSetup
    static void setup() {
        ClinicalTrialsTestDataFactory.insertTrialsAndTrialPatients();
    }

    @IsTest
    static void selectAllVisible() {
        Test.startTest();

        List<Clinical_Trial__c> result = new ClinicalTrialsSelector().selectAllVisible(10);

        Test.stopTest();

        System.assertEquals(2, result.size());

        System.assertEquals(ClinicalTrialsTestDataFactory.TRIAL_1_NCTID, result[0].NCTId__c,
                'The first record should be the expected record');
        System.assertEquals(0, result[0].Clinical_Trial_Patients__r.size(), 'No patient records should be returned');

        System.assertEquals(ClinicalTrialsTestDataFactory.TRIAL_2_NCTID, result[1].NCTId__c,
                'The second record should be the expected record');
        System.assertEquals(1, result[1].Clinical_Trial_Patients__r.size(), 'One patient record should be returned');
    }

    @IsTest
    static void selectById() {
        Clinical_Trial__c trial3 = ClinicalTrialsTestDataFactory.getTrial3();

        Test.startTest();

        List<Clinical_Trial__c> result = new ClinicalTrialsSelector().selectById(new Set<Id>{ trial3.Id });

        Test.stopTest();

        System.assertEquals(1, result.size());

        System.assertEquals(ClinicalTrialsTestDataFactory.TRIAL_3_NCTID, result[0].NCTId__c,
                'The first record should be the expected record');
        System.assertEquals(0, result[0].Clinical_Trial_Patients__r.size(), 'No patient records should be returned');
    }

    @IsTest
    static void selectByIdWithChildren() {
        Clinical_Trial__c trial2 = ClinicalTrialsTestDataFactory.getTrial2();
        Clinical_Trial__c trial3 = ClinicalTrialsTestDataFactory.getTrial3();

        Test.startTest();

        List<Clinical_Trial__c> result =
                new ClinicalTrialsSelector().selectByIdWithChildren(new Set<Id>{ trial2.Id, trial3.Id });

        Test.stopTest();

        System.assertEquals(2, result.size());

        System.assertEquals(ClinicalTrialsTestDataFactory.TRIAL_2_NCTID, result[0].NCTId__c,
                'The second record should be the expected record');
        System.assertEquals(1, result[0].Clinical_Trial_Patients__r.size(), 'One patient record should be returned');

        System.assertEquals(ClinicalTrialsTestDataFactory.TRIAL_3_NCTID, result[1].NCTId__c,
                'The first record should be the expected record');
        System.assertEquals(0, result[1].Clinical_Trial_Patients__r.size(), 'No patient records should be returned');
    }
}