unpackaged/main/default/objects/Clinical_Trial__c/Clinical_Trial__c.object-meta.xml
<CustomObject>
    <label>Clinical Trial</label>
    <nameField>
        <displayFormat>CTID-{0000}</displayFormat>
        <label>Clinical Trial ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clinical_Trial_Patient__c/Clinical_Trial_Patient__c.object-meta.xml
<CustomObject>
    <label>Clinical Trial Patient</label>
    <nameField>
        <displayFormat>CTPID-{0000}</displayFormat>
        <label>Clinical Trial Patient ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clinical_Trial_Patient__c/fields/Clinical_Trial__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial</label>
    <referenceTo>Clinical_Trial__c</referenceTo>
    <relationshipName>Clinical_Trial_Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ClinicalTrialPatientsSelector.cls
/**
 * Selector for Clinical Trial Patient records
 * 
 * @author Grant Adamson, Traction on Demand
 * @date 2020-05-28
 */
public inherited sharing class ClinicalTrialPatientsSelector {

    public List<Clinical_Trial_Patient__c> selectByTrialIdAndUserId(Set<Id> trialIds, Set<Id> userIds) {
        return [
                SELECT Clinical_Trial__c, OwnerId
                FROM Clinical_Trial_Patient__c
                WHERE Clinical_Trial__c IN :trialIds
                AND OwnerId IN :userIds
        ];
    }
}