unpackaged/main/default/objects/MyKomen_Setting__mdt/MyKomen_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Various settings related to the MyKomen community. These may vary by org or be the same in all environments</description>
    <label>MyKomen Setting</label>
    <pluralLabel>MyKomen Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/MyKomen_Setting__mdt/fields/Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Org_Id__c</fullName>
    <defaultValue>$Organization.Id</defaultValue>
    <description>The specific org Id this setting applies to. Defaults to the current org, can be cleared to apply to ALL orgs</description>
    <label>Org Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/MK_MyKomenSettingsSelectorImpl.cls
/**
 * Selector for MyKomen Setting custom metadata
 * 
 * @author Grant Adamson, Traction on Demand
 * @date 2020-09-16
 */
public inherited sharing class MK_MyKomenSettingsSelectorImpl implements MK_MyKomenSettingsSelector {
    public List<MyKomen_Setting__mdt> selectByKeyAndOptionalOrgId(String key, Id orgId) {
        return [
                SELECT Value__c
                FROM MyKomen_Setting__mdt
                WHERE Key__c = :key
                AND (Org_Id__c = :orgId OR Org_Id__c = NULL)
                ORDER BY Org_Id__c NULLS LAST
        ];
    }
}