unpackaged/main/default/objects/HealthCloudGA__ContactContactRelation__c/HealthCloudGA__ContactContactRelation__c.object-meta.xml
<CustomObject>
    <description>A relationship between any two individuals.</description>
    <label>Contact-Contact Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Contact Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Contact Relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/HealthCloudGA__EhrAllergyIntolerance__c/HealthCloudGA__EhrAllergyIntolerance__c.object-meta.xml
<CustomObject>
    <description>Indicates the patient has a susceptibility to an adverse reaction upon exposure to a specified substance.</description>
    <label>EHR Allergy Intolerance</label>
    <nameField>
        <displayFormat>Alle-{0}</displayFormat>
        <label>EHR Allergy Intolerance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EHR Allergy Intolerances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/HealthCloudGA__EhrAllergyIntolerance__c/fields/Allergen_Name__c.field-meta.xml
<CustomField>
    <fullName>Allergen_Name__c</fullName>
    <description>Used to capture the name of the thing the Patient is allergic to</description>
    <label>Allergen Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrAllergyIntolerance__c/fields/Allergy_Type__c.field-meta.xml
<CustomField>
    <fullName>Allergy_Type__c</fullName>
    <label>Allergy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Food Allergy</fullName>
            </value>
            <value>
                <fullName>Materials Allergy</fullName>
            </value>
            <value>
                <fullName>Medication Allergy</fullName>
            </value>
            <value>
                <fullName>Seasonal Allergy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrAllergyIntolerance__c/fields/HealthCloudGA__Reaction__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Reaction__c</fullName>
    <label>Reaction</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrAllergyIntolerance__c/fields/Medication__c.field-meta.xml
<CustomField>
    <fullName>Medication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Medication object for the medication someone is allergic to.</description>
    <label>Medication</label>
    <referenceTo>Medication__c</referenceTo>
    <relationshipLabel>Allergy Intolerances</relationshipLabel>
    <relationshipName>Allergy_Intolerances</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrAllergyIntolerance__c/fields/Reaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Reaction_Type__c</fullName>
    <label>Type of Reaction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A sense of “impending doom”</fullName>
            </value>
            <value>
                <fullName>Bloating</fullName>
            </value>
            <value>
                <fullName>Chest tightness and losing your breath</fullName>
            </value>
            <value>
                <fullName>Cough</fullName>
            </value>
            <value>
                <fullName>Diarrhea</fullName>
            </value>
            <value>
                <fullName>Feeling faint, light-headed or “blacking out”</fullName>
            </value>
            <value>
                <fullName>Hives (a rash with raised red patches)</fullName>
            </value>
            <value>
                <fullName>Itchy, watery eyes</fullName>
            </value>
            <value>
                <fullName>Itchy nose</fullName>
            </value>
            <value>
                <fullName>Pain</fullName>
            </value>
            <value>
                <fullName>Rashes</fullName>
            </value>
            <value>
                <fullName>Redness</fullName>
            </value>
            <value>
                <fullName>Runny nose</fullName>
            </value>
            <value>
                <fullName>Sneezing</fullName>
            </value>
            <value>
                <fullName>Stomach cramps</fullName>
            </value>
            <value>
                <fullName>Swelling</fullName>
            </value>
            <value>
                <fullName>Throat closing</fullName>
            </value>
            <value>
                <fullName>Tongue swelling</fullName>
            </value>
            <value>
                <fullName>Vomiting</fullName>
            </value>
            <value>
                <fullName>Wheezing (a whistling sound when you breathe)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrAllergyIntolerance__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mild</fullName>
            </value>
            <value>
                <fullName>Moderate</fullName>
            </value>
            <value>
                <fullName>Severe</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrEncounter__c/HealthCloudGA__EhrEncounter__c.object-meta.xml
<CustomObject>
    <label>EHR Encounter</label>
    <nameField>
        <displayFormat>Enco-{0}</displayFormat>
        <label>EHR Encounter ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EHR Encounters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/HealthCloudGA__EhrEncounter__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the appointment</description>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrImmunization__c/HealthCloudGA__EhrImmunization__c.object-meta.xml
<CustomObject>
    <description>Immunization event information.</description>
    <label>EHR Immunization</label>
    <nameField>
        <displayFormat>Immu-{0}</displayFormat>
        <label>EHR Immunization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EHR Immunizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/HealthCloudGA__EhrImmunization__c/fields/Immunization_Type__c.field-meta.xml
<CustomField>
    <fullName>Immunization_Type__c</fullName>
    <description>List from https://www.cdc.gov/vaccines/vpd/vaccines-list.html</description>
    <label>Immunization Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Adenovirus</fullName>
            </value>
            <value>
                <fullName>Anthrax</fullName>
            </value>
            <value>
                <fullName>Cholera</fullName>
            </value>
            <value>
                <fullName>Diphtheria</fullName>
            </value>
            <value>
                <fullName>Haemophilus influenzae type b (Hib)</fullName>
            </value>
            <value>
                <fullName>Hepatitis A</fullName>
            </value>
            <value>
                <fullName>Hepatitis B</fullName>
            </value>
            <value>
                <fullName>Human Papillomavirus (HPV)</fullName>
            </value>
            <value>
                <fullName>Japanese Encephalitis</fullName>
            </value>
            <value>
                <fullName>Measles</fullName>
            </value>
            <value>
                <fullName>Meningococcal</fullName>
            </value>
            <value>
                <fullName>Mumps</fullName>
            </value>
            <value>
                <fullName>Pertussis</fullName>
            </value>
            <value>
                <fullName>Pneumococcal</fullName>
            </value>
            <value>
                <fullName>Polio</fullName>
            </value>
            <value>
                <fullName>Rabies</fullName>
            </value>
            <value>
                <fullName>Rotavirus</fullName>
            </value>
            <value>
                <fullName>Rubella</fullName>
            </value>
            <value>
                <fullName>Seasonal Influenza (Flu) only</fullName>
            </value>
            <value>
                <fullName>Shingles</fullName>
            </value>
            <value>
                <fullName>Smallpox</fullName>
            </value>
            <value>
                <fullName>Tetanus</fullName>
            </value>
            <value>
                <fullName>Tuberculosis</fullName>
            </value>
            <value>
                <fullName>Typhoid Fever</fullName>
            </value>
            <value>
                <fullName>Varicella</fullName>
            </value>
            <value>
                <fullName>Yellow Fever</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrMedicationStatement__c/HealthCloudGA__EhrMedicationStatement__c.object-meta.xml
<CustomObject>
    <description>A record of medication being taken by a patient, or that the medication has been given to a patient where the record is the result of a report from the patient or another clinician.</description>
    <label>EHR Medication Statement</label>
    <nameField>
        <displayFormat>Stat-{0}</displayFormat>
        <label>EHR Medication Statement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EHR Medication Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/HealthCloudGA__EhrMedicationStatement__c/fields/Medication__c.field-meta.xml
<CustomField>
    <fullName>Medication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medication</label>
    <referenceTo>Medication__c</referenceTo>
    <relationshipLabel>Medication Statements</relationshipLabel>
    <relationshipName>Medication_Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__ReciprocalRole__c/HealthCloudGA__ReciprocalRole__c.object-meta.xml
<CustomObject>
    <description>Represents the other entity’s corresponding role in a one-to-one relationship between entities.</description>
    <label>Reciprocal Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reciprocal Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/HealthCloudGA__ReciprocalRole__c/fields/HealthCloudGA__InverseRole__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__InverseRole__c</fullName>
    <label>Inverse Role</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Knowledge__kav/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <label>Resource Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Article</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Medication__c/Medication__c.object-meta.xml
<CustomObject>
    <description>Holds information about medications in use by Patients.  Intended to be populated either manually, or via integration with an API.</description>
    <label>Medication</label>
    <nameField>
        <label>Medication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Medication__c/fields/Med_Name__c.field-meta.xml
<CustomField>
    <fullName>Med_Name__c</fullName>
    <label>Med Name</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Referral_Record__c/Referral_Record__c.object-meta.xml
<CustomObject>
    <label>Referral Record</label>
    <nameField>
        <displayFormat>RR-{00000}</displayFormat>
        <label>Referral Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Referral_Record__c/fields/Featured__c.field-meta.xml
<CustomField>
    <fullName>Featured__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Featured</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Referral_Record__c/fields/Knowledge_Article_Referred__c.field-meta.xml
<CustomField>
    <fullName>Knowledge_Article_Referred__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Knowledge Article Referred</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Referral Records</relationshipLabel>
    <relationshipName>Referral_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Referral_Record__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referral Records</relationshipLabel>
    <relationshipName>Referral_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/KHC_TestUtility.cls
/**
 * Test Utility class to hold KHC related objects and methods
 * 
 * @author Nitin Chandwani, Traction on Demand
 * @date 2020-09-10
 */
@isTest
public class KHC_TestUtility {
    
    public static List<Medication__c> insertMedications( String medicationName, Integer count, Boolean performDml ){
        List<Medication__c> medications = new List<Medication__c>();
        for( Integer i = 0; i < count; i ++ ){
            medications.add( insertMedication( medicationName + i, false ) );
        }
        if( performDml ){
            INSERT medications;
        }
        return medications;
    }

    public static Medication__c insertMedication( String medicationName, Boolean performDml ){
        Medication__c medication = new Medication__c();
        medication.Med_Name__c  = medicationName;
        if( performDml ){
            INSERT medication;
        }
        return medication;
    }

    public static HealthCloudGA__EhrMedicationStatement__c insertEhrMedicationStatement( Id medicationId, Id personAccountId, Boolean performDml ){
        HealthCloudGA__EhrMedicationStatement__c medicationStatement = new HealthCloudGA__EhrMedicationStatement__c();
        medicationStatement.Medication__c = medicationId;
        medicationStatement.HealthCloudGA__Account__c = personAccountId;
        if( performDml ){
            INSERT medicationStatement;
        }
        return medicationStatement;
    }

    public static List<HealthCloudGA__EhrImmunization__c> insertEhrImmunizations( Id personAccountId, String immunizationType, Integer count, Boolean performDml){
        List<HealthCloudGA__EhrImmunization__c> immunizations = new List<HealthCloudGA__EhrImmunization__c>();
        for( Integer i = 0; i < count; i ++ ){
            immunizations.add( insertEhrImmunization( personAccountId, immunizationType, false ) );
        }
        if( performDml ){
            INSERT immunizations;
        }
        return immunizations;
    }

    public static HealthCloudGA__EhrImmunization__c insertEhrImmunization( Id personAccountId, String immunizationType, Boolean performDml ){
        HealthCloudGA__EhrImmunization__c immunization = new HealthCloudGA__EhrImmunization__c();
        immunization.HealthCloudGA__DateAdministered__c = System.today();
        immunization.HealthCloudGA__Account__c = personAccountId;
        immunization.Immunization_Type__c = immunizationType;
        if( performDml ){
            INSERT immunization;
        }
        return immunization;
    }

    public static List<HealthCloudGA__ReciprocalRole__c> insertReciprocalRoles( Map<String,String> rolesMap, Boolean performDml ){
        List<HealthCloudGA__ReciprocalRole__c> reciprocalRoles = new List<HealthCloudGA__ReciprocalRole__c>();
        for( String role : rolesMap.keySet() ){
            reciprocalRoles.add( insertReciprocalRole( role, rolesMap.get( role ), false ) );
        }
        if( performDml ){
            INSERT reciprocalRoles;
        }
        return reciprocalRoles;
    }

    public static HealthCloudGA__ReciprocalRole__c insertReciprocalRole( String roleName, String inverseRoleName, Boolean performDml ){
        HealthCloudGA__ReciprocalRole__c reciprocalRole = new HealthCloudGA__ReciprocalRole__c();
        reciprocalRole.Name = roleName;
        reciprocalRole.RecordTypeId = Schema.SObjectType.HealthCloudGA__ReciprocalRole__c.getRecordTypeInfosByName().get('Contact Role').getRecordTypeId();
        reciprocalRole.HealthCloudGA__InverseRole__c = inverseRoleName;
        if( performDml ){
            INSERT reciprocalRole;
        }
        return reciprocalRole;
    }

    public static HealthCloudGA__ContactContactRelation__c insertConConRel( Id relContactId, Id conId, Id roleId , Boolean performDml ){
        HealthCloudGA__ContactContactRelation__c conConRel = new HealthCloudGA__ContactContactRelation__c();
        conConRel.HealthCloudGA__Role__c = roleId;
        conConRel.HealthCloudGA__Contact__c = conId;
        conConRel.HealthCloudGA__RelatedContact__c = relContactId;
        if( performDml ){
            INSERT conConRel;
        }
        return conConRel;
    }

    public static HealthCloudGA__EhrAllergyIntolerance__c insertEhrAllergyIntolerance( Id personAccountId, String allergyType, String reactionType, Boolean performDml ){

        HealthCloudGA__EhrAllergyIntolerance__c allergyIntolerance = new HealthCloudGA__EhrAllergyIntolerance__c();

        allergyIntolerance.Allergy_Type__c = allergyType;
        allergyIntolerance.Allergen_Name__c = 'Test Allergy';
        allergyIntolerance.Reaction_Type__c = ReactionType;
        allergyIntolerance.HealthCloudGA__Reaction__c = 'Test Allergy';
        allergyIntolerance.Severity__c = 'Mild';
        allergyIntolerance.HealthCloudGA__Account__c = personAccountId;

        if( performDml ){
            INSERT allergyIntolerance;
        }
        return allergyIntolerance;
    }

    public static List<HealthCloudGA__EhrAllergyIntolerance__c> insertEhrAllergyIntolerances( Id personAccountId, String allergyType,  String reactionType, Integer count, Boolean performDml){
        List<HealthCloudGA__EhrAllergyIntolerance__c> allergies = new List<HealthCloudGA__EhrAllergyIntolerance__c>();
        for( Integer i = 0; i < count; i ++ ){
            allergies.add( insertEhrAllergyIntolerance( personAccountId, allergyType, reactionType,false ) );
        }
        if( performDml ){
            INSERT allergies;
        }
        return allergies;
    }

    public static List<HealthCloudGA__EhrEncounter__c> insertEhrEncounters( Id personAccountId, String providerName, Integer count, Boolean performDml){
        List<HealthCloudGA__EhrEncounter__c> encounters = new List<HealthCloudGA__EhrEncounter__c>();
        for( Integer i = 0; i < count; i ++ ){
            encounters.add( insertEhrEncounter( personAccountId, providerName, false ) );
        }
        if( performDml ){
            INSERT encounters;
        }
        return encounters;
    }

    public static HealthCloudGA__EhrEncounter__c insertEhrEncounter( Id personAccountId, String providerName, Boolean performDml ){
        HealthCloudGA__EhrEncounter__c encounter = new HealthCloudGA__EhrEncounter__c();
        encounter.Appointment_Date__c = System.today();
        encounter.HealthCloudGA__Account__c = personAccountId;
        encounter.Provider_Name__c = providerName;
        encounter.Title__c = 'Test';
        if( performDml ){
            INSERT encounter;
        }
        return encounter;
    }

    public static Knowledge__kav insertKnowledgeArticleVersion( String articleName, String resourceType, Boolean performDml,
            Id recordTypeId, Boolean isFeatured){
        Knowledge__kav newArticle = new knowledge__kav( Title=articleName, Summary=articleName, Urlname=articleName );
        newArticle.Resource_Type__c = resourceType;
        newArticle.IsVisibleInCsp = true;
        newArticle.RecordTypeId = recordTypeId;
        newArticle.Featured__c = isFeatured;
        if( performDml ){
            INSERT newArticle;
        }
        return newArticle;
    }

    public static Referral_Record__c insertReferralRecord( Id accId, Id articleId, Boolean performDml ){
        Referral_Record__c refRecord = new Referral_Record__c();
        refRecord.Knowledge_Article_Referred__c = articleId;
        refRecord.Patient__c = accId;
        if( performDml ){
            INSERT refRecord;
        }
        return refRecord;
    }

    
}