unpackaged/main/default/objects/HealthCloudGA__EhrMedicationStatement__c/HealthCloudGA__EhrMedicationStatement__c.object-meta.xml
<CustomObject>
    <description>A record of medication being taken by a patient, or that the medication has been given to a patient where the record is the result of a report from the patient or another clinician.</description>
    <label>EHR Medication Statement</label>
    <nameField>
        <displayFormat>Stat-{0}</displayFormat>
        <label>EHR Medication Statement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EHR Medication Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/HealthCloudGA__EhrMedicationStatement__c/fields/Medication__c.field-meta.xml
<CustomField>
    <fullName>Medication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medication</label>
    <referenceTo>Medication__c</referenceTo>
    <relationshipLabel>Medication Statements</relationshipLabel>
    <relationshipName>Medication_Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Medication__c/Medication__c.object-meta.xml
<CustomObject>
    <description>Holds information about medications in use by Patients.  Intended to be populated either manually, or via integration with an API.</description>
    <label>Medication</label>
    <nameField>
        <label>Medication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/EhrMedicationStatementSelector.cls
/**
 * Selector for EhrMedicationStatement records
 * 
 * @author Nitin Chandwani, Traction on Demand
 * @date 2020-09-04
 */
public with sharing class EhrMedicationStatementSelector {
    public List<HealthCloudGA__EhrMedicationStatement__c> selectByPersonAccount( Id accountId ){
        return [
                SELECT Id, HealthCloudGA__Account__c, Name, 
                Medication__c, Medication__r.Name, Notes__c 
                FROM HealthCloudGA__EhrMedicationStatement__c
                WHERE Medication__c != NULL AND HealthCloudGA__Account__c =: accountId
            ];
    }
}