unpackaged/main/default/objects/HealthCloudGA__EhrImmunization__c/HealthCloudGA__EhrImmunization__c.object-meta.xml
<CustomObject>
    <description>Immunization event information.</description>
    <label>EHR Immunization</label>
    <nameField>
        <displayFormat>Immu-{0}</displayFormat>
        <label>EHR Immunization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EHR Immunizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/HealthCloudGA__EhrImmunization__c/fields/Date_Administered__c.field-meta.xml
<CustomField>
    <fullName>Date_Administered__c</fullName>
    <description>Date Only field to capture the date the Immunization was administered.</description>
    <label>Date Administered</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/HealthCloudGA__EhrImmunization__c/fields/Immunization_Type__c.field-meta.xml
<CustomField>
    <fullName>Immunization_Type__c</fullName>
    <description>List from https://www.cdc.gov/vaccines/vpd/vaccines-list.html</description>
    <label>Immunization Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Adenovirus</fullName>
            </value>
            <value>
                <fullName>Anthrax</fullName>
            </value>
            <value>
                <fullName>Cholera</fullName>
            </value>
            <value>
                <fullName>Diphtheria</fullName>
            </value>
            <value>
                <fullName>Haemophilus influenzae type b (Hib)</fullName>
            </value>
            <value>
                <fullName>Hepatitis A</fullName>
            </value>
            <value>
                <fullName>Hepatitis B</fullName>
            </value>
            <value>
                <fullName>Human Papillomavirus (HPV)</fullName>
            </value>
            <value>
                <fullName>Japanese Encephalitis</fullName>
            </value>
            <value>
                <fullName>Measles</fullName>
            </value>
            <value>
                <fullName>Meningococcal</fullName>
            </value>
            <value>
                <fullName>Mumps</fullName>
            </value>
            <value>
                <fullName>Pertussis</fullName>
            </value>
            <value>
                <fullName>Pneumococcal</fullName>
            </value>
            <value>
                <fullName>Polio</fullName>
            </value>
            <value>
                <fullName>Rabies</fullName>
            </value>
            <value>
                <fullName>Rotavirus</fullName>
            </value>
            <value>
                <fullName>Rubella</fullName>
            </value>
            <value>
                <fullName>Seasonal Influenza (Flu) only</fullName>
            </value>
            <value>
                <fullName>Shingles</fullName>
            </value>
            <value>
                <fullName>Smallpox</fullName>
            </value>
            <value>
                <fullName>Tetanus</fullName>
            </value>
            <value>
                <fullName>Tuberculosis</fullName>
            </value>
            <value>
                <fullName>Typhoid Fever</fullName>
            </value>
            <value>
                <fullName>Varicella</fullName>
            </value>
            <value>
                <fullName>Yellow Fever</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ImmunizationSelector.cls
/* * Selector class for Immunization(HealthCloudGA__EhrImmunization__c) 
 *
 * @author Nitin Chandwani, Traction on Demand
 * @date 2020-10-01
 */
 public with sharing class ImmunizationSelector {
    public List<HealthCloudGA__EhrImmunization__c> getImmunizationsByAccountId( String accountId ) {
        if( String.isNotBlank( accountId ) ){
            return [SELECT Id, HealthCloudGA__Account__c, 
                    Name, Immunization_Type__c,
                    Date_Administered__c
                    FROM HealthCloudGA__EhrImmunization__c
                    WHERE HealthCloudGA__Account__c = :accountId ];
        }
        return null;
    }
}